# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Tasks\TaskFilterConfigDialog.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TaskFilterConfigDialog(object):
    def setupUi(self, TaskFilterConfigDialog):
        TaskFilterConfigDialog.setObjectName(_fromUtf8("TaskFilterConfigDialog"))
        TaskFilterConfigDialog.resize(562, 470)
        TaskFilterConfigDialog.setSizeGripEnabled(True)
        self.vboxlayout = QtGui.QVBoxLayout(TaskFilterConfigDialog)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.label = QtGui.QLabel(TaskFilterConfigDialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.vboxlayout.addWidget(self.label)
        self.descriptionGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.descriptionGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.descriptionGroup.setCheckable(True)
        self.descriptionGroup.setObjectName(_fromUtf8("descriptionGroup"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.descriptionGroup)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.descriptionEdit = QtGui.QLineEdit(self.descriptionGroup)
        self.descriptionEdit.setObjectName(_fromUtf8("descriptionEdit"))
        self.vboxlayout1.addWidget(self.descriptionEdit)
        self.vboxlayout.addWidget(self.descriptionGroup)
        self.filenameGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.filenameGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.filenameGroup.setCheckable(True)
        self.filenameGroup.setObjectName(_fromUtf8("filenameGroup"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.filenameGroup)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.filenameEdit = QtGui.QLineEdit(self.filenameGroup)
        self.filenameEdit.setObjectName(_fromUtf8("filenameEdit"))
        self.vboxlayout2.addWidget(self.filenameEdit)
        self.vboxlayout.addWidget(self.filenameGroup)
        self.typeGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.typeGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.typeGroup.setCheckable(True)
        self.typeGroup.setObjectName(_fromUtf8("typeGroup"))
        self.hboxlayout = QtGui.QHBoxLayout(self.typeGroup)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.standardRadioButton = QtGui.QRadioButton(self.typeGroup)
        self.standardRadioButton.setObjectName(_fromUtf8("standardRadioButton"))
        self.hboxlayout.addWidget(self.standardRadioButton)
        self.bugfixRadioButton = QtGui.QRadioButton(self.typeGroup)
        self.bugfixRadioButton.setObjectName(_fromUtf8("bugfixRadioButton"))
        self.hboxlayout.addWidget(self.bugfixRadioButton)
        self.vboxlayout.addWidget(self.typeGroup)
        self.scopeGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.scopeGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scopeGroup.setCheckable(True)
        self.scopeGroup.setObjectName(_fromUtf8("scopeGroup"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.scopeGroup)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.globalRadioButton = QtGui.QRadioButton(self.scopeGroup)
        self.globalRadioButton.setObjectName(_fromUtf8("globalRadioButton"))
        self.hboxlayout1.addWidget(self.globalRadioButton)
        self.projectRadioButton = QtGui.QRadioButton(self.scopeGroup)
        self.projectRadioButton.setObjectName(_fromUtf8("projectRadioButton"))
        self.hboxlayout1.addWidget(self.projectRadioButton)
        self.vboxlayout.addWidget(self.scopeGroup)
        self.statusGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.statusGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.statusGroup.setCheckable(True)
        self.statusGroup.setObjectName(_fromUtf8("statusGroup"))
        self.hboxlayout2 = QtGui.QHBoxLayout(self.statusGroup)
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.uncompletedRadioButton = QtGui.QRadioButton(self.statusGroup)
        self.uncompletedRadioButton.setObjectName(_fromUtf8("uncompletedRadioButton"))
        self.hboxlayout2.addWidget(self.uncompletedRadioButton)
        self.completedRadioButton = QtGui.QRadioButton(self.statusGroup)
        self.completedRadioButton.setObjectName(_fromUtf8("completedRadioButton"))
        self.hboxlayout2.addWidget(self.completedRadioButton)
        self.vboxlayout.addWidget(self.statusGroup)
        self.priorityGroup = QtGui.QGroupBox(TaskFilterConfigDialog)
        self.priorityGroup.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.priorityGroup.setCheckable(True)
        self.priorityGroup.setObjectName(_fromUtf8("priorityGroup"))
        self.hboxlayout3 = QtGui.QHBoxLayout(self.priorityGroup)
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.priorityHighCheckBox = QtGui.QCheckBox(self.priorityGroup)
        self.priorityHighCheckBox.setObjectName(_fromUtf8("priorityHighCheckBox"))
        self.hboxlayout3.addWidget(self.priorityHighCheckBox)
        self.priorityNormalCheckBox = QtGui.QCheckBox(self.priorityGroup)
        self.priorityNormalCheckBox.setObjectName(_fromUtf8("priorityNormalCheckBox"))
        self.hboxlayout3.addWidget(self.priorityNormalCheckBox)
        self.priorityLowCheckBox = QtGui.QCheckBox(self.priorityGroup)
        self.priorityLowCheckBox.setObjectName(_fromUtf8("priorityLowCheckBox"))
        self.hboxlayout3.addWidget(self.priorityLowCheckBox)
        self.vboxlayout.addWidget(self.priorityGroup)
        self.buttonBox = QtGui.QDialogButtonBox(TaskFilterConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(TaskFilterConfigDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TaskFilterConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TaskFilterConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(TaskFilterConfigDialog)
        TaskFilterConfigDialog.setTabOrder(self.descriptionGroup, self.descriptionEdit)
        TaskFilterConfigDialog.setTabOrder(self.descriptionEdit, self.filenameGroup)
        TaskFilterConfigDialog.setTabOrder(self.filenameGroup, self.filenameEdit)
        TaskFilterConfigDialog.setTabOrder(self.filenameEdit, self.typeGroup)
        TaskFilterConfigDialog.setTabOrder(self.typeGroup, self.standardRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.standardRadioButton, self.bugfixRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.bugfixRadioButton, self.scopeGroup)
        TaskFilterConfigDialog.setTabOrder(self.scopeGroup, self.globalRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.globalRadioButton, self.projectRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.projectRadioButton, self.statusGroup)
        TaskFilterConfigDialog.setTabOrder(self.statusGroup, self.uncompletedRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.uncompletedRadioButton, self.completedRadioButton)
        TaskFilterConfigDialog.setTabOrder(self.completedRadioButton, self.priorityGroup)
        TaskFilterConfigDialog.setTabOrder(self.priorityGroup, self.priorityHighCheckBox)
        TaskFilterConfigDialog.setTabOrder(self.priorityHighCheckBox, self.priorityNormalCheckBox)
        TaskFilterConfigDialog.setTabOrder(self.priorityNormalCheckBox, self.priorityLowCheckBox)

    def retranslateUi(self, TaskFilterConfigDialog):
        TaskFilterConfigDialog.setWindowTitle(_translate("TaskFilterConfigDialog", "Task filter configuration", None))
        self.label.setText(_translate("TaskFilterConfigDialog", "Select the categories, the tasks list should be filtered on. Within each category, enter the selection criteria. The enabled categories are combined using an \"<b>and</b>\" operation.", None))
        self.descriptionGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task description", None))
        self.descriptionGroup.setTitle(_translate("TaskFilterConfigDialog", "Description", None))
        self.descriptionEdit.setToolTip(_translate("TaskFilterConfigDialog", "Enter the description filter as a regular expression.", None))
        self.filenameGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task filename", None))
        self.filenameGroup.setTitle(_translate("TaskFilterConfigDialog", "Filename", None))
        self.filenameEdit.setToolTip(_translate("TaskFilterConfigDialog", "Enter the filename filter as a wildcard expression.", None))
        self.typeGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task type", None))
        self.typeGroup.setTitle(_translate("TaskFilterConfigDialog", "Type", None))
        self.standardRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show standard tasks only", None))
        self.standardRadioButton.setText(_translate("TaskFilterConfigDialog", "Standard tasks", None))
        self.bugfixRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show bugfix tasks only", None))
        self.bugfixRadioButton.setText(_translate("TaskFilterConfigDialog", "Bugfix tasks", None))
        self.scopeGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task scope", None))
        self.scopeGroup.setTitle(_translate("TaskFilterConfigDialog", "Scope", None))
        self.globalRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show global tasks only", None))
        self.globalRadioButton.setText(_translate("TaskFilterConfigDialog", "Global tasks", None))
        self.projectRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show project tasks only", None))
        self.projectRadioButton.setText(_translate("TaskFilterConfigDialog", "Project tasks", None))
        self.statusGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task completion status", None))
        self.statusGroup.setTitle(_translate("TaskFilterConfigDialog", "Completion status", None))
        self.uncompletedRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show uncompleted tasks only", None))
        self.uncompletedRadioButton.setText(_translate("TaskFilterConfigDialog", "Uncompleted tasks", None))
        self.completedRadioButton.setToolTip(_translate("TaskFilterConfigDialog", "Select to show completed tasks only", None))
        self.completedRadioButton.setText(_translate("TaskFilterConfigDialog", "Completed tasks", None))
        self.priorityGroup.setToolTip(_translate("TaskFilterConfigDialog", "Select to filter on the task priority", None))
        self.priorityGroup.setTitle(_translate("TaskFilterConfigDialog", "Priority", None))
        self.priorityHighCheckBox.setToolTip(_translate("TaskFilterConfigDialog", "Select to show high priority tasks", None))
        self.priorityHighCheckBox.setText(_translate("TaskFilterConfigDialog", "High priority tasks", None))
        self.priorityNormalCheckBox.setToolTip(_translate("TaskFilterConfigDialog", "Select to show normal priority tasks", None))
        self.priorityNormalCheckBox.setText(_translate("TaskFilterConfigDialog", "Normal priority tasks", None))
        self.priorityLowCheckBox.setToolTip(_translate("TaskFilterConfigDialog", "Select to show low priority tasks", None))
        self.priorityLowCheckBox.setText(_translate("TaskFilterConfigDialog", "Low priority tasks", None))

