# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Project\PropertiesDialog.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PropertiesDialog(object):
    def setupUi(self, PropertiesDialog):
        PropertiesDialog.setObjectName(_fromUtf8("PropertiesDialog"))
        PropertiesDialog.resize(600, 550)
        PropertiesDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        PropertiesDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtGui.QVBoxLayout(PropertiesDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.nameLabel = QtGui.QLabel(PropertiesDialog)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameEdit = QtGui.QLineEdit(PropertiesDialog)
        self.nameEdit.setObjectName(_fromUtf8("nameEdit"))
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.spellPropertiesButton = QtGui.QPushButton(PropertiesDialog)
        self.spellPropertiesButton.setObjectName(_fromUtf8("spellPropertiesButton"))
        self.gridLayout.addWidget(self.spellPropertiesButton, 1, 1, 1, 1)
        self.textLabel1 = QtGui.QLabel(PropertiesDialog)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridLayout.addWidget(self.textLabel1, 2, 0, 1, 1)
        self.languageComboBox = QtGui.QComboBox(PropertiesDialog)
        self.languageComboBox.setObjectName(_fromUtf8("languageComboBox"))
        self.gridLayout.addWidget(self.languageComboBox, 2, 1, 1, 1)
        self.mixedLanguageCheckBox = QtGui.QCheckBox(PropertiesDialog)
        self.mixedLanguageCheckBox.setObjectName(_fromUtf8("mixedLanguageCheckBox"))
        self.gridLayout.addWidget(self.mixedLanguageCheckBox, 3, 1, 1, 1)
        self.textLabel1_2 = QtGui.QLabel(PropertiesDialog)
        self.textLabel1_2.setObjectName(_fromUtf8("textLabel1_2"))
        self.gridLayout.addWidget(self.textLabel1_2, 4, 0, 1, 1)
        self.projectTypeComboBox = QtGui.QComboBox(PropertiesDialog)
        self.projectTypeComboBox.setObjectName(_fromUtf8("projectTypeComboBox"))
        self.gridLayout.addWidget(self.projectTypeComboBox, 4, 1, 1, 1)
        self.dirLabel = QtGui.QLabel(PropertiesDialog)
        self.dirLabel.setObjectName(_fromUtf8("dirLabel"))
        self.gridLayout.addWidget(self.dirLabel, 5, 0, 1, 1)
        self.dirEdit = QtGui.QLineEdit(PropertiesDialog)
        self.dirEdit.setObjectName(_fromUtf8("dirEdit"))
        self.gridLayout.addWidget(self.dirEdit, 5, 1, 1, 1)
        self.dirButton = QtGui.QPushButton(PropertiesDialog)
        self.dirButton.setObjectName(_fromUtf8("dirButton"))
        self.gridLayout.addWidget(self.dirButton, 5, 2, 1, 1)
        self.versionLabel = QtGui.QLabel(PropertiesDialog)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.gridLayout.addWidget(self.versionLabel, 6, 0, 1, 1)
        self.versionEdit = QtGui.QLineEdit(PropertiesDialog)
        self.versionEdit.setObjectName(_fromUtf8("versionEdit"))
        self.gridLayout.addWidget(self.versionEdit, 6, 1, 1, 1)
        self.mainscriptLabel = QtGui.QLabel(PropertiesDialog)
        self.mainscriptLabel.setObjectName(_fromUtf8("mainscriptLabel"))
        self.gridLayout.addWidget(self.mainscriptLabel, 7, 0, 1, 1)
        self.mainscriptEdit = QtGui.QLineEdit(PropertiesDialog)
        self.mainscriptEdit.setObjectName(_fromUtf8("mainscriptEdit"))
        self.gridLayout.addWidget(self.mainscriptEdit, 7, 1, 1, 1)
        self.mainscriptButton = QtGui.QPushButton(PropertiesDialog)
        self.mainscriptButton.setObjectName(_fromUtf8("mainscriptButton"))
        self.gridLayout.addWidget(self.mainscriptButton, 7, 2, 1, 1)
        self.transPropertiesButton = QtGui.QPushButton(PropertiesDialog)
        self.transPropertiesButton.setObjectName(_fromUtf8("transPropertiesButton"))
        self.gridLayout.addWidget(self.transPropertiesButton, 8, 1, 1, 1)
        self.authorLabel = QtGui.QLabel(PropertiesDialog)
        self.authorLabel.setObjectName(_fromUtf8("authorLabel"))
        self.gridLayout.addWidget(self.authorLabel, 9, 0, 1, 1)
        self.authorEdit = QtGui.QLineEdit(PropertiesDialog)
        self.authorEdit.setObjectName(_fromUtf8("authorEdit"))
        self.gridLayout.addWidget(self.authorEdit, 9, 1, 1, 1)
        self.emailLabel = QtGui.QLabel(PropertiesDialog)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.gridLayout.addWidget(self.emailLabel, 10, 0, 1, 1)
        self.emailEdit = QtGui.QLineEdit(PropertiesDialog)
        self.emailEdit.setObjectName(_fromUtf8("emailEdit"))
        self.gridLayout.addWidget(self.emailEdit, 10, 1, 1, 1)
        self.descriptionLabel = QtGui.QLabel(PropertiesDialog)
        self.descriptionLabel.setAlignment(QtCore.Qt.AlignTop)
        self.descriptionLabel.setObjectName(_fromUtf8("descriptionLabel"))
        self.gridLayout.addWidget(self.descriptionLabel, 11, 0, 1, 1)
        self.descriptionEdit = QtGui.QTextEdit(PropertiesDialog)
        self.descriptionEdit.setTabChangesFocus(True)
        self.descriptionEdit.setAcceptRichText(False)
        self.descriptionEdit.setObjectName(_fromUtf8("descriptionEdit"))
        self.gridLayout.addWidget(self.descriptionEdit, 11, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.vcsCheckBox = QtGui.QCheckBox(PropertiesDialog)
        self.vcsCheckBox.setObjectName(_fromUtf8("vcsCheckBox"))
        self.verticalLayout.addWidget(self.vcsCheckBox)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.vcsLabel = QtGui.QLabel(PropertiesDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vcsLabel.sizePolicy().hasHeightForWidth())
        self.vcsLabel.setSizePolicy(sizePolicy)
        self.vcsLabel.setText(_fromUtf8(""))
        self.vcsLabel.setObjectName(_fromUtf8("vcsLabel"))
        self._2.addWidget(self.vcsLabel)
        self.vcsInfoButton = QtGui.QPushButton(PropertiesDialog)
        self.vcsInfoButton.setObjectName(_fromUtf8("vcsInfoButton"))
        self._2.addWidget(self.vcsInfoButton)
        self.verticalLayout.addLayout(self._2)
        self.buttonBox = QtGui.QDialogButtonBox(PropertiesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.nameLabel.setBuddy(self.nameEdit)
        self.textLabel1.setBuddy(self.languageComboBox)
        self.textLabel1_2.setBuddy(self.projectTypeComboBox)
        self.dirLabel.setBuddy(self.dirEdit)
        self.versionLabel.setBuddy(self.versionEdit)
        self.mainscriptLabel.setBuddy(self.mainscriptEdit)
        self.authorLabel.setBuddy(self.authorEdit)
        self.emailLabel.setBuddy(self.emailEdit)
        self.descriptionLabel.setBuddy(self.descriptionEdit)

        self.retranslateUi(PropertiesDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PropertiesDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PropertiesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PropertiesDialog)
        PropertiesDialog.setTabOrder(self.nameEdit, self.spellPropertiesButton)
        PropertiesDialog.setTabOrder(self.spellPropertiesButton, self.languageComboBox)
        PropertiesDialog.setTabOrder(self.languageComboBox, self.mixedLanguageCheckBox)
        PropertiesDialog.setTabOrder(self.mixedLanguageCheckBox, self.projectTypeComboBox)
        PropertiesDialog.setTabOrder(self.projectTypeComboBox, self.dirEdit)
        PropertiesDialog.setTabOrder(self.dirEdit, self.dirButton)
        PropertiesDialog.setTabOrder(self.dirButton, self.versionEdit)
        PropertiesDialog.setTabOrder(self.versionEdit, self.mainscriptEdit)
        PropertiesDialog.setTabOrder(self.mainscriptEdit, self.mainscriptButton)
        PropertiesDialog.setTabOrder(self.mainscriptButton, self.transPropertiesButton)
        PropertiesDialog.setTabOrder(self.transPropertiesButton, self.authorEdit)
        PropertiesDialog.setTabOrder(self.authorEdit, self.emailEdit)
        PropertiesDialog.setTabOrder(self.emailEdit, self.descriptionEdit)
        PropertiesDialog.setTabOrder(self.descriptionEdit, self.vcsCheckBox)
        PropertiesDialog.setTabOrder(self.vcsCheckBox, self.vcsInfoButton)
        PropertiesDialog.setTabOrder(self.vcsInfoButton, self.buttonBox)

    def retranslateUi(self, PropertiesDialog):
        PropertiesDialog.setWindowTitle(_translate("PropertiesDialog", "Project Properties", None))
        PropertiesDialog.setWhatsThis(_translate("PropertiesDialog", "<b>Project Properties Dialog</b>\n"
"<p>This dialog is used to show and edit the projects properties.</p>\n"
"<p>If the project is controlled by a version control system, the \"Show Repository Info\" button displays information about the repository.</p>", None))
        self.nameLabel.setText(_translate("PropertiesDialog", "Project &Name:", None))
        self.nameEdit.setToolTip(_translate("PropertiesDialog", "Enter the project name", None))
        self.nameEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Project Name</b>\n"
"<p>Enter the project name</p>", None))
        self.spellPropertiesButton.setToolTip(_translate("PropertiesDialog", "Press to edit the spell checking properties", None))
        self.spellPropertiesButton.setText(_translate("PropertiesDialog", "Spell Checking Properties...", None))
        self.textLabel1.setText(_translate("PropertiesDialog", "&Progr. Language:", None))
        self.languageComboBox.setToolTip(_translate("PropertiesDialog", "Select the project\'s programming language", None))
        self.mixedLanguageCheckBox.setToolTip(_translate("PropertiesDialog", "Select, if the project uses other programming languages as well", None))
        self.mixedLanguageCheckBox.setText(_translate("PropertiesDialog", "Mi&xed programming languages", None))
        self.mixedLanguageCheckBox.setShortcut(_translate("PropertiesDialog", "Alt+X", None))
        self.textLabel1_2.setText(_translate("PropertiesDialog", "Project &Type:", None))
        self.projectTypeComboBox.setToolTip(_translate("PropertiesDialog", "Select the type of the project", None))
        self.dirLabel.setText(_translate("PropertiesDialog", "Project &Directory:", None))
        self.dirEdit.setToolTip(_translate("PropertiesDialog", "Enter the project directory", None))
        self.dirEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Project Directory</b>\n"
"<p>Enter the project directory. You may select it\n"
" with a dialog by pressing the button to the right.</p>", None))
        self.dirButton.setToolTip(_translate("PropertiesDialog", "Show directory selection dialog", None))
        self.dirButton.setWhatsThis(_translate("PropertiesDialog", "<b>Project Directory</b>\n"
"<p>Select a project directory via a directory selection dialog.</p>", None))
        self.dirButton.setText(_translate("PropertiesDialog", "...", None))
        self.versionLabel.setText(_translate("PropertiesDialog", "&Version No.:", None))
        self.versionEdit.setToolTip(_translate("PropertiesDialog", "Enter the version number", None))
        self.versionEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Version No.</b>\n"
"<p>Enter the version no.</p>", None))
        self.mainscriptLabel.setText(_translate("PropertiesDialog", "&Main Script:", None))
        self.mainscriptEdit.setToolTip(_translate("PropertiesDialog", "Enter the main script", None))
        self.mainscriptEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Main Script</b>\n"
"<p>Enter the main script of the project. You may select it\n"
" with a dialog by pressing the button to the right.</p>", None))
        self.mainscriptButton.setToolTip(_translate("PropertiesDialog", "Show file selection dialog", None))
        self.mainscriptButton.setWhatsThis(_translate("PropertiesDialog", "<b>Main Script</b>\n"
"<p>Select the projects main script via a file selection dialog.</p>", None))
        self.mainscriptButton.setText(_translate("PropertiesDialog", "...", None))
        self.transPropertiesButton.setToolTip(_translate("PropertiesDialog", "Press to edit the translations properties", None))
        self.transPropertiesButton.setText(_translate("PropertiesDialog", "Translations Properties...", None))
        self.authorLabel.setText(_translate("PropertiesDialog", "&Author:", None))
        self.authorEdit.setToolTip(_translate("PropertiesDialog", "Enter authors name", None))
        self.authorEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Author</b>\n"
"<p>Enter the name of the author.</p>", None))
        self.emailLabel.setText(_translate("PropertiesDialog", "&Email:", None))
        self.emailEdit.setToolTip(_translate("PropertiesDialog", "Enter authors email", None))
        self.emailEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Email</b>\n"
"<p>Enter the email address of the author</p>", None))
        self.descriptionLabel.setText(_translate("PropertiesDialog", "&Description:", None))
        self.descriptionEdit.setToolTip(_translate("PropertiesDialog", "Enter description", None))
        self.descriptionEdit.setWhatsThis(_translate("PropertiesDialog", "<b>Description</b>\n"
"<p>Enter a short description for the project.</p>", None))
        self.vcsCheckBox.setToolTip(_translate("PropertiesDialog", "Select to create a version controlled project", None))
        self.vcsCheckBox.setText(_translate("PropertiesDialog", "Version Controlled Project", None))
        self.vcsInfoButton.setToolTip(_translate("PropertiesDialog", "Press to show information about the repository", None))
        self.vcsInfoButton.setText(_translate("PropertiesDialog", "Show &Repository Info", None))
        self.vcsInfoButton.setShortcut(_translate("PropertiesDialog", "Alt+R", None))

