# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Plugins\DocumentationPlugins\Ericdoc\EricdocConfigDialog.ui'
#
# Created: Fri Apr 18 09:56:41 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EricdocConfigDialog(object):
    def setupUi(self, EricdocConfigDialog):
        EricdocConfigDialog.setObjectName(_fromUtf8("EricdocConfigDialog"))
        EricdocConfigDialog.resize(542, 550)
        EricdocConfigDialog.setSizeGripEnabled(True)
        self.vboxlayout = QtGui.QVBoxLayout(EricdocConfigDialog)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tabWidget = QtGui.QTabWidget(EricdocConfigDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.generalTab = QtGui.QWidget()
        self.generalTab.setObjectName(_fromUtf8("generalTab"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.generalTab)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.TextLabel6 = QtGui.QLabel(self.generalTab)
        self.TextLabel6.setObjectName(_fromUtf8("TextLabel6"))
        self.hboxlayout.addWidget(self.TextLabel6)
        self.outputDirEdit = QtGui.QLineEdit(self.generalTab)
        self.outputDirEdit.setObjectName(_fromUtf8("outputDirEdit"))
        self.hboxlayout.addWidget(self.outputDirEdit)
        self.outputDirButton = QtGui.QPushButton(self.generalTab)
        self.outputDirButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputDirButton.setObjectName(_fromUtf8("outputDirButton"))
        self.hboxlayout.addWidget(self.outputDirButton)
        self.vboxlayout1.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.textLabel1_3 = QtGui.QLabel(self.generalTab)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.hboxlayout1.addWidget(self.textLabel1_3)
        self.sourceExtEdit = QtGui.QLineEdit(self.generalTab)
        self.sourceExtEdit.setObjectName(_fromUtf8("sourceExtEdit"))
        self.hboxlayout1.addWidget(self.sourceExtEdit)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.recursionCheckBox = QtGui.QCheckBox(self.generalTab)
        self.recursionCheckBox.setObjectName(_fromUtf8("recursionCheckBox"))
        self.hboxlayout2.addWidget(self.recursionCheckBox)
        self.noindexCheckBox = QtGui.QCheckBox(self.generalTab)
        self.noindexCheckBox.setObjectName(_fromUtf8("noindexCheckBox"))
        self.hboxlayout2.addWidget(self.noindexCheckBox)
        spacerItem = QtGui.QSpacerItem(145, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.noemptyCheckBox = QtGui.QCheckBox(self.generalTab)
        self.noemptyCheckBox.setObjectName(_fromUtf8("noemptyCheckBox"))
        self.hboxlayout3.addWidget(self.noemptyCheckBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout3.addItem(spacerItem1)
        self.vboxlayout1.addLayout(self.hboxlayout3)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setObjectName(_fromUtf8("hboxlayout4"))
        self.label = QtGui.QLabel(self.generalTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout4.addWidget(self.label)
        self.excludeFilesEdit = QtGui.QLineEdit(self.generalTab)
        self.excludeFilesEdit.setObjectName(_fromUtf8("excludeFilesEdit"))
        self.hboxlayout4.addWidget(self.excludeFilesEdit)
        self.vboxlayout1.addLayout(self.hboxlayout4)
        self.groupBox = QtGui.QGroupBox(self.generalTab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.ignoreDirEdit = QtGui.QLineEdit(self.groupBox)
        self.ignoreDirEdit.setObjectName(_fromUtf8("ignoreDirEdit"))
        self.gridlayout.addWidget(self.ignoreDirEdit, 1, 2, 1, 1)
        self.addButton = QtGui.QPushButton(self.groupBox)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridlayout.addWidget(self.addButton, 1, 1, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.groupBox)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.gridlayout.addWidget(self.deleteButton, 1, 0, 1, 1)
        self.ignoreDirButton = QtGui.QPushButton(self.groupBox)
        self.ignoreDirButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ignoreDirButton.setObjectName(_fromUtf8("ignoreDirButton"))
        self.gridlayout.addWidget(self.ignoreDirButton, 1, 3, 1, 1)
        self.ignoreDirsList = QtGui.QListWidget(self.groupBox)
        self.ignoreDirsList.setObjectName(_fromUtf8("ignoreDirsList"))
        self.gridlayout.addWidget(self.ignoreDirsList, 0, 0, 1, 4)
        self.vboxlayout1.addWidget(self.groupBox)
        self.tabWidget.addTab(self.generalTab, _fromUtf8(""))
        self.styleTab = QtGui.QWidget()
        self.styleTab.setObjectName(_fromUtf8("styleTab"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.styleTab)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.groupBox_3 = QtGui.QGroupBox(self.styleTab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.hboxlayout5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.hboxlayout5.setObjectName(_fromUtf8("hboxlayout5"))
        self.cssEdit = QtGui.QLineEdit(self.groupBox_3)
        self.cssEdit.setObjectName(_fromUtf8("cssEdit"))
        self.hboxlayout5.addWidget(self.cssEdit)
        self.cssButton = QtGui.QPushButton(self.groupBox_3)
        self.cssButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cssButton.setObjectName(_fromUtf8("cssButton"))
        self.hboxlayout5.addWidget(self.cssButton)
        self.vboxlayout2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.styleTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.cfBgButton = QtGui.QPushButton(self.groupBox_2)
        self.cfBgButton.setObjectName(_fromUtf8("cfBgButton"))
        self.gridlayout1.addWidget(self.cfBgButton, 3, 1, 1, 1)
        self.cfFgButton = QtGui.QPushButton(self.groupBox_2)
        self.cfFgButton.setObjectName(_fromUtf8("cfFgButton"))
        self.gridlayout1.addWidget(self.cfFgButton, 3, 0, 1, 1)
        self.l2BgButton = QtGui.QPushButton(self.groupBox_2)
        self.l2BgButton.setObjectName(_fromUtf8("l2BgButton"))
        self.gridlayout1.addWidget(self.l2BgButton, 2, 1, 1, 1)
        self.l2FgButton = QtGui.QPushButton(self.groupBox_2)
        self.l2FgButton.setObjectName(_fromUtf8("l2FgButton"))
        self.gridlayout1.addWidget(self.l2FgButton, 2, 0, 1, 1)
        self.l1BgButton = QtGui.QPushButton(self.groupBox_2)
        self.l1BgButton.setObjectName(_fromUtf8("l1BgButton"))
        self.gridlayout1.addWidget(self.l1BgButton, 1, 1, 1, 1)
        self.l1FgButton = QtGui.QPushButton(self.groupBox_2)
        self.l1FgButton.setObjectName(_fromUtf8("l1FgButton"))
        self.gridlayout1.addWidget(self.l1FgButton, 1, 0, 1, 1)
        self.bodyBgButton = QtGui.QPushButton(self.groupBox_2)
        self.bodyBgButton.setObjectName(_fromUtf8("bodyBgButton"))
        self.gridlayout1.addWidget(self.bodyBgButton, 0, 1, 1, 1)
        self.bodyFgButton = QtGui.QPushButton(self.groupBox_2)
        self.bodyFgButton.setObjectName(_fromUtf8("bodyFgButton"))
        self.gridlayout1.addWidget(self.bodyFgButton, 0, 0, 1, 1)
        self.linkFgButton = QtGui.QPushButton(self.groupBox_2)
        self.linkFgButton.setObjectName(_fromUtf8("linkFgButton"))
        self.gridlayout1.addWidget(self.linkFgButton, 4, 0, 1, 1)
        self.sample = QtGui.QTextEdit(self.groupBox_2)
        self.sample.setReadOnly(True)
        self.sample.setObjectName(_fromUtf8("sample"))
        self.gridlayout1.addWidget(self.sample, 5, 0, 1, 2)
        self.vboxlayout2.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.styleTab, _fromUtf8(""))
        self.qtHelpTab = QtGui.QWidget()
        self.qtHelpTab.setObjectName(_fromUtf8("qtHelpTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.qtHelpTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtHelpGroup = QtGui.QGroupBox(self.qtHelpTab)
        self.qtHelpGroup.setCheckable(True)
        self.qtHelpGroup.setChecked(False)
        self.qtHelpGroup.setObjectName(_fromUtf8("qtHelpGroup"))
        self.gridLayout = QtGui.QGridLayout(self.qtHelpGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TextLabel6_2 = QtGui.QLabel(self.qtHelpGroup)
        self.TextLabel6_2.setObjectName(_fromUtf8("TextLabel6_2"))
        self.gridLayout.addWidget(self.TextLabel6_2, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.qtHelpDirEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpDirEdit.setObjectName(_fromUtf8("qtHelpDirEdit"))
        self.horizontalLayout.addWidget(self.qtHelpDirEdit)
        self.qtHelpDirButton = QtGui.QPushButton(self.qtHelpGroup)
        self.qtHelpDirButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.qtHelpDirButton.setObjectName(_fromUtf8("qtHelpDirButton"))
        self.horizontalLayout.addWidget(self.qtHelpDirButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.qtHelpGroup)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.qtHelpNamespaceEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpNamespaceEdit.setObjectName(_fromUtf8("qtHelpNamespaceEdit"))
        self.gridLayout.addWidget(self.qtHelpNamespaceEdit, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.qtHelpGroup)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.qtHelpFolderEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpFolderEdit.setObjectName(_fromUtf8("qtHelpFolderEdit"))
        self.gridLayout.addWidget(self.qtHelpFolderEdit, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.qtHelpGroup)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.qtHelpFilterNameEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpFilterNameEdit.setObjectName(_fromUtf8("qtHelpFilterNameEdit"))
        self.gridLayout.addWidget(self.qtHelpFilterNameEdit, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.qtHelpGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.qtHelpFilterAttributesEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpFilterAttributesEdit.setObjectName(_fromUtf8("qtHelpFilterAttributesEdit"))
        self.gridLayout.addWidget(self.qtHelpFilterAttributesEdit, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.qtHelpGroup)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.qtHelpTitleEdit = QtGui.QLineEdit(self.qtHelpGroup)
        self.qtHelpTitleEdit.setObjectName(_fromUtf8("qtHelpTitleEdit"))
        self.gridLayout.addWidget(self.qtHelpTitleEdit, 5, 1, 1, 1)
        self.qtHelpGenerateCollectionCheckBox = QtGui.QCheckBox(self.qtHelpGroup)
        self.qtHelpGenerateCollectionCheckBox.setObjectName(_fromUtf8("qtHelpGenerateCollectionCheckBox"))
        self.gridLayout.addWidget(self.qtHelpGenerateCollectionCheckBox, 6, 0, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 271, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 1, 1, 1)
        self.verticalLayout.addWidget(self.qtHelpGroup)
        self.tabWidget.addTab(self.qtHelpTab, _fromUtf8(""))
        self.vboxlayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(EricdocConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(EricdocConfigDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), EricdocConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EricdocConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EricdocConfigDialog)
        EricdocConfigDialog.setTabOrder(self.tabWidget, self.outputDirEdit)
        EricdocConfigDialog.setTabOrder(self.outputDirEdit, self.sourceExtEdit)
        EricdocConfigDialog.setTabOrder(self.sourceExtEdit, self.recursionCheckBox)
        EricdocConfigDialog.setTabOrder(self.recursionCheckBox, self.noindexCheckBox)
        EricdocConfigDialog.setTabOrder(self.noindexCheckBox, self.noemptyCheckBox)
        EricdocConfigDialog.setTabOrder(self.noemptyCheckBox, self.excludeFilesEdit)
        EricdocConfigDialog.setTabOrder(self.excludeFilesEdit, self.ignoreDirsList)
        EricdocConfigDialog.setTabOrder(self.ignoreDirsList, self.ignoreDirEdit)
        EricdocConfigDialog.setTabOrder(self.ignoreDirEdit, self.addButton)
        EricdocConfigDialog.setTabOrder(self.addButton, self.deleteButton)
        EricdocConfigDialog.setTabOrder(self.deleteButton, self.cssEdit)
        EricdocConfigDialog.setTabOrder(self.cssEdit, self.bodyFgButton)
        EricdocConfigDialog.setTabOrder(self.bodyFgButton, self.bodyBgButton)
        EricdocConfigDialog.setTabOrder(self.bodyBgButton, self.l1FgButton)
        EricdocConfigDialog.setTabOrder(self.l1FgButton, self.l1BgButton)
        EricdocConfigDialog.setTabOrder(self.l1BgButton, self.l2FgButton)
        EricdocConfigDialog.setTabOrder(self.l2FgButton, self.l2BgButton)
        EricdocConfigDialog.setTabOrder(self.l2BgButton, self.cfFgButton)
        EricdocConfigDialog.setTabOrder(self.cfFgButton, self.cfBgButton)
        EricdocConfigDialog.setTabOrder(self.cfBgButton, self.linkFgButton)
        EricdocConfigDialog.setTabOrder(self.linkFgButton, self.sample)
        EricdocConfigDialog.setTabOrder(self.sample, self.qtHelpGroup)
        EricdocConfigDialog.setTabOrder(self.qtHelpGroup, self.qtHelpDirEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpDirEdit, self.qtHelpNamespaceEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpNamespaceEdit, self.qtHelpFolderEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpFolderEdit, self.qtHelpFilterNameEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpFilterNameEdit, self.qtHelpFilterAttributesEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpFilterAttributesEdit, self.qtHelpTitleEdit)
        EricdocConfigDialog.setTabOrder(self.qtHelpTitleEdit, self.qtHelpGenerateCollectionCheckBox)
        EricdocConfigDialog.setTabOrder(self.qtHelpGenerateCollectionCheckBox, self.buttonBox)

    def retranslateUi(self, EricdocConfigDialog):
        EricdocConfigDialog.setWindowTitle(_translate("EricdocConfigDialog", "Ericdoc Configuration", None))
        self.TextLabel6.setText(_translate("EricdocConfigDialog", "Output Directory:", None))
        self.outputDirEdit.setToolTip(_translate("EricdocConfigDialog", "Enter an output directory", None))
        self.outputDirButton.setToolTip(_translate("EricdocConfigDialog", "Press to open a directory selection dialog", None))
        self.outputDirButton.setText(_translate("EricdocConfigDialog", "...", None))
        self.textLabel1_3.setText(_translate("EricdocConfigDialog", "Additional source extensions:", None))
        self.sourceExtEdit.setToolTip(_translate("EricdocConfigDialog", "Enter additional source extensions separated by a comma", None))
        self.recursionCheckBox.setToolTip(_translate("EricdocConfigDialog", "Select to recurse into subdirectories", None))
        self.recursionCheckBox.setText(_translate("EricdocConfigDialog", "Recurse into subdirectories", None))
        self.noindexCheckBox.setToolTip(_translate("EricdocConfigDialog", "Select, if no index files should be generated", None))
        self.noindexCheckBox.setText(_translate("EricdocConfigDialog", "Don\'t generate index files", None))
        self.noemptyCheckBox.setToolTip(_translate("EricdocConfigDialog", "Select to exclude empty modules", None))
        self.noemptyCheckBox.setText(_translate("EricdocConfigDialog", "Don\'t include empty modules", None))
        self.label.setText(_translate("EricdocConfigDialog", "Exclude Files:", None))
        self.excludeFilesEdit.setToolTip(_translate("EricdocConfigDialog", "Enter filename patterns of files to be excluded separated by a comma", None))
        self.groupBox.setTitle(_translate("EricdocConfigDialog", "Exclude Directories", None))
        self.ignoreDirEdit.setToolTip(_translate("EricdocConfigDialog", "Enter a directory basename to be ignored", None))
        self.addButton.setToolTip(_translate("EricdocConfigDialog", "Press to add the entered directory to the list", None))
        self.addButton.setText(_translate("EricdocConfigDialog", "Add", None))
        self.deleteButton.setToolTip(_translate("EricdocConfigDialog", "Press to delete the selected directory from the list", None))
        self.deleteButton.setText(_translate("EricdocConfigDialog", "Delete", None))
        self.ignoreDirButton.setToolTip(_translate("EricdocConfigDialog", "Press to open a directory selection dialog", None))
        self.ignoreDirButton.setText(_translate("EricdocConfigDialog", "...", None))
        self.ignoreDirsList.setToolTip(_translate("EricdocConfigDialog", "List of directory basenames to be ignored", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("EricdocConfigDialog", "General", None))
        self.groupBox_3.setTitle(_translate("EricdocConfigDialog", "Style Sheet", None))
        self.cssEdit.setToolTip(_translate("EricdocConfigDialog", "Enter the filename of a CSS style sheet. Leave empty to use the colours defined below.", None))
        self.cssButton.setToolTip(_translate("EricdocConfigDialog", "Press to open a file selection dialog", None))
        self.cssButton.setText(_translate("EricdocConfigDialog", "...", None))
        self.groupBox_2.setTitle(_translate("EricdocConfigDialog", "Colours", None))
        self.cfBgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the class and function header background colour.", None))
        self.cfBgButton.setText(_translate("EricdocConfigDialog", "Class/Function Header Background", None))
        self.cfFgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the class and function header foreground colour.", None))
        self.cfFgButton.setText(_translate("EricdocConfigDialog", "Class/Function Header Foreground", None))
        self.l2BgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the level 2 header background colour.", None))
        self.l2BgButton.setText(_translate("EricdocConfigDialog", "Level 2 Header Background", None))
        self.l2FgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the level 2 header foreground colour.", None))
        self.l2FgButton.setText(_translate("EricdocConfigDialog", "Level 2 Header Foreground", None))
        self.l1BgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the level 1 header background colour.", None))
        self.l1BgButton.setText(_translate("EricdocConfigDialog", "Level 1 Header Background", None))
        self.l1FgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the level 1 header foreground colour.", None))
        self.l1FgButton.setText(_translate("EricdocConfigDialog", "Level 1 Header Foreground", None))
        self.bodyBgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the body background colour.", None))
        self.bodyBgButton.setText(_translate("EricdocConfigDialog", "Body Background", None))
        self.bodyFgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the body foreground colour.", None))
        self.bodyFgButton.setText(_translate("EricdocConfigDialog", "Body Foreground", None))
        self.linkFgButton.setToolTip(_translate("EricdocConfigDialog", "Press to select the foreground colour of links.", None))
        self.linkFgButton.setText(_translate("EricdocConfigDialog", "Links", None))
        self.sample.setToolTip(_translate("EricdocConfigDialog", "This shows an example of the selected colours.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.styleTab), _translate("EricdocConfigDialog", "Style", None))
        self.qtHelpGroup.setTitle(_translate("EricdocConfigDialog", "Generate QtHelp Files", None))
        self.TextLabel6_2.setText(_translate("EricdocConfigDialog", "Output Directory:", None))
        self.qtHelpDirEdit.setToolTip(_translate("EricdocConfigDialog", "Enter an output directory", None))
        self.qtHelpDirButton.setToolTip(_translate("EricdocConfigDialog", "Press to open a directory selection dialog", None))
        self.qtHelpDirButton.setText(_translate("EricdocConfigDialog", "...", None))
        self.label_2.setText(_translate("EricdocConfigDialog", "Namespace:", None))
        self.qtHelpNamespaceEdit.setToolTip(_translate("EricdocConfigDialog", "Enter the namespace", None))
        self.label_3.setText(_translate("EricdocConfigDialog", "Virtual Folder:", None))
        self.qtHelpFolderEdit.setToolTip(_translate("EricdocConfigDialog", "Enter the name of the virtual folder (must not contain \'/\')", None))
        self.label_4.setText(_translate("EricdocConfigDialog", "Filter Name:", None))
        self.qtHelpFilterNameEdit.setToolTip(_translate("EricdocConfigDialog", "Enter the name of the custom filter", None))
        self.label_5.setText(_translate("EricdocConfigDialog", "Filter Attributes:", None))
        self.qtHelpFilterAttributesEdit.setToolTip(_translate("EricdocConfigDialog", "Enter the filter attributes separated by \':\'", None))
        self.label_6.setText(_translate("EricdocConfigDialog", "Title:", None))
        self.qtHelpTitleEdit.setToolTip(_translate("EricdocConfigDialog", "Enter a short title for the top entry", None))
        self.qtHelpGenerateCollectionCheckBox.setToolTip(_translate("EricdocConfigDialog", "Select to generate the QtHelp collection files", None))
        self.qtHelpGenerateCollectionCheckBox.setText(_translate("EricdocConfigDialog", "Generate QtHelp collection files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.qtHelpTab), _translate("EricdocConfigDialog", "QtHelp", None))

