# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Plugins\DocumentationPlugins\Ericapi\EricapiConfigDialog.ui'
#
# Created: Fri Apr 18 09:56:41 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EricapiConfigDialog(object):
    def setupUi(self, EricapiConfigDialog):
        EricapiConfigDialog.setObjectName(_fromUtf8("EricapiConfigDialog"))
        EricapiConfigDialog.resize(500, 600)
        EricapiConfigDialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(EricapiConfigDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.outputFileEdit = QtGui.QLineEdit(EricapiConfigDialog)
        self.outputFileEdit.setObjectName(_fromUtf8("outputFileEdit"))
        self.gridlayout.addWidget(self.outputFileEdit, 0, 1, 1, 1)
        self.outputFileButton = QtGui.QPushButton(EricapiConfigDialog)
        self.outputFileButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.outputFileButton.setObjectName(_fromUtf8("outputFileButton"))
        self.gridlayout.addWidget(self.outputFileButton, 0, 2, 1, 1)
        self.TextLabel6 = QtGui.QLabel(EricapiConfigDialog)
        self.TextLabel6.setObjectName(_fromUtf8("TextLabel6"))
        self.gridlayout.addWidget(self.TextLabel6, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridlayout)
        self.groupBox_2 = QtGui.QGroupBox(EricapiConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.languagesList = QtGui.QListWidget(self.groupBox_2)
        self.languagesList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.languagesList.setObjectName(_fromUtf8("languagesList"))
        self.verticalLayout.addWidget(self.languagesList)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.textLabel1_3 = QtGui.QLabel(EricapiConfigDialog)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.hboxlayout.addWidget(self.textLabel1_3)
        self.sourceExtEdit = QtGui.QLineEdit(EricapiConfigDialog)
        self.sourceExtEdit.setObjectName(_fromUtf8("sourceExtEdit"))
        self.hboxlayout.addWidget(self.sourceExtEdit)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        spacerItem = QtGui.QSpacerItem(31, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout1.addItem(spacerItem, 0, 2, 1, 1)
        self.oldStyleCheckBox = QtGui.QCheckBox(EricapiConfigDialog)
        self.oldStyleCheckBox.setObjectName(_fromUtf8("oldStyleCheckBox"))
        self.gridlayout1.addWidget(self.oldStyleCheckBox, 0, 1, 1, 1)
        self.recursionCheckBox = QtGui.QCheckBox(EricapiConfigDialog)
        self.recursionCheckBox.setObjectName(_fromUtf8("recursionCheckBox"))
        self.gridlayout1.addWidget(self.recursionCheckBox, 0, 0, 1, 1)
        self.includePrivateCheckBox = QtGui.QCheckBox(EricapiConfigDialog)
        self.includePrivateCheckBox.setObjectName(_fromUtf8("includePrivateCheckBox"))
        self.gridlayout1.addWidget(self.includePrivateCheckBox, 1, 0, 1, 3)
        self.verticalLayout_2.addLayout(self.gridlayout1)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.label = QtGui.QLabel(EricapiConfigDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout1.addWidget(self.label)
        self.baseEdit = QtGui.QLineEdit(EricapiConfigDialog)
        self.baseEdit.setObjectName(_fromUtf8("baseEdit"))
        self.hboxlayout1.addWidget(self.baseEdit)
        self.verticalLayout_2.addLayout(self.hboxlayout1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.label_2 = QtGui.QLabel(EricapiConfigDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.hboxlayout2.addWidget(self.label_2)
        self.excludeFilesEdit = QtGui.QLineEdit(EricapiConfigDialog)
        self.excludeFilesEdit.setObjectName(_fromUtf8("excludeFilesEdit"))
        self.hboxlayout2.addWidget(self.excludeFilesEdit)
        self.verticalLayout_2.addLayout(self.hboxlayout2)
        self.groupBox = QtGui.QGroupBox(EricapiConfigDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.ignoreDirEdit = QtGui.QLineEdit(self.groupBox)
        self.ignoreDirEdit.setObjectName(_fromUtf8("ignoreDirEdit"))
        self.gridlayout2.addWidget(self.ignoreDirEdit, 1, 2, 1, 1)
        self.addButton = QtGui.QPushButton(self.groupBox)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.gridlayout2.addWidget(self.addButton, 1, 1, 1, 1)
        self.deleteButton = QtGui.QPushButton(self.groupBox)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.gridlayout2.addWidget(self.deleteButton, 1, 0, 1, 1)
        self.ignoreDirButton = QtGui.QPushButton(self.groupBox)
        self.ignoreDirButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ignoreDirButton.setObjectName(_fromUtf8("ignoreDirButton"))
        self.gridlayout2.addWidget(self.ignoreDirButton, 1, 3, 1, 1)
        self.ignoreDirsList = QtGui.QListWidget(self.groupBox)
        self.ignoreDirsList.setObjectName(_fromUtf8("ignoreDirsList"))
        self.gridlayout2.addWidget(self.ignoreDirsList, 0, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBox = QtGui.QDialogButtonBox(EricapiConfigDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(EricapiConfigDialog)
        QtCore.QObject.connect(self.oldStyleCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.label.setDisabled)
        QtCore.QObject.connect(self.oldStyleCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.baseEdit.setDisabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), EricapiConfigDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), EricapiConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(EricapiConfigDialog)
        EricapiConfigDialog.setTabOrder(self.outputFileEdit, self.languagesList)
        EricapiConfigDialog.setTabOrder(self.languagesList, self.sourceExtEdit)
        EricapiConfigDialog.setTabOrder(self.sourceExtEdit, self.recursionCheckBox)
        EricapiConfigDialog.setTabOrder(self.recursionCheckBox, self.oldStyleCheckBox)
        EricapiConfigDialog.setTabOrder(self.oldStyleCheckBox, self.includePrivateCheckBox)
        EricapiConfigDialog.setTabOrder(self.includePrivateCheckBox, self.baseEdit)
        EricapiConfigDialog.setTabOrder(self.baseEdit, self.excludeFilesEdit)
        EricapiConfigDialog.setTabOrder(self.excludeFilesEdit, self.ignoreDirEdit)
        EricapiConfigDialog.setTabOrder(self.ignoreDirEdit, self.addButton)
        EricapiConfigDialog.setTabOrder(self.addButton, self.ignoreDirsList)
        EricapiConfigDialog.setTabOrder(self.ignoreDirsList, self.deleteButton)
        EricapiConfigDialog.setTabOrder(self.deleteButton, self.buttonBox)

    def retranslateUi(self, EricapiConfigDialog):
        EricapiConfigDialog.setWindowTitle(_translate("EricapiConfigDialog", "Ericapi Configuration", None))
        self.outputFileEdit.setToolTip(_translate("EricapiConfigDialog", "Enter an output filename", None))
        self.outputFileEdit.setWhatsThis(_translate("EricapiConfigDialog", "<b>Output Filename</b><p>Enter the filename of the output file. A \'%L\' placeholder is replaced by the language of the API file.</p>", None))
        self.outputFileButton.setToolTip(_translate("EricapiConfigDialog", "Press to open a file selection dialog", None))
        self.outputFileButton.setText(_translate("EricapiConfigDialog", "...", None))
        self.TextLabel6.setText(_translate("EricapiConfigDialog", "Output File:", None))
        self.groupBox_2.setTitle(_translate("EricapiConfigDialog", "Languages", None))
        self.languagesList.setToolTip(_translate("EricapiConfigDialog", "Select the languages of the  APIs to generate", None))
        self.textLabel1_3.setText(_translate("EricapiConfigDialog", "Additional source extensions:", None))
        self.sourceExtEdit.setToolTip(_translate("EricapiConfigDialog", "Enter additional source extensions separated by a comma", None))
        self.oldStyleCheckBox.setToolTip(_translate("EricapiConfigDialog", "Select to generate API files for QScintilla prior to 1.7", None))
        self.oldStyleCheckBox.setText(_translate("EricapiConfigDialog", "Generate old style API files", None))
        self.recursionCheckBox.setToolTip(_translate("EricapiConfigDialog", "Select to recurse into subdirectories", None))
        self.recursionCheckBox.setText(_translate("EricapiConfigDialog", "Recurse into subdirectories", None))
        self.includePrivateCheckBox.setToolTip(_translate("EricapiConfigDialog", "Select to include private classes, methods and functions in the API file", None))
        self.includePrivateCheckBox.setText(_translate("EricapiConfigDialog", "Include private classes, methods and functions", None))
        self.label.setText(_translate("EricapiConfigDialog", "Base package name:", None))
        self.baseEdit.setToolTip(_translate("EricapiConfigDialog", "Enter the name of the base package", None))
        self.label_2.setText(_translate("EricapiConfigDialog", "Exclude Files:", None))
        self.excludeFilesEdit.setToolTip(_translate("EricapiConfigDialog", "Enter filename patterns of files to be excluded separated by a comma", None))
        self.groupBox.setTitle(_translate("EricapiConfigDialog", "Exclude Directories", None))
        self.ignoreDirEdit.setToolTip(_translate("EricapiConfigDialog", "Enter a directory basename to be ignored", None))
        self.addButton.setToolTip(_translate("EricapiConfigDialog", "Press to add the entered directory to the list", None))
        self.addButton.setText(_translate("EricapiConfigDialog", "Add", None))
        self.deleteButton.setToolTip(_translate("EricapiConfigDialog", "Press to delete the selected directory from the list", None))
        self.deleteButton.setText(_translate("EricapiConfigDialog", "Delete", None))
        self.ignoreDirButton.setToolTip(_translate("EricapiConfigDialog", "Press to open a directory selection dialog", None))
        self.ignoreDirButton.setText(_translate("EricapiConfigDialog", "...", None))
        self.ignoreDirsList.setToolTip(_translate("EricapiConfigDialog", "List of directory basenames to be ignored", None))

