# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ViewProfileDialog.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ViewProfileDialog(object):
    def setupUi(self, ViewProfileDialog):
        ViewProfileDialog.setObjectName(_fromUtf8("ViewProfileDialog"))
        ViewProfileDialog.resize(608, 370)
        ViewProfileDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(ViewProfileDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.textLabel1 = QtGui.QLabel(ViewProfileDialog)
        self.textLabel1.setAlignment(QtCore.Qt.AlignVCenter)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.gridLayout.addWidget(self.textLabel1, 0, 0, 1, 2)
        self.editGroup = QtGui.QGroupBox(ViewProfileDialog)
        self.editGroup.setObjectName(_fromUtf8("editGroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.editGroup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.epmpbCheckBox = QtGui.QCheckBox(self.editGroup)
        self.epmpbCheckBox.setChecked(True)
        self.epmpbCheckBox.setObjectName(_fromUtf8("epmpbCheckBox"))
        self.verticalLayout.addWidget(self.epmpbCheckBox)
        self.eppbCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eppbCheckBox.setChecked(True)
        self.eppbCheckBox.setObjectName(_fromUtf8("eppbCheckBox"))
        self.verticalLayout.addWidget(self.eppbCheckBox)
        self.epfbCheckBox = QtGui.QCheckBox(self.editGroup)
        self.epfbCheckBox.setObjectName(_fromUtf8("epfbCheckBox"))
        self.verticalLayout.addWidget(self.epfbCheckBox)
        self.epdbCheckBox = QtGui.QCheckBox(self.editGroup)
        self.epdbCheckBox.setObjectName(_fromUtf8("epdbCheckBox"))
        self.verticalLayout.addWidget(self.epdbCheckBox)
        self.eppsCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eppsCheckBox.setChecked(True)
        self.eppsCheckBox.setObjectName(_fromUtf8("eppsCheckBox"))
        self.verticalLayout.addWidget(self.eppsCheckBox)
        self.eptwCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eptwCheckBox.setChecked(True)
        self.eptwCheckBox.setObjectName(_fromUtf8("eptwCheckBox"))
        self.verticalLayout.addWidget(self.eptwCheckBox)
        self.eplvCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eplvCheckBox.setChecked(True)
        self.eplvCheckBox.setObjectName(_fromUtf8("eplvCheckBox"))
        self.verticalLayout.addWidget(self.eplvCheckBox)
        self.eptvCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eptvCheckBox.setChecked(True)
        self.eptvCheckBox.setObjectName(_fromUtf8("eptvCheckBox"))
        self.verticalLayout.addWidget(self.eptvCheckBox)
        self.eptevCheckBox = QtGui.QCheckBox(self.editGroup)
        self.eptevCheckBox.setChecked(True)
        self.eptevCheckBox.setObjectName(_fromUtf8("eptevCheckBox"))
        self.verticalLayout.addWidget(self.eptevCheckBox)
        self.gridLayout.addWidget(self.editGroup, 1, 0, 1, 1)
        self.debugGroup = QtGui.QGroupBox(ViewProfileDialog)
        self.debugGroup.setObjectName(_fromUtf8("debugGroup"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.debugGroup)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.dpmpbCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dpmpbCheckBox.setObjectName(_fromUtf8("dpmpbCheckBox"))
        self.verticalLayout_2.addWidget(self.dpmpbCheckBox)
        self.dppbCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dppbCheckBox.setChecked(False)
        self.dppbCheckBox.setObjectName(_fromUtf8("dppbCheckBox"))
        self.verticalLayout_2.addWidget(self.dppbCheckBox)
        self.dpfbCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dpfbCheckBox.setObjectName(_fromUtf8("dpfbCheckBox"))
        self.verticalLayout_2.addWidget(self.dpfbCheckBox)
        self.dpdbCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dpdbCheckBox.setChecked(True)
        self.dpdbCheckBox.setObjectName(_fromUtf8("dpdbCheckBox"))
        self.verticalLayout_2.addWidget(self.dpdbCheckBox)
        self.dppsCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dppsCheckBox.setChecked(True)
        self.dppsCheckBox.setObjectName(_fromUtf8("dppsCheckBox"))
        self.verticalLayout_2.addWidget(self.dppsCheckBox)
        self.dptwCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dptwCheckBox.setChecked(True)
        self.dptwCheckBox.setObjectName(_fromUtf8("dptwCheckBox"))
        self.verticalLayout_2.addWidget(self.dptwCheckBox)
        self.dplvCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dplvCheckBox.setChecked(True)
        self.dplvCheckBox.setObjectName(_fromUtf8("dplvCheckBox"))
        self.verticalLayout_2.addWidget(self.dplvCheckBox)
        self.dptvCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dptvCheckBox.setChecked(True)
        self.dptvCheckBox.setObjectName(_fromUtf8("dptvCheckBox"))
        self.verticalLayout_2.addWidget(self.dptvCheckBox)
        self.dptevCheckBox = QtGui.QCheckBox(self.debugGroup)
        self.dptevCheckBox.setObjectName(_fromUtf8("dptevCheckBox"))
        self.verticalLayout_2.addWidget(self.dptevCheckBox)
        self.gridLayout.addWidget(self.debugGroup, 1, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ViewProfileDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)

        self.retranslateUi(ViewProfileDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ViewProfileDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ViewProfileDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ViewProfileDialog)
        ViewProfileDialog.setTabOrder(self.epmpbCheckBox, self.eppbCheckBox)
        ViewProfileDialog.setTabOrder(self.eppbCheckBox, self.epfbCheckBox)
        ViewProfileDialog.setTabOrder(self.epfbCheckBox, self.epdbCheckBox)
        ViewProfileDialog.setTabOrder(self.epdbCheckBox, self.eppsCheckBox)
        ViewProfileDialog.setTabOrder(self.eppsCheckBox, self.eptwCheckBox)
        ViewProfileDialog.setTabOrder(self.eptwCheckBox, self.eplvCheckBox)
        ViewProfileDialog.setTabOrder(self.eplvCheckBox, self.eptvCheckBox)
        ViewProfileDialog.setTabOrder(self.eptvCheckBox, self.eptevCheckBox)
        ViewProfileDialog.setTabOrder(self.eptevCheckBox, self.dpmpbCheckBox)
        ViewProfileDialog.setTabOrder(self.dpmpbCheckBox, self.dppbCheckBox)
        ViewProfileDialog.setTabOrder(self.dppbCheckBox, self.dpfbCheckBox)
        ViewProfileDialog.setTabOrder(self.dpfbCheckBox, self.dpdbCheckBox)
        ViewProfileDialog.setTabOrder(self.dpdbCheckBox, self.dppsCheckBox)
        ViewProfileDialog.setTabOrder(self.dppsCheckBox, self.dptwCheckBox)
        ViewProfileDialog.setTabOrder(self.dptwCheckBox, self.dplvCheckBox)
        ViewProfileDialog.setTabOrder(self.dplvCheckBox, self.dptvCheckBox)
        ViewProfileDialog.setTabOrder(self.dptvCheckBox, self.dptevCheckBox)
        ViewProfileDialog.setTabOrder(self.dptevCheckBox, self.buttonBox)

    def retranslateUi(self, ViewProfileDialog):
        ViewProfileDialog.setWindowTitle(_translate("ViewProfileDialog", "Configure View Profiles", None))
        self.textLabel1.setText(_translate("ViewProfileDialog", "Select the windows, that should be visible, when the different profiles are active.", None))
        self.editGroup.setTitle(_translate("ViewProfileDialog", "&Edit Profile", None))
        self.epmpbCheckBox.setText(_translate("ViewProfileDialog", "Multiproject-Viewer", None))
        self.eppbCheckBox.setText(_translate("ViewProfileDialog", "Project-Viewer", None))
        self.epfbCheckBox.setText(_translate("ViewProfileDialog", "File-Browser", None))
        self.epdbCheckBox.setText(_translate("ViewProfileDialog", "Debug-Viewer", None))
        self.eppsCheckBox.setText(_translate("ViewProfileDialog", "Shell", None))
        self.eptwCheckBox.setText(_translate("ViewProfileDialog", "Terminal", None))
        self.eplvCheckBox.setText(_translate("ViewProfileDialog", "Log-Viewer", None))
        self.eptvCheckBox.setText(_translate("ViewProfileDialog", "Task-Viewer", None))
        self.eptevCheckBox.setText(_translate("ViewProfileDialog", "Templates-Viewer", None))
        self.debugGroup.setTitle(_translate("ViewProfileDialog", "&Debug Profile", None))
        self.dpmpbCheckBox.setText(_translate("ViewProfileDialog", "Multiproject-Viewer", None))
        self.dppbCheckBox.setText(_translate("ViewProfileDialog", "Project-Viewer", None))
        self.dpfbCheckBox.setText(_translate("ViewProfileDialog", "File-Browser", None))
        self.dpdbCheckBox.setText(_translate("ViewProfileDialog", "Debug-Viewer", None))
        self.dppsCheckBox.setText(_translate("ViewProfileDialog", "Shell", None))
        self.dptwCheckBox.setText(_translate("ViewProfileDialog", "Terminal", None))
        self.dplvCheckBox.setText(_translate("ViewProfileDialog", "Log-Viewer", None))
        self.dptvCheckBox.setText(_translate("ViewProfileDialog", "Task-Viewer", None))
        self.dptevCheckBox.setText(_translate("ViewProfileDialog", "Templates-Viewer", None))

