# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\PyUnit\UnittestDialog.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UnittestDialog(object):
    def setupUi(self, UnittestDialog):
        UnittestDialog.setObjectName(_fromUtf8("UnittestDialog"))
        UnittestDialog.resize(619, 667)
        self._2 = QtGui.QVBoxLayout(UnittestDialog)
        self._2.setObjectName(_fromUtf8("_2"))
        self.groupBox = QtGui.QGroupBox(UnittestDialog)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self._4 = QtGui.QGridLayout(self.groupBox)
        self._4.setObjectName(_fromUtf8("_4"))
        self.testComboBox = QtGui.QComboBox(self.groupBox)
        self.testComboBox.setEditable(True)
        self.testComboBox.setObjectName(_fromUtf8("testComboBox"))
        self._4.addWidget(self.testComboBox, 1, 1, 1, 2)
        self.testsuiteComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testsuiteComboBox.sizePolicy().hasHeightForWidth())
        self.testsuiteComboBox.setSizePolicy(sizePolicy)
        self.testsuiteComboBox.setEditable(True)
        self.testsuiteComboBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.testsuiteComboBox.setAutoCompletion(True)
        self.testsuiteComboBox.setDuplicatesEnabled(False)
        self.testsuiteComboBox.setObjectName(_fromUtf8("testsuiteComboBox"))
        self._4.addWidget(self.testsuiteComboBox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self._4.addWidget(self.label, 1, 0, 1, 1)
        self.fileDialogButton = QtGui.QPushButton(self.groupBox)
        self.fileDialogButton.setObjectName(_fromUtf8("fileDialogButton"))
        self._4.addWidget(self.fileDialogButton, 0, 2, 1, 1)
        self.testsuiteLabel = QtGui.QLabel(self.groupBox)
        self.testsuiteLabel.setObjectName(_fromUtf8("testsuiteLabel"))
        self._4.addWidget(self.testsuiteLabel, 0, 0, 1, 1)
        self._2.addWidget(self.groupBox)
        self.optionsGroup = QtGui.QGroupBox(UnittestDialog)
        self.optionsGroup.setTitle(_fromUtf8(""))
        self.optionsGroup.setObjectName(_fromUtf8("optionsGroup"))
        self._5 = QtGui.QHBoxLayout(self.optionsGroup)
        self._5.setObjectName(_fromUtf8("_5"))
        self.localCheckBox = QtGui.QCheckBox(self.optionsGroup)
        self.localCheckBox.setObjectName(_fromUtf8("localCheckBox"))
        self._5.addWidget(self.localCheckBox)
        self.coverageCheckBox = QtGui.QCheckBox(self.optionsGroup)
        self.coverageCheckBox.setObjectName(_fromUtf8("coverageCheckBox"))
        self._5.addWidget(self.coverageCheckBox)
        self.coverageEraseCheckBox = QtGui.QCheckBox(self.optionsGroup)
        self.coverageEraseCheckBox.setEnabled(False)
        self.coverageEraseCheckBox.setObjectName(_fromUtf8("coverageEraseCheckBox"))
        self._5.addWidget(self.coverageEraseCheckBox)
        self._2.addWidget(self.optionsGroup)
        self.progressGroupBox = QtGui.QGroupBox(UnittestDialog)
        self.progressGroupBox.setTitle(_fromUtf8(""))
        self.progressGroupBox.setObjectName(_fromUtf8("progressGroupBox"))
        self._6 = QtGui.QVBoxLayout(self.progressGroupBox)
        self._6.setObjectName(_fromUtf8("_6"))
        self._8 = QtGui.QHBoxLayout()
        self._8.setObjectName(_fromUtf8("_8"))
        self.progressTextLabel = QtGui.QLabel(self.progressGroupBox)
        self.progressTextLabel.setObjectName(_fromUtf8("progressTextLabel"))
        self._8.addWidget(self.progressTextLabel)
        spacerItem = QtGui.QSpacerItem(371, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._8.addItem(spacerItem)
        self.progressLed = E4Led(self.progressGroupBox)
        self.progressLed.setObjectName(_fromUtf8("progressLed"))
        self._8.addWidget(self.progressLed)
        self._6.addLayout(self._8)
        self.progressProgressBar = QtGui.QProgressBar(self.progressGroupBox)
        self.progressProgressBar.setProperty("value", 0)
        self.progressProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressProgressBar.setObjectName(_fromUtf8("progressProgressBar"))
        self._6.addWidget(self.progressProgressBar)
        self._7 = QtGui.QHBoxLayout()
        self._7.setObjectName(_fromUtf8("_7"))
        self.progressCounterRunLabel = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterRunLabel.setObjectName(_fromUtf8("progressCounterRunLabel"))
        self._7.addWidget(self.progressCounterRunLabel)
        self.progressCounterRunCount = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterRunCount.setObjectName(_fromUtf8("progressCounterRunCount"))
        self._7.addWidget(self.progressCounterRunCount)
        self.progressCounterFailureLabel = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterFailureLabel.setObjectName(_fromUtf8("progressCounterFailureLabel"))
        self._7.addWidget(self.progressCounterFailureLabel)
        self.progressCounterFailureCount = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterFailureCount.setObjectName(_fromUtf8("progressCounterFailureCount"))
        self._7.addWidget(self.progressCounterFailureCount)
        self.progressCounterErrorLabel = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterErrorLabel.setObjectName(_fromUtf8("progressCounterErrorLabel"))
        self._7.addWidget(self.progressCounterErrorLabel)
        self.progressCounterErrorCount = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterErrorCount.setObjectName(_fromUtf8("progressCounterErrorCount"))
        self._7.addWidget(self.progressCounterErrorCount)
        self.progressCounterRemLabel = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterRemLabel.setObjectName(_fromUtf8("progressCounterRemLabel"))
        self._7.addWidget(self.progressCounterRemLabel)
        self.progressCounterRemCount = QtGui.QLabel(self.progressGroupBox)
        self.progressCounterRemCount.setObjectName(_fromUtf8("progressCounterRemCount"))
        self._7.addWidget(self.progressCounterRemCount)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._7.addItem(spacerItem1)
        self._6.addLayout(self._7)
        self._2.addWidget(self.progressGroupBox)
        self.textLabel1 = QtGui.QLabel(UnittestDialog)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self._2.addWidget(self.textLabel1)
        self.testsListWidget = QtGui.QListWidget(UnittestDialog)
        self.testsListWidget.setObjectName(_fromUtf8("testsListWidget"))
        self._2.addWidget(self.testsListWidget)
        self.listboxLabel = QtGui.QLabel(UnittestDialog)
        self.listboxLabel.setObjectName(_fromUtf8("listboxLabel"))
        self._2.addWidget(self.listboxLabel)
        self.errorsListWidget = QtGui.QListWidget(UnittestDialog)
        self.errorsListWidget.setObjectName(_fromUtf8("errorsListWidget"))
        self._2.addWidget(self.errorsListWidget)
        self.buttonBox = QtGui.QDialogButtonBox(UnittestDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self._2.addWidget(self.buttonBox)
        self._3 = QtGui.QHBoxLayout()
        self._3.setObjectName(_fromUtf8("_3"))
        self.sbLabel = QtGui.QLabel(UnittestDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbLabel.sizePolicy().hasHeightForWidth())
        self.sbLabel.setSizePolicy(sizePolicy)
        self.sbLabel.setObjectName(_fromUtf8("sbLabel"))
        self._3.addWidget(self.sbLabel)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._3.addItem(spacerItem2)
        self._2.addLayout(self._3)
        self.label.setBuddy(self.testComboBox)
        self.testsuiteLabel.setBuddy(self.testsuiteComboBox)

        self.retranslateUi(UnittestDialog)
        QtCore.QObject.connect(self.coverageCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.coverageEraseCheckBox.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), UnittestDialog.close)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), UnittestDialog.close)
        QtCore.QMetaObject.connectSlotsByName(UnittestDialog)
        UnittestDialog.setTabOrder(self.testsuiteComboBox, self.fileDialogButton)
        UnittestDialog.setTabOrder(self.fileDialogButton, self.testComboBox)
        UnittestDialog.setTabOrder(self.testComboBox, self.localCheckBox)
        UnittestDialog.setTabOrder(self.localCheckBox, self.coverageCheckBox)
        UnittestDialog.setTabOrder(self.coverageCheckBox, self.coverageEraseCheckBox)
        UnittestDialog.setTabOrder(self.coverageEraseCheckBox, self.testsListWidget)
        UnittestDialog.setTabOrder(self.testsListWidget, self.errorsListWidget)

    def retranslateUi(self, UnittestDialog):
        UnittestDialog.setWindowTitle(_translate("UnittestDialog", "Unittest", None))
        self.testComboBox.setToolTip(_translate("UnittestDialog", "Enter the test name. Leave empty to use the default name \"suite\".", None))
        self.testComboBox.setWhatsThis(_translate("UnittestDialog", "<b>Testname</b><p>Enter the name of the test to be performed. This name must follow the rules given by Python\'s unittest module. If this field is empty, the default name of \"suite\" will be used.</p>", None))
        self.testsuiteComboBox.setToolTip(_translate("UnittestDialog", "Enter name of file defining the testsuite", None))
        self.testsuiteComboBox.setWhatsThis(_translate("UnittestDialog", "<b>Testsuite</b>\n"
"<p>Enter the name of the file defining the testsuite.\n"
"It should have a method with a name given below. If no name is given, the suite() method will be tried. If no such method can be\n"
"found, the module will be inspected for proper test\n"
"cases.</p>", None))
        self.label.setText(_translate("UnittestDialog", "Enter &test name:", None))
        self.fileDialogButton.setToolTip(_translate("UnittestDialog", "Open a file selection dialog", None))
        self.fileDialogButton.setText(_translate("UnittestDialog", "...", None))
        self.testsuiteLabel.setText(_translate("UnittestDialog", "Enter test &filename:", None))
        self.localCheckBox.setToolTip(_translate("UnittestDialog", "Select whether you want to run the test locally", None))
        self.localCheckBox.setText(_translate("UnittestDialog", "Run &local", None))
        self.coverageCheckBox.setToolTip(_translate("UnittestDialog", "Select whether coverage data should be collected", None))
        self.coverageCheckBox.setText(_translate("UnittestDialog", "C&ollect coverage data", None))
        self.coverageEraseCheckBox.setToolTip(_translate("UnittestDialog", "Select whether old coverage data should be erased", None))
        self.coverageEraseCheckBox.setText(_translate("UnittestDialog", "&Erase coverage data", None))
        self.progressTextLabel.setText(_translate("UnittestDialog", "Progress:", None))
        self.progressCounterRunLabel.setText(_translate("UnittestDialog", "Run:", None))
        self.progressCounterRunCount.setToolTip(_translate("UnittestDialog", "Number of tests run", None))
        self.progressCounterRunCount.setText(_translate("UnittestDialog", "0", None))
        self.progressCounterFailureLabel.setText(_translate("UnittestDialog", "Failures:", None))
        self.progressCounterFailureCount.setToolTip(_translate("UnittestDialog", "Number of test failures", None))
        self.progressCounterFailureCount.setText(_translate("UnittestDialog", "0", None))
        self.progressCounterErrorLabel.setText(_translate("UnittestDialog", "Errors:", None))
        self.progressCounterErrorCount.setToolTip(_translate("UnittestDialog", "Number of test errors", None))
        self.progressCounterErrorCount.setText(_translate("UnittestDialog", "0", None))
        self.progressCounterRemLabel.setText(_translate("UnittestDialog", "Remaining:", None))
        self.progressCounterRemCount.setToolTip(_translate("UnittestDialog", "Number of tests to be run", None))
        self.progressCounterRemCount.setText(_translate("UnittestDialog", "0", None))
        self.textLabel1.setText(_translate("UnittestDialog", "Tests performed:", None))
        self.listboxLabel.setText(_translate("UnittestDialog", "Failures and errors:", None))
        self.errorsListWidget.setToolTip(_translate("UnittestDialog", "Failures and Errors list", None))
        self.errorsListWidget.setWhatsThis(_translate("UnittestDialog", "<b>Failures and Errors list</b>\n"
"<p>This list shows all failed and errored tests.\n"
"Double clicking on an entry will show the respective traceback.</p>", None))
        self.sbLabel.setText(_translate("UnittestDialog", "Idle", None))

from E4Gui.E4Led import E4Led
