# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\UI\CompareDialog.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CompareDialog(object):
    def setupUi(self, CompareDialog):
        CompareDialog.setObjectName(_fromUtf8("CompareDialog"))
        CompareDialog.resize(950, 600)
        self.verticalLayout = QtGui.QVBoxLayout(CompareDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.filesGroup = QtGui.QGroupBox(CompareDialog)
        self.filesGroup.setTitle(_fromUtf8(""))
        self.filesGroup.setFlat(True)
        self.filesGroup.setObjectName(_fromUtf8("filesGroup"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.filesGroup)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.textLabel1 = QtGui.QLabel(self.filesGroup)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.horizontalLayout_3.addWidget(self.textLabel1)
        self.file1Edit = QtGui.QLineEdit(self.filesGroup)
        self.file1Edit.setObjectName(_fromUtf8("file1Edit"))
        self.horizontalLayout_3.addWidget(self.file1Edit)
        self.file1Button = QtGui.QPushButton(self.filesGroup)
        self.file1Button.setObjectName(_fromUtf8("file1Button"))
        self.horizontalLayout_3.addWidget(self.file1Button)
        self.textLabel2 = QtGui.QLabel(self.filesGroup)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.horizontalLayout_3.addWidget(self.textLabel2)
        self.file2Edit = QtGui.QLineEdit(self.filesGroup)
        self.file2Edit.setObjectName(_fromUtf8("file2Edit"))
        self.horizontalLayout_3.addWidget(self.file2Edit)
        self.file2Button = QtGui.QPushButton(self.filesGroup)
        self.file2Button.setObjectName(_fromUtf8("file2Button"))
        self.horizontalLayout_3.addWidget(self.file2Button)
        self.verticalLayout.addWidget(self.filesGroup)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.file1Label = QtGui.QLabel(CompareDialog)
        self.file1Label.setText(_fromUtf8(""))
        self.file1Label.setWordWrap(True)
        self.file1Label.setObjectName(_fromUtf8("file1Label"))
        self.gridLayout.addWidget(self.file1Label, 0, 0, 1, 1)
        self.file2Label = QtGui.QLabel(CompareDialog)
        self.file2Label.setText(_fromUtf8(""))
        self.file2Label.setWordWrap(True)
        self.file2Label.setObjectName(_fromUtf8("file2Label"))
        self.gridLayout.addWidget(self.file2Label, 0, 2, 1, 1)
        self.contents_1 = QtGui.QTextEdit(CompareDialog)
        self.contents_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contents_1.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.contents_1.setReadOnly(True)
        self.contents_1.setTabStopWidth(8)
        self.contents_1.setAcceptRichText(False)
        self.contents_1.setObjectName(_fromUtf8("contents_1"))
        self.gridLayout.addWidget(self.contents_1, 1, 0, 1, 1)
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        spacerItem = QtGui.QSpacerItem(20, 101, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem)
        self.firstButton = QtGui.QToolButton(CompareDialog)
        self.firstButton.setEnabled(False)
        self.firstButton.setObjectName(_fromUtf8("firstButton"))
        self.vboxlayout.addWidget(self.firstButton)
        self.upButton = QtGui.QToolButton(CompareDialog)
        self.upButton.setEnabled(False)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.vboxlayout.addWidget(self.upButton)
        self.downButton = QtGui.QToolButton(CompareDialog)
        self.downButton.setEnabled(False)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.vboxlayout.addWidget(self.downButton)
        self.lastButton = QtGui.QToolButton(CompareDialog)
        self.lastButton.setEnabled(False)
        self.lastButton.setObjectName(_fromUtf8("lastButton"))
        self.vboxlayout.addWidget(self.lastButton)
        spacerItem1 = QtGui.QSpacerItem(20, 101, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.vboxlayout, 1, 1, 1, 1)
        self.contents_2 = QtGui.QTextEdit(CompareDialog)
        self.contents_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.contents_2.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.contents_2.setReadOnly(True)
        self.contents_2.setTabStopWidth(8)
        self.contents_2.setAcceptRichText(False)
        self.contents_2.setObjectName(_fromUtf8("contents_2"))
        self.gridLayout.addWidget(self.contents_2, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.synchronizeCheckBox = QtGui.QCheckBox(CompareDialog)
        self.synchronizeCheckBox.setChecked(True)
        self.synchronizeCheckBox.setObjectName(_fromUtf8("synchronizeCheckBox"))
        self.verticalLayout.addWidget(self.synchronizeCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.totalLabel = QtGui.QLabel(CompareDialog)
        self.totalLabel.setFrameShape(QtGui.QFrame.Panel)
        self.totalLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.totalLabel.setObjectName(_fromUtf8("totalLabel"))
        self.horizontalLayout.addWidget(self.totalLabel)
        self.changedLabel = QtGui.QLabel(CompareDialog)
        self.changedLabel.setFrameShape(QtGui.QFrame.Panel)
        self.changedLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.changedLabel.setObjectName(_fromUtf8("changedLabel"))
        self.horizontalLayout.addWidget(self.changedLabel)
        self.addedLabel = QtGui.QLabel(CompareDialog)
        self.addedLabel.setFrameShape(QtGui.QFrame.Panel)
        self.addedLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.addedLabel.setObjectName(_fromUtf8("addedLabel"))
        self.horizontalLayout.addWidget(self.addedLabel)
        self.deletedLabel = QtGui.QLabel(CompareDialog)
        self.deletedLabel.setFrameShape(QtGui.QFrame.Panel)
        self.deletedLabel.setFrameShadow(QtGui.QFrame.Sunken)
        self.deletedLabel.setObjectName(_fromUtf8("deletedLabel"))
        self.horizontalLayout.addWidget(self.deletedLabel)
        self.buttonBox = QtGui.QDialogButtonBox(CompareDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textLabel1.setBuddy(self.file1Edit)
        self.textLabel2.setBuddy(self.file1Edit)

        self.retranslateUi(CompareDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CompareDialog.close)
        QtCore.QMetaObject.connectSlotsByName(CompareDialog)
        CompareDialog.setTabOrder(self.file1Edit, self.file1Button)
        CompareDialog.setTabOrder(self.file1Button, self.file2Edit)
        CompareDialog.setTabOrder(self.file2Edit, self.file2Button)
        CompareDialog.setTabOrder(self.file2Button, self.synchronizeCheckBox)
        CompareDialog.setTabOrder(self.synchronizeCheckBox, self.firstButton)
        CompareDialog.setTabOrder(self.firstButton, self.upButton)
        CompareDialog.setTabOrder(self.upButton, self.downButton)
        CompareDialog.setTabOrder(self.downButton, self.lastButton)

    def retranslateUi(self, CompareDialog):
        CompareDialog.setWindowTitle(_translate("CompareDialog", "File Comparison", None))
        self.textLabel1.setText(_translate("CompareDialog", "File &1:", None))
        self.file1Edit.setToolTip(_translate("CompareDialog", "Enter the name of the first file", None))
        self.file1Button.setToolTip(_translate("CompareDialog", "Press to select the file via a file selection dialog", None))
        self.file1Button.setText(_translate("CompareDialog", "...", None))
        self.textLabel2.setText(_translate("CompareDialog", "File &2:", None))
        self.file2Edit.setToolTip(_translate("CompareDialog", "Enter the name of the second file", None))
        self.file2Button.setToolTip(_translate("CompareDialog", "Press to select the file via a file selection dialog", None))
        self.file2Button.setText(_translate("CompareDialog", "...", None))
        self.firstButton.setToolTip(_translate("CompareDialog", "Press to move to the first difference", None))
        self.upButton.setToolTip(_translate("CompareDialog", "Press to move to the previous difference", None))
        self.downButton.setToolTip(_translate("CompareDialog", "Press to move to the next difference", None))
        self.lastButton.setToolTip(_translate("CompareDialog", "Press to move to the last difference", None))
        self.synchronizeCheckBox.setToolTip(_translate("CompareDialog", "Select, if the scrollbars should be synchronized", None))
        self.synchronizeCheckBox.setText(_translate("CompareDialog", "&Synchronize scrollbars", None))
        self.synchronizeCheckBox.setShortcut(_translate("CompareDialog", "Alt+S", None))

