# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Plugins\WizardPlugins\MessageBoxWizard\MessageBoxWizardDialog.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MessageBoxWizardDialog(object):
    def setupUi(self, MessageBoxWizardDialog):
        MessageBoxWizardDialog.setObjectName(_fromUtf8("MessageBoxWizardDialog"))
        MessageBoxWizardDialog.resize(535, 658)
        MessageBoxWizardDialog.setSizeGripEnabled(True)
        self.vboxlayout = QtGui.QVBoxLayout(MessageBoxWizardDialog)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.qtGroup = QtGui.QGroupBox(MessageBoxWizardDialog)
        self.qtGroup.setObjectName(_fromUtf8("qtGroup"))
        self.hboxlayout = QtGui.QHBoxLayout(self.qtGroup)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.rQt4 = QtGui.QRadioButton(self.qtGroup)
        self.rQt4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQt4.setObjectName(_fromUtf8("rQt4"))
        self.hboxlayout.addWidget(self.rQt4)
        self.rQt42 = QtGui.QRadioButton(self.qtGroup)
        self.rQt42.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQt42.setChecked(True)
        self.rQt42.setObjectName(_fromUtf8("rQt42"))
        self.hboxlayout.addWidget(self.rQt42)
        spacerItem = QtGui.QSpacerItem(161, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.vboxlayout.addWidget(self.qtGroup)
        self.groupBox = QtGui.QGroupBox(MessageBoxWizardDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        self.rInformation = QtGui.QRadioButton(self.groupBox)
        self.rInformation.setChecked(True)
        self.rInformation.setObjectName(_fromUtf8("rInformation"))
        self.hboxlayout1.addWidget(self.rInformation)
        self.rQuestion = QtGui.QRadioButton(self.groupBox)
        self.rQuestion.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQuestion.setObjectName(_fromUtf8("rQuestion"))
        self.hboxlayout1.addWidget(self.rQuestion)
        self.rWarning = QtGui.QRadioButton(self.groupBox)
        self.rWarning.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rWarning.setObjectName(_fromUtf8("rWarning"))
        self.hboxlayout1.addWidget(self.rWarning)
        self.rCritical = QtGui.QRadioButton(self.groupBox)
        self.rCritical.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rCritical.setObjectName(_fromUtf8("rCritical"))
        self.hboxlayout1.addWidget(self.rCritical)
        self.rAbout = QtGui.QRadioButton(self.groupBox)
        self.rAbout.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rAbout.setObjectName(_fromUtf8("rAbout"))
        self.hboxlayout1.addWidget(self.rAbout)
        self.rAboutQt = QtGui.QRadioButton(self.groupBox)
        self.rAboutQt.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rAboutQt.setObjectName(_fromUtf8("rAboutQt"))
        self.hboxlayout1.addWidget(self.rAboutQt)
        self.vboxlayout.addWidget(self.groupBox)
        self.textLabel1 = QtGui.QLabel(MessageBoxWizardDialog)
        self.textLabel1.setObjectName(_fromUtf8("textLabel1"))
        self.vboxlayout.addWidget(self.textLabel1)
        self.eCaption = QtGui.QLineEdit(MessageBoxWizardDialog)
        self.eCaption.setObjectName(_fromUtf8("eCaption"))
        self.vboxlayout.addWidget(self.eCaption)
        self.textLabel2 = QtGui.QLabel(MessageBoxWizardDialog)
        self.textLabel2.setObjectName(_fromUtf8("textLabel2"))
        self.vboxlayout.addWidget(self.textLabel2)
        self.eMessage = QtGui.QTextEdit(MessageBoxWizardDialog)
        self.eMessage.setTabChangesFocus(True)
        self.eMessage.setObjectName(_fromUtf8("eMessage"))
        self.vboxlayout.addWidget(self.eMessage)
        self.buttons = QtGui.QGroupBox(MessageBoxWizardDialog)
        self.buttons.setEnabled(False)
        self.buttons.setObjectName(_fromUtf8("buttons"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.buttons)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.cButton1 = QtGui.QComboBox(self.buttons)
        self.cButton1.setEnabled(False)
        self.cButton1.setEditable(True)
        self.cButton1.setObjectName(_fromUtf8("cButton1"))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.setItemText(0, _fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.cButton1.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cButton1, 1, 1, 1, 1)
        self.cButton0 = QtGui.QComboBox(self.buttons)
        self.cButton0.setEditable(True)
        self.cButton0.setObjectName(_fromUtf8("cButton0"))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.setItemText(0, _fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.cButton0.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cButton0, 1, 0, 1, 1)
        self.textLabel3_2_2 = QtGui.QLabel(self.buttons)
        self.textLabel3_2_2.setObjectName(_fromUtf8("textLabel3_2_2"))
        self.gridlayout.addWidget(self.textLabel3_2_2, 0, 2, 1, 1)
        self.cButton2 = QtGui.QComboBox(self.buttons)
        self.cButton2.setEnabled(False)
        self.cButton2.setEditable(True)
        self.cButton2.setObjectName(_fromUtf8("cButton2"))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.setItemText(0, _fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.cButton2.addItem(_fromUtf8(""))
        self.gridlayout.addWidget(self.cButton2, 1, 2, 1, 1)
        self.textLabel3_2 = QtGui.QLabel(self.buttons)
        self.textLabel3_2.setObjectName(_fromUtf8("textLabel3_2"))
        self.gridlayout.addWidget(self.textLabel3_2, 0, 1, 1, 1)
        self.textLabel3 = QtGui.QLabel(self.buttons)
        self.textLabel3.setObjectName(_fromUtf8("textLabel3"))
        self.gridlayout.addWidget(self.textLabel3, 0, 0, 1, 1)
        self.vboxlayout1.addLayout(self.gridlayout)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName(_fromUtf8("hboxlayout2"))
        self.TextLabel1 = QtGui.QLabel(self.buttons)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.hboxlayout2.addWidget(self.TextLabel1)
        self.sDefault = QtGui.QSpinBox(self.buttons)
        self.sDefault.setMaximum(0)
        self.sDefault.setObjectName(_fromUtf8("sDefault"))
        self.hboxlayout2.addWidget(self.sDefault)
        self.TextLabel2 = QtGui.QLabel(self.buttons)
        self.TextLabel2.setObjectName(_fromUtf8("TextLabel2"))
        self.hboxlayout2.addWidget(self.TextLabel2)
        self.sEscape = QtGui.QSpinBox(self.buttons)
        self.sEscape.setMinimum(-1)
        self.sEscape.setMaximum(0)
        self.sEscape.setProperty("value", -1)
        self.sEscape.setObjectName(_fromUtf8("sEscape"))
        self.hboxlayout2.addWidget(self.sEscape)
        self.vboxlayout1.addLayout(self.hboxlayout2)
        self.vboxlayout.addWidget(self.buttons)
        self.standardButtons = QtGui.QGroupBox(MessageBoxWizardDialog)
        self.standardButtons.setObjectName(_fromUtf8("standardButtons"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.standardButtons)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.applyCheck = QtGui.QCheckBox(self.standardButtons)
        self.applyCheck.setObjectName(_fromUtf8("applyCheck"))
        self.gridlayout1.addWidget(self.applyCheck, 0, 1, 1, 1)
        self.abortCheck = QtGui.QCheckBox(self.standardButtons)
        self.abortCheck.setObjectName(_fromUtf8("abortCheck"))
        self.gridlayout1.addWidget(self.abortCheck, 0, 0, 1, 1)
        self.cancelCheck = QtGui.QCheckBox(self.standardButtons)
        self.cancelCheck.setObjectName(_fromUtf8("cancelCheck"))
        self.gridlayout1.addWidget(self.cancelCheck, 0, 2, 1, 1)
        self.ignoreCheck = QtGui.QCheckBox(self.standardButtons)
        self.ignoreCheck.setObjectName(_fromUtf8("ignoreCheck"))
        self.gridlayout1.addWidget(self.ignoreCheck, 1, 1, 1, 1)
        self.saveallCheck = QtGui.QCheckBox(self.standardButtons)
        self.saveallCheck.setObjectName(_fromUtf8("saveallCheck"))
        self.gridlayout1.addWidget(self.saveallCheck, 3, 0, 1, 1)
        self.saveCheck = QtGui.QCheckBox(self.standardButtons)
        self.saveCheck.setObjectName(_fromUtf8("saveCheck"))
        self.gridlayout1.addWidget(self.saveCheck, 2, 4, 1, 1)
        self.discardCheck = QtGui.QCheckBox(self.standardButtons)
        self.discardCheck.setObjectName(_fromUtf8("discardCheck"))
        self.gridlayout1.addWidget(self.discardCheck, 0, 4, 1, 1)
        self.yestoallCheck = QtGui.QCheckBox(self.standardButtons)
        self.yestoallCheck.setObjectName(_fromUtf8("yestoallCheck"))
        self.gridlayout1.addWidget(self.yestoallCheck, 3, 2, 1, 1)
        self.openCheck = QtGui.QCheckBox(self.standardButtons)
        self.openCheck.setObjectName(_fromUtf8("openCheck"))
        self.gridlayout1.addWidget(self.openCheck, 2, 0, 1, 1)
        self.resetCheck = QtGui.QCheckBox(self.standardButtons)
        self.resetCheck.setObjectName(_fromUtf8("resetCheck"))
        self.gridlayout1.addWidget(self.resetCheck, 2, 1, 1, 1)
        self.okCheck = QtGui.QCheckBox(self.standardButtons)
        self.okCheck.setObjectName(_fromUtf8("okCheck"))
        self.gridlayout1.addWidget(self.okCheck, 1, 4, 1, 1)
        self.noCheck = QtGui.QCheckBox(self.standardButtons)
        self.noCheck.setObjectName(_fromUtf8("noCheck"))
        self.gridlayout1.addWidget(self.noCheck, 1, 2, 1, 1)
        self.helpCheck = QtGui.QCheckBox(self.standardButtons)
        self.helpCheck.setObjectName(_fromUtf8("helpCheck"))
        self.gridlayout1.addWidget(self.helpCheck, 1, 0, 1, 1)
        self.notoallCheck = QtGui.QCheckBox(self.standardButtons)
        self.notoallCheck.setObjectName(_fromUtf8("notoallCheck"))
        self.gridlayout1.addWidget(self.notoallCheck, 1, 3, 1, 1)
        self.retryCheck = QtGui.QCheckBox(self.standardButtons)
        self.retryCheck.setObjectName(_fromUtf8("retryCheck"))
        self.gridlayout1.addWidget(self.retryCheck, 2, 3, 1, 1)
        self.restoreCheck = QtGui.QCheckBox(self.standardButtons)
        self.restoreCheck.setObjectName(_fromUtf8("restoreCheck"))
        self.gridlayout1.addWidget(self.restoreCheck, 2, 2, 1, 1)
        self.yesCheck = QtGui.QCheckBox(self.standardButtons)
        self.yesCheck.setObjectName(_fromUtf8("yesCheck"))
        self.gridlayout1.addWidget(self.yesCheck, 3, 1, 1, 1)
        self.closeCheck = QtGui.QCheckBox(self.standardButtons)
        self.closeCheck.setObjectName(_fromUtf8("closeCheck"))
        self.gridlayout1.addWidget(self.closeCheck, 0, 3, 1, 1)
        self.vboxlayout2.addLayout(self.gridlayout1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setObjectName(_fromUtf8("hboxlayout3"))
        self.TextLabel1_2 = QtGui.QLabel(self.standardButtons)
        self.TextLabel1_2.setObjectName(_fromUtf8("TextLabel1_2"))
        self.hboxlayout3.addWidget(self.TextLabel1_2)
        self.defaultCombo = QtGui.QComboBox(self.standardButtons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultCombo.sizePolicy().hasHeightForWidth())
        self.defaultCombo.setSizePolicy(sizePolicy)
        self.defaultCombo.setObjectName(_fromUtf8("defaultCombo"))
        self.hboxlayout3.addWidget(self.defaultCombo)
        self.vboxlayout2.addLayout(self.hboxlayout3)
        self.vboxlayout.addWidget(self.standardButtons)
        self.buttonBox = QtGui.QDialogButtonBox(MessageBoxWizardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(MessageBoxWizardDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MessageBoxWizardDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MessageBoxWizardDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(MessageBoxWizardDialog)
        MessageBoxWizardDialog.setTabOrder(self.rQt4, self.rQt42)
        MessageBoxWizardDialog.setTabOrder(self.rQt42, self.rInformation)
        MessageBoxWizardDialog.setTabOrder(self.rInformation, self.rQuestion)
        MessageBoxWizardDialog.setTabOrder(self.rQuestion, self.rWarning)
        MessageBoxWizardDialog.setTabOrder(self.rWarning, self.rCritical)
        MessageBoxWizardDialog.setTabOrder(self.rCritical, self.rAbout)
        MessageBoxWizardDialog.setTabOrder(self.rAbout, self.rAboutQt)
        MessageBoxWizardDialog.setTabOrder(self.rAboutQt, self.eCaption)
        MessageBoxWizardDialog.setTabOrder(self.eCaption, self.eMessage)
        MessageBoxWizardDialog.setTabOrder(self.eMessage, self.cButton0)
        MessageBoxWizardDialog.setTabOrder(self.cButton0, self.cButton1)
        MessageBoxWizardDialog.setTabOrder(self.cButton1, self.cButton2)
        MessageBoxWizardDialog.setTabOrder(self.cButton2, self.sDefault)
        MessageBoxWizardDialog.setTabOrder(self.sDefault, self.sEscape)
        MessageBoxWizardDialog.setTabOrder(self.sEscape, self.abortCheck)
        MessageBoxWizardDialog.setTabOrder(self.abortCheck, self.applyCheck)
        MessageBoxWizardDialog.setTabOrder(self.applyCheck, self.cancelCheck)
        MessageBoxWizardDialog.setTabOrder(self.cancelCheck, self.closeCheck)
        MessageBoxWizardDialog.setTabOrder(self.closeCheck, self.discardCheck)
        MessageBoxWizardDialog.setTabOrder(self.discardCheck, self.helpCheck)
        MessageBoxWizardDialog.setTabOrder(self.helpCheck, self.ignoreCheck)
        MessageBoxWizardDialog.setTabOrder(self.ignoreCheck, self.noCheck)
        MessageBoxWizardDialog.setTabOrder(self.noCheck, self.notoallCheck)
        MessageBoxWizardDialog.setTabOrder(self.notoallCheck, self.okCheck)
        MessageBoxWizardDialog.setTabOrder(self.okCheck, self.openCheck)
        MessageBoxWizardDialog.setTabOrder(self.openCheck, self.resetCheck)
        MessageBoxWizardDialog.setTabOrder(self.resetCheck, self.restoreCheck)
        MessageBoxWizardDialog.setTabOrder(self.restoreCheck, self.retryCheck)
        MessageBoxWizardDialog.setTabOrder(self.retryCheck, self.saveCheck)
        MessageBoxWizardDialog.setTabOrder(self.saveCheck, self.saveallCheck)
        MessageBoxWizardDialog.setTabOrder(self.saveallCheck, self.yesCheck)
        MessageBoxWizardDialog.setTabOrder(self.yesCheck, self.yestoallCheck)
        MessageBoxWizardDialog.setTabOrder(self.yestoallCheck, self.defaultCombo)

    def retranslateUi(self, MessageBoxWizardDialog):
        MessageBoxWizardDialog.setWindowTitle(_translate("MessageBoxWizardDialog", "QMessageBox Wizard", None))
        self.qtGroup.setTitle(_translate("MessageBoxWizardDialog", "Qt Version", None))
        self.rQt4.setToolTip(_translate("MessageBoxWizardDialog", "Select to generate code for Qt 4.0.0 or newer", None))
        self.rQt4.setText(_translate("MessageBoxWizardDialog", "Qt 4.0", None))
        self.rQt42.setToolTip(_translate("MessageBoxWizardDialog", "Select to generate code for Qt 4.2.0 or newer", None))
        self.rQt42.setText(_translate("MessageBoxWizardDialog", "Qt 4.2", None))
        self.groupBox.setTitle(_translate("MessageBoxWizardDialog", "Type", None))
        self.rInformation.setToolTip(_translate("MessageBoxWizardDialog", "Generate an Information QMessageBox", None))
        self.rInformation.setText(_translate("MessageBoxWizardDialog", "Information", None))
        self.rQuestion.setToolTip(_translate("MessageBoxWizardDialog", "Generate a Question QMessageBox", None))
        self.rQuestion.setText(_translate("MessageBoxWizardDialog", "Question", None))
        self.rWarning.setToolTip(_translate("MessageBoxWizardDialog", "Generate a Warning QMessageBox", None))
        self.rWarning.setText(_translate("MessageBoxWizardDialog", "Warning", None))
        self.rCritical.setToolTip(_translate("MessageBoxWizardDialog", "Generate a Critical QMessageBox", None))
        self.rCritical.setText(_translate("MessageBoxWizardDialog", "Critical", None))
        self.rAbout.setToolTip(_translate("MessageBoxWizardDialog", "Generate an About QMessageBox", None))
        self.rAbout.setText(_translate("MessageBoxWizardDialog", "About", None))
        self.rAboutQt.setToolTip(_translate("MessageBoxWizardDialog", "Generate an AboutQt QMessageBox", None))
        self.rAboutQt.setText(_translate("MessageBoxWizardDialog", "About Qt", None))
        self.textLabel1.setText(_translate("MessageBoxWizardDialog", "Caption", None))
        self.eCaption.setToolTip(_translate("MessageBoxWizardDialog", "Enter the caption for the QMessageBox", None))
        self.textLabel2.setText(_translate("MessageBoxWizardDialog", "Message", None))
        self.eMessage.setToolTip(_translate("MessageBoxWizardDialog", "Enter the message to be shown in the QMessageBox", None))
        self.buttons.setTitle(_translate("MessageBoxWizardDialog", "Buttons", None))
        self.cButton1.setToolTip(_translate("MessageBoxWizardDialog", "Enter the text of button 1", None))
        self.cButton1.setItemText(1, _translate("MessageBoxWizardDialog", "&OK", None))
        self.cButton1.setItemText(2, _translate("MessageBoxWizardDialog", "&Cancel", None))
        self.cButton1.setItemText(3, _translate("MessageBoxWizardDialog", "&Yes", None))
        self.cButton1.setItemText(4, _translate("MessageBoxWizardDialog", "&No", None))
        self.cButton1.setItemText(5, _translate("MessageBoxWizardDialog", "&Abort", None))
        self.cButton1.setItemText(6, _translate("MessageBoxWizardDialog", "&Retry", None))
        self.cButton1.setItemText(7, _translate("MessageBoxWizardDialog", "&Ignore", None))
        self.cButton0.setToolTip(_translate("MessageBoxWizardDialog", "Enter the text of button 0", None))
        self.cButton0.setItemText(1, _translate("MessageBoxWizardDialog", "&OK", None))
        self.cButton0.setItemText(2, _translate("MessageBoxWizardDialog", "&Cancel", None))
        self.cButton0.setItemText(3, _translate("MessageBoxWizardDialog", "&Yes", None))
        self.cButton0.setItemText(4, _translate("MessageBoxWizardDialog", "&No", None))
        self.cButton0.setItemText(5, _translate("MessageBoxWizardDialog", "&Abort", None))
        self.cButton0.setItemText(6, _translate("MessageBoxWizardDialog", "&Retry", None))
        self.cButton0.setItemText(7, _translate("MessageBoxWizardDialog", "&Ignore", None))
        self.textLabel3_2_2.setText(_translate("MessageBoxWizardDialog", "Button 2", None))
        self.cButton2.setToolTip(_translate("MessageBoxWizardDialog", "Enter the text of button 2", None))
        self.cButton2.setItemText(1, _translate("MessageBoxWizardDialog", "&OK", None))
        self.cButton2.setItemText(2, _translate("MessageBoxWizardDialog", "&Cancel", None))
        self.cButton2.setItemText(3, _translate("MessageBoxWizardDialog", "&Yes", None))
        self.cButton2.setItemText(4, _translate("MessageBoxWizardDialog", "&No", None))
        self.cButton2.setItemText(5, _translate("MessageBoxWizardDialog", "&Abort", None))
        self.cButton2.setItemText(6, _translate("MessageBoxWizardDialog", "&Retry", None))
        self.cButton2.setItemText(7, _translate("MessageBoxWizardDialog", "&Ignore", None))
        self.textLabel3_2.setText(_translate("MessageBoxWizardDialog", "Button 1", None))
        self.textLabel3.setText(_translate("MessageBoxWizardDialog", "Button 0", None))
        self.TextLabel1.setText(_translate("MessageBoxWizardDialog", "Default Button:", None))
        self.sDefault.setToolTip(_translate("MessageBoxWizardDialog", "Enter the index of the default button", None))
        self.TextLabel2.setText(_translate("MessageBoxWizardDialog", "Escape Button:", None))
        self.sEscape.setToolTip(_translate("MessageBoxWizardDialog", "Enter the index of the button to be activated upon pressing Esc or -1 to ignore", None))
        self.standardButtons.setTitle(_translate("MessageBoxWizardDialog", "Standard Buttons", None))
        self.applyCheck.setText(_translate("MessageBoxWizardDialog", "Apply", None))
        self.abortCheck.setText(_translate("MessageBoxWizardDialog", "Abort", None))
        self.cancelCheck.setText(_translate("MessageBoxWizardDialog", "Cancel", None))
        self.ignoreCheck.setText(_translate("MessageBoxWizardDialog", "Ignore", None))
        self.saveallCheck.setText(_translate("MessageBoxWizardDialog", "Save all", None))
        self.saveCheck.setText(_translate("MessageBoxWizardDialog", "Save", None))
        self.discardCheck.setText(_translate("MessageBoxWizardDialog", "Discard", None))
        self.yestoallCheck.setText(_translate("MessageBoxWizardDialog", "Yes to all", None))
        self.openCheck.setText(_translate("MessageBoxWizardDialog", "Open", None))
        self.resetCheck.setText(_translate("MessageBoxWizardDialog", "Reset", None))
        self.okCheck.setText(_translate("MessageBoxWizardDialog", "Ok", None))
        self.noCheck.setText(_translate("MessageBoxWizardDialog", "No", None))
        self.helpCheck.setText(_translate("MessageBoxWizardDialog", "Help", None))
        self.notoallCheck.setText(_translate("MessageBoxWizardDialog", "No to all", None))
        self.retryCheck.setText(_translate("MessageBoxWizardDialog", "Retry", None))
        self.restoreCheck.setText(_translate("MessageBoxWizardDialog", "Restore defaults", None))
        self.yesCheck.setText(_translate("MessageBoxWizardDialog", "Yes", None))
        self.closeCheck.setText(_translate("MessageBoxWizardDialog", "Close", None))
        self.TextLabel1_2.setText(_translate("MessageBoxWizardDialog", "Default Button:", None))
        self.defaultCombo.setToolTip(_translate("MessageBoxWizardDialog", "Select the default button", None))

