# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\ApplicationPage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ApplicationPage(object):
    def setupUi(self, ApplicationPage):
        ApplicationPage.setObjectName(_fromUtf8("ApplicationPage"))
        ApplicationPage.resize(589, 563)
        self.verticalLayout_3 = QtGui.QVBoxLayout(ApplicationPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.headerLabel = QtGui.QLabel(ApplicationPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line9_3 = QtGui.QFrame(ApplicationPage)
        self.line9_3.setFrameShape(QtGui.QFrame.HLine)
        self.line9_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_3.setFrameShape(QtGui.QFrame.HLine)
        self.line9_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_3.setObjectName(_fromUtf8("line9_3"))
        self.verticalLayout_3.addWidget(self.line9_3)
        self.singleApplicationCheckBox = QtGui.QCheckBox(ApplicationPage)
        self.singleApplicationCheckBox.setObjectName(_fromUtf8("singleApplicationCheckBox"))
        self.verticalLayout_3.addWidget(self.singleApplicationCheckBox)
        self.splashScreenCheckBox = QtGui.QCheckBox(ApplicationPage)
        self.splashScreenCheckBox.setObjectName(_fromUtf8("splashScreenCheckBox"))
        self.verticalLayout_3.addWidget(self.splashScreenCheckBox)
        self.groupBox_3 = QtGui.QGroupBox(ApplicationPage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.noOpenRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.noOpenRadioButton.setObjectName(_fromUtf8("noOpenRadioButton"))
        self.gridlayout.addWidget(self.noOpenRadioButton, 0, 0, 1, 1)
        self.lastFileRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.lastFileRadioButton.setObjectName(_fromUtf8("lastFileRadioButton"))
        self.gridlayout.addWidget(self.lastFileRadioButton, 0, 1, 1, 1)
        self.lastProjectRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.lastProjectRadioButton.setObjectName(_fromUtf8("lastProjectRadioButton"))
        self.gridlayout.addWidget(self.lastProjectRadioButton, 1, 0, 1, 1)
        self.lastMultiprojectRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.lastMultiprojectRadioButton.setObjectName(_fromUtf8("lastMultiprojectRadioButton"))
        self.gridlayout.addWidget(self.lastMultiprojectRadioButton, 1, 1, 1, 1)
        self.globalSessionRadioButton = QtGui.QRadioButton(self.groupBox_3)
        self.globalSessionRadioButton.setObjectName(_fromUtf8("globalSessionRadioButton"))
        self.gridlayout.addWidget(self.globalSessionRadioButton, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(ApplicationPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.noCheckRadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.noCheckRadioButton.setObjectName(_fromUtf8("noCheckRadioButton"))
        self.hboxlayout.addWidget(self.noCheckRadioButton)
        self.alwaysCheckRadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.alwaysCheckRadioButton.setObjectName(_fromUtf8("alwaysCheckRadioButton"))
        self.hboxlayout.addWidget(self.alwaysCheckRadioButton)
        self.dailyCheckRadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.dailyCheckRadioButton.setObjectName(_fromUtf8("dailyCheckRadioButton"))
        self.hboxlayout.addWidget(self.dailyCheckRadioButton)
        self.weeklyCheckRadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.weeklyCheckRadioButton.setObjectName(_fromUtf8("weeklyCheckRadioButton"))
        self.hboxlayout.addWidget(self.weeklyCheckRadioButton)
        self.monthlyCheckRadioButton = QtGui.QRadioButton(self.groupBox_2)
        self.monthlyCheckRadioButton.setObjectName(_fromUtf8("monthlyCheckRadioButton"))
        self.hboxlayout.addWidget(self.monthlyCheckRadioButton)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(ApplicationPage)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.systemEmailClientCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.systemEmailClientCheckBox.setObjectName(_fromUtf8("systemEmailClientCheckBox"))
        self.verticalLayout_2.addWidget(self.systemEmailClientCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(ApplicationPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.errorlogCheckBox = QtGui.QCheckBox(self.groupBox)
        self.errorlogCheckBox.setObjectName(_fromUtf8("errorlogCheckBox"))
        self.verticalLayout.addWidget(self.errorlogCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem = QtGui.QSpacerItem(571, 21, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(ApplicationPage)
        QtCore.QMetaObject.connectSlotsByName(ApplicationPage)
        ApplicationPage.setTabOrder(self.singleApplicationCheckBox, self.splashScreenCheckBox)
        ApplicationPage.setTabOrder(self.splashScreenCheckBox, self.noOpenRadioButton)
        ApplicationPage.setTabOrder(self.noOpenRadioButton, self.lastFileRadioButton)
        ApplicationPage.setTabOrder(self.lastFileRadioButton, self.lastProjectRadioButton)
        ApplicationPage.setTabOrder(self.lastProjectRadioButton, self.lastMultiprojectRadioButton)
        ApplicationPage.setTabOrder(self.lastMultiprojectRadioButton, self.globalSessionRadioButton)
        ApplicationPage.setTabOrder(self.globalSessionRadioButton, self.noCheckRadioButton)
        ApplicationPage.setTabOrder(self.noCheckRadioButton, self.alwaysCheckRadioButton)
        ApplicationPage.setTabOrder(self.alwaysCheckRadioButton, self.dailyCheckRadioButton)
        ApplicationPage.setTabOrder(self.dailyCheckRadioButton, self.weeklyCheckRadioButton)
        ApplicationPage.setTabOrder(self.weeklyCheckRadioButton, self.monthlyCheckRadioButton)
        ApplicationPage.setTabOrder(self.monthlyCheckRadioButton, self.systemEmailClientCheckBox)
        ApplicationPage.setTabOrder(self.systemEmailClientCheckBox, self.errorlogCheckBox)

    def retranslateUi(self, ApplicationPage):
        self.headerLabel.setText(_translate("ApplicationPage", "<b>Configure the application</b>", None))
        self.singleApplicationCheckBox.setToolTip(_translate("ApplicationPage", "Select, if only one instance of the application should be running", None))
        self.singleApplicationCheckBox.setText(_translate("ApplicationPage", "Single Application Mode", None))
        self.splashScreenCheckBox.setToolTip(_translate("ApplicationPage", "Select to show the startup splash screen", None))
        self.splashScreenCheckBox.setText(_translate("ApplicationPage", "Show Splash Screen at startup", None))
        self.groupBox_3.setTitle(_translate("ApplicationPage", "Open at startup", None))
        self.noOpenRadioButton.setToolTip(_translate("ApplicationPage", "Select to not open anything", None))
        self.noOpenRadioButton.setText(_translate("ApplicationPage", "None", None))
        self.lastFileRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened file", None))
        self.lastFileRadioButton.setText(_translate("ApplicationPage", "Last File", None))
        self.lastProjectRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened project", None))
        self.lastProjectRadioButton.setText(_translate("ApplicationPage", "Last Project", None))
        self.lastMultiprojectRadioButton.setToolTip(_translate("ApplicationPage", "Select to open the most recently opened multiproject", None))
        self.lastMultiprojectRadioButton.setText(_translate("ApplicationPage", "Last Multiproject", None))
        self.globalSessionRadioButton.setToolTip(_translate("ApplicationPage", "Select to restore the global session", None))
        self.globalSessionRadioButton.setText(_translate("ApplicationPage", "Global Session", None))
        self.groupBox_2.setTitle(_translate("ApplicationPage", "Check for updates", None))
        self.noCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to disable update checking", None))
        self.noCheckRadioButton.setText(_translate("ApplicationPage", "None", None))
        self.alwaysCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates at every startup", None))
        self.alwaysCheckRadioButton.setText(_translate("ApplicationPage", "Always", None))
        self.dailyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a day", None))
        self.dailyCheckRadioButton.setText(_translate("ApplicationPage", "Daily", None))
        self.weeklyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a week", None))
        self.weeklyCheckRadioButton.setText(_translate("ApplicationPage", "Weekly", None))
        self.monthlyCheckRadioButton.setToolTip(_translate("ApplicationPage", "Select to check for updates once a month", None))
        self.monthlyCheckRadioButton.setText(_translate("ApplicationPage", "Monthly", None))
        self.groupBox_4.setTitle(_translate("ApplicationPage", "Reporting", None))
        self.systemEmailClientCheckBox.setToolTip(_translate("ApplicationPage", "Select to use the system email client to send reports", None))
        self.systemEmailClientCheckBox.setText(_translate("ApplicationPage", "Use System Email Client", None))
        self.groupBox.setTitle(_translate("ApplicationPage", "Error Log", None))
        self.errorlogCheckBox.setToolTip(_translate("ApplicationPage", "Select to check the existence of an error log upon startup", None))
        self.errorlogCheckBox.setText(_translate("ApplicationPage", "Check for Error Log at Startup", None))

