# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\EditorHighlightingStylesPage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EditorHighlightingStylesPage(object):
    def setupUi(self, EditorHighlightingStylesPage):
        EditorHighlightingStylesPage.setObjectName(_fromUtf8("EditorHighlightingStylesPage"))
        EditorHighlightingStylesPage.resize(550, 592)
        self.verticalLayout = QtGui.QVBoxLayout(EditorHighlightingStylesPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.headerLabel = QtGui.QLabel(EditorHighlightingStylesPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout.addWidget(self.headerLabel)
        self.line1 = QtGui.QFrame(EditorHighlightingStylesPage)
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setFrameShape(QtGui.QFrame.HLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName(_fromUtf8("line1"))
        self.verticalLayout.addWidget(self.line1)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.TextLabel1_3 = QtGui.QLabel(EditorHighlightingStylesPage)
        self.TextLabel1_3.setToolTip(_fromUtf8(""))
        self.TextLabel1_3.setObjectName(_fromUtf8("TextLabel1_3"))
        self.hboxlayout.addWidget(self.TextLabel1_3)
        self.lexerLanguageComboBox = QtGui.QComboBox(EditorHighlightingStylesPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lexerLanguageComboBox.sizePolicy().hasHeightForWidth())
        self.lexerLanguageComboBox.setSizePolicy(sizePolicy)
        self.lexerLanguageComboBox.setObjectName(_fromUtf8("lexerLanguageComboBox"))
        self.hboxlayout.addWidget(self.lexerLanguageComboBox)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.styleGroup = QtGui.QGroupBox(EditorHighlightingStylesPage)
        self.styleGroup.setObjectName(_fromUtf8("styleGroup"))
        self.gridLayout = QtGui.QGridLayout(self.styleGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.styleElementList = QtGui.QListWidget(self.styleGroup)
        self.styleElementList.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.styleElementList.setObjectName(_fromUtf8("styleElementList"))
        self.gridLayout.addWidget(self.styleElementList, 0, 0, 12, 1)
        self.foregroundButton = QtGui.QPushButton(self.styleGroup)
        self.foregroundButton.setObjectName(_fromUtf8("foregroundButton"))
        self.gridLayout.addWidget(self.foregroundButton, 0, 1, 1, 1)
        self.backgroundButton = QtGui.QPushButton(self.styleGroup)
        self.backgroundButton.setObjectName(_fromUtf8("backgroundButton"))
        self.gridLayout.addWidget(self.backgroundButton, 1, 1, 1, 1)
        self.fontButton = QtGui.QPushButton(self.styleGroup)
        self.fontButton.setObjectName(_fromUtf8("fontButton"))
        self.gridLayout.addWidget(self.fontButton, 2, 1, 1, 1)
        self.eolfillCheckBox = QtGui.QCheckBox(self.styleGroup)
        self.eolfillCheckBox.setObjectName(_fromUtf8("eolfillCheckBox"))
        self.gridLayout.addWidget(self.eolfillCheckBox, 3, 1, 1, 1)
        self.line = QtGui.QFrame(self.styleGroup)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.defaultButton = QtGui.QPushButton(self.styleGroup)
        self.defaultButton.setObjectName(_fromUtf8("defaultButton"))
        self.gridLayout.addWidget(self.defaultButton, 5, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 51, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.allBackgroundColoursButton = QtGui.QPushButton(self.styleGroup)
        self.allBackgroundColoursButton.setObjectName(_fromUtf8("allBackgroundColoursButton"))
        self.gridLayout.addWidget(self.allBackgroundColoursButton, 7, 1, 1, 1)
        self.allFontsButton = QtGui.QPushButton(self.styleGroup)
        self.allFontsButton.setObjectName(_fromUtf8("allFontsButton"))
        self.gridLayout.addWidget(self.allFontsButton, 8, 1, 1, 1)
        self.allEolFillButton = QtGui.QPushButton(self.styleGroup)
        self.allEolFillButton.setObjectName(_fromUtf8("allEolFillButton"))
        self.gridLayout.addWidget(self.allEolFillButton, 9, 1, 1, 1)
        self.line_2 = QtGui.QFrame(self.styleGroup)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 10, 1, 1, 1)
        self.allDefaultButton = QtGui.QPushButton(self.styleGroup)
        self.allDefaultButton.setObjectName(_fromUtf8("allDefaultButton"))
        self.gridLayout.addWidget(self.allDefaultButton, 11, 1, 1, 1)
        self.sampleText = QtGui.QLineEdit(self.styleGroup)
        self.sampleText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sampleText.setAlignment(QtCore.Qt.AlignHCenter)
        self.sampleText.setReadOnly(True)
        self.sampleText.setObjectName(_fromUtf8("sampleText"))
        self.gridLayout.addWidget(self.sampleText, 12, 0, 1, 2)
        self.verticalLayout.addWidget(self.styleGroup)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.importCurrentButton = QtGui.QPushButton(EditorHighlightingStylesPage)
        self.importCurrentButton.setEnabled(False)
        self.importCurrentButton.setObjectName(_fromUtf8("importCurrentButton"))
        self.horizontalLayout.addWidget(self.importCurrentButton)
        self.exportCurrentButton = QtGui.QPushButton(EditorHighlightingStylesPage)
        self.exportCurrentButton.setEnabled(False)
        self.exportCurrentButton.setObjectName(_fromUtf8("exportCurrentButton"))
        self.horizontalLayout.addWidget(self.exportCurrentButton)
        self.importAllButton = QtGui.QPushButton(EditorHighlightingStylesPage)
        self.importAllButton.setObjectName(_fromUtf8("importAllButton"))
        self.horizontalLayout.addWidget(self.importAllButton)
        self.exportAllButton = QtGui.QPushButton(EditorHighlightingStylesPage)
        self.exportAllButton.setObjectName(_fromUtf8("exportAllButton"))
        self.horizontalLayout.addWidget(self.exportAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EditorHighlightingStylesPage)
        QtCore.QMetaObject.connectSlotsByName(EditorHighlightingStylesPage)
        EditorHighlightingStylesPage.setTabOrder(self.lexerLanguageComboBox, self.styleElementList)
        EditorHighlightingStylesPage.setTabOrder(self.styleElementList, self.foregroundButton)
        EditorHighlightingStylesPage.setTabOrder(self.foregroundButton, self.backgroundButton)
        EditorHighlightingStylesPage.setTabOrder(self.backgroundButton, self.fontButton)
        EditorHighlightingStylesPage.setTabOrder(self.fontButton, self.eolfillCheckBox)
        EditorHighlightingStylesPage.setTabOrder(self.eolfillCheckBox, self.defaultButton)
        EditorHighlightingStylesPage.setTabOrder(self.defaultButton, self.allBackgroundColoursButton)
        EditorHighlightingStylesPage.setTabOrder(self.allBackgroundColoursButton, self.allFontsButton)
        EditorHighlightingStylesPage.setTabOrder(self.allFontsButton, self.allEolFillButton)
        EditorHighlightingStylesPage.setTabOrder(self.allEolFillButton, self.allDefaultButton)

    def retranslateUi(self, EditorHighlightingStylesPage):
        self.headerLabel.setText(_translate("EditorHighlightingStylesPage", "<b>Configure syntax highlighting</b>", None))
        self.TextLabel1_3.setText(_translate("EditorHighlightingStylesPage", "Lexer Language:", None))
        self.lexerLanguageComboBox.setToolTip(_translate("EditorHighlightingStylesPage", "Select the lexer language to be configured.", None))
        self.styleGroup.setTitle(_translate("EditorHighlightingStylesPage", "Style Element", None))
        self.foregroundButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the foreground colour.", None))
        self.foregroundButton.setText(_translate("EditorHighlightingStylesPage", "Foreground Colour", None))
        self.backgroundButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the background colour.", None))
        self.backgroundButton.setText(_translate("EditorHighlightingStylesPage", "Background Colour", None))
        self.fontButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the font.", None))
        self.fontButton.setText(_translate("EditorHighlightingStylesPage", "Font", None))
        self.eolfillCheckBox.setToolTip(_translate("EditorHighlightingStylesPage", "Select end of line fill.", None))
        self.eolfillCheckBox.setText(_translate("EditorHighlightingStylesPage", "Fill to end of line", None))
        self.defaultButton.setToolTip(_translate("EditorHighlightingStylesPage", "Press to set the current style to its default values", None))
        self.defaultButton.setText(_translate("EditorHighlightingStylesPage", "to Default", None))
        self.allBackgroundColoursButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the background colour for all styles", None))
        self.allBackgroundColoursButton.setText(_translate("EditorHighlightingStylesPage", "All Background Colours", None))
        self.allFontsButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the font for all styles.", None))
        self.allFontsButton.setText(_translate("EditorHighlightingStylesPage", "All Fonts", None))
        self.allEolFillButton.setToolTip(_translate("EditorHighlightingStylesPage", "Select the eol fill for all styles", None))
        self.allEolFillButton.setText(_translate("EditorHighlightingStylesPage", "All Fill to end of line", None))
        self.allDefaultButton.setToolTip(_translate("EditorHighlightingStylesPage", "Press to set all styles to their default values", None))
        self.allDefaultButton.setText(_translate("EditorHighlightingStylesPage", "All to Default", None))
        self.sampleText.setText(_translate("EditorHighlightingStylesPage", "Sample Text", None))
        self.importCurrentButton.setToolTip(_translate("EditorHighlightingStylesPage", "Imports all styles of the currently selected language", None))
        self.importCurrentButton.setText(_translate("EditorHighlightingStylesPage", "Import styles", None))
        self.exportCurrentButton.setToolTip(_translate("EditorHighlightingStylesPage", "Exports all styles of the currently selected language", None))
        self.exportCurrentButton.setText(_translate("EditorHighlightingStylesPage", "Export styles", None))
        self.importAllButton.setToolTip(_translate("EditorHighlightingStylesPage", "Imports all styles of all languages", None))
        self.importAllButton.setText(_translate("EditorHighlightingStylesPage", "Import all styles", None))
        self.exportAllButton.setToolTip(_translate("EditorHighlightingStylesPage", "Exports all styles of all languages", None))
        self.exportAllButton.setText(_translate("EditorHighlightingStylesPage", "Export all styles", None))

