# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\EditorStylesPage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EditorStylesPage(object):
    def setupUi(self, EditorStylesPage):
        EditorStylesPage.setObjectName(_fromUtf8("EditorStylesPage"))
        EditorStylesPage.resize(581, 1602)
        self.verticalLayout_3 = QtGui.QVBoxLayout(EditorStylesPage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.headerLabel = QtGui.QLabel(EditorStylesPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line3 = QtGui.QFrame(EditorStylesPage)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.verticalLayout_3.addWidget(self.line3)
        self.label_3 = QtGui.QLabel(EditorStylesPage)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.groupBox_12 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.editAreaOverrideCheckBox = QtGui.QCheckBox(self.groupBox_12)
        self.editAreaOverrideCheckBox.setObjectName(_fromUtf8("editAreaOverrideCheckBox"))
        self.gridLayout_6.addWidget(self.editAreaOverrideCheckBox, 0, 0, 1, 4)
        self.TextLabel2_2_2_2_2_12 = QtGui.QLabel(self.groupBox_12)
        self.TextLabel2_2_2_2_2_12.setEnabled(False)
        self.TextLabel2_2_2_2_2_12.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_12"))
        self.gridLayout_6.addWidget(self.TextLabel2_2_2_2_2_12, 1, 0, 1, 1)
        self.editAreaForegroundButton = QtGui.QPushButton(self.groupBox_12)
        self.editAreaForegroundButton.setEnabled(False)
        self.editAreaForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.editAreaForegroundButton.setText(_fromUtf8(""))
        self.editAreaForegroundButton.setObjectName(_fromUtf8("editAreaForegroundButton"))
        self.gridLayout_6.addWidget(self.editAreaForegroundButton, 1, 1, 1, 1)
        self.TextLabel2_2_2_2_2_11 = QtGui.QLabel(self.groupBox_12)
        self.TextLabel2_2_2_2_2_11.setEnabled(False)
        self.TextLabel2_2_2_2_2_11.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_11"))
        self.gridLayout_6.addWidget(self.TextLabel2_2_2_2_2_11, 1, 2, 1, 1)
        self.editAreaBackgroundButton = QtGui.QPushButton(self.groupBox_12)
        self.editAreaBackgroundButton.setEnabled(False)
        self.editAreaBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.editAreaBackgroundButton.setText(_fromUtf8(""))
        self.editAreaBackgroundButton.setObjectName(_fromUtf8("editAreaBackgroundButton"))
        self.gridLayout_6.addWidget(self.editAreaBackgroundButton, 1, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.groupBox_5 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.monospacedCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.monospacedCheckBox.setObjectName(_fromUtf8("monospacedCheckBox"))
        self.gridlayout.addWidget(self.monospacedCheckBox, 1, 2, 1, 1)
        self.defaultFontSample = QtGui.QLineEdit(self.groupBox_5)
        self.defaultFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.defaultFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.defaultFontSample.setReadOnly(True)
        self.defaultFontSample.setObjectName(_fromUtf8("defaultFontSample"))
        self.gridlayout.addWidget(self.defaultFontSample, 0, 1, 1, 1)
        self.defaultFontButton = QtGui.QPushButton(self.groupBox_5)
        self.defaultFontButton.setObjectName(_fromUtf8("defaultFontButton"))
        self.gridlayout.addWidget(self.defaultFontButton, 0, 0, 1, 1)
        self.monospacedFontButton = QtGui.QPushButton(self.groupBox_5)
        self.monospacedFontButton.setObjectName(_fromUtf8("monospacedFontButton"))
        self.gridlayout.addWidget(self.monospacedFontButton, 1, 0, 1, 1)
        self.monospacedFontSample = QtGui.QLineEdit(self.groupBox_5)
        self.monospacedFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.monospacedFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.monospacedFontSample.setReadOnly(True)
        self.monospacedFontSample.setObjectName(_fromUtf8("monospacedFontSample"))
        self.gridlayout.addWidget(self.monospacedFontSample, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.linenoCheckBox = QtGui.QCheckBox(self.groupBox)
        self.linenoCheckBox.setObjectName(_fromUtf8("linenoCheckBox"))
        self.gridLayout_2.addWidget(self.linenoCheckBox, 0, 0, 1, 1)
        self.foldingCheckBox = QtGui.QCheckBox(self.groupBox)
        self.foldingCheckBox.setObjectName(_fromUtf8("foldingCheckBox"))
        self.gridLayout_2.addWidget(self.foldingCheckBox, 0, 1, 1, 1)
        self.unifiedMarginsCheckBox = QtGui.QCheckBox(self.groupBox)
        self.unifiedMarginsCheckBox.setObjectName(_fromUtf8("unifiedMarginsCheckBox"))
        self.gridLayout_2.addWidget(self.unifiedMarginsCheckBox, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.TextLabel1_4_2_2 = QtGui.QLabel(self.groupBox)
        self.TextLabel1_4_2_2.setObjectName(_fromUtf8("TextLabel1_4_2_2"))
        self.hboxlayout.addWidget(self.TextLabel1_4_2_2)
        self.foldingStyleComboBox = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.foldingStyleComboBox.sizePolicy().hasHeightForWidth())
        self.foldingStyleComboBox.setSizePolicy(sizePolicy)
        self.foldingStyleComboBox.setObjectName(_fromUtf8("foldingStyleComboBox"))
        self.foldingStyleComboBox.addItem(_fromUtf8(""))
        self.foldingStyleComboBox.addItem(_fromUtf8(""))
        self.foldingStyleComboBox.addItem(_fromUtf8(""))
        self.foldingStyleComboBox.addItem(_fromUtf8(""))
        self.foldingStyleComboBox.addItem(_fromUtf8(""))
        self.hboxlayout.addWidget(self.foldingStyleComboBox)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TextLabel2_2_2_2_2_6 = QtGui.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_6.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_6"))
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_6, 0, 0, 1, 1)
        self.marginsForegroundButton = QtGui.QPushButton(self.groupBox)
        self.marginsForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.marginsForegroundButton.setText(_fromUtf8(""))
        self.marginsForegroundButton.setObjectName(_fromUtf8("marginsForegroundButton"))
        self.gridLayout.addWidget(self.marginsForegroundButton, 0, 1, 1, 1)
        self.TextLabel2_2_2_2_2_7 = QtGui.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_7.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_7"))
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_7, 0, 2, 1, 1)
        self.marginsBackgroundButton = QtGui.QPushButton(self.groupBox)
        self.marginsBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.marginsBackgroundButton.setText(_fromUtf8(""))
        self.marginsBackgroundButton.setObjectName(_fromUtf8("marginsBackgroundButton"))
        self.gridLayout.addWidget(self.marginsBackgroundButton, 0, 3, 1, 1)
        self.TextLabel2_2_2_2_2_8 = QtGui.QLabel(self.groupBox)
        self.TextLabel2_2_2_2_2_8.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_8"))
        self.gridLayout.addWidget(self.TextLabel2_2_2_2_2_8, 1, 0, 1, 1)
        self.foldmarginBackgroundButton = QtGui.QPushButton(self.groupBox)
        self.foldmarginBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.foldmarginBackgroundButton.setText(_fromUtf8(""))
        self.foldmarginBackgroundButton.setObjectName(_fromUtf8("foldmarginBackgroundButton"))
        self.gridLayout.addWidget(self.foldmarginBackgroundButton, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.linenumbersFontButton = QtGui.QPushButton(self.groupBox)
        self.linenumbersFontButton.setObjectName(_fromUtf8("linenumbersFontButton"))
        self.horizontalLayout.addWidget(self.linenumbersFontButton)
        self.marginsFontSample = QtGui.QLineEdit(self.groupBox)
        self.marginsFontSample.setMinimumSize(QtCore.QSize(200, 0))
        self.marginsFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.marginsFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.marginsFontSample.setReadOnly(True)
        self.marginsFontSample.setObjectName(_fromUtf8("marginsFontSample"))
        self.horizontalLayout.addWidget(self.marginsFontSample)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self._2 = QtGui.QVBoxLayout(self.groupBox_3)
        self._2.setObjectName(_fromUtf8("_2"))
        self._3 = QtGui.QGridLayout()
        self._3.setObjectName(_fromUtf8("_3"))
        self.customSelColourCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.customSelColourCheckBox.setObjectName(_fromUtf8("customSelColourCheckBox"))
        self._3.addWidget(self.customSelColourCheckBox, 0, 0, 1, 1)
        self.colourizeSelTextCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.colourizeSelTextCheckBox.setObjectName(_fromUtf8("colourizeSelTextCheckBox"))
        self._3.addWidget(self.colourizeSelTextCheckBox, 0, 1, 1, 1)
        self.extentSelEolCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.extentSelEolCheckBox.setObjectName(_fromUtf8("extentSelEolCheckBox"))
        self._3.addWidget(self.extentSelEolCheckBox, 1, 0, 1, 1)
        self._2.addLayout(self._3)
        self._4 = QtGui.QHBoxLayout()
        self._4.setObjectName(_fromUtf8("_4"))
        self.TextLabel2_2_2_2_2_4 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel2_2_2_2_2_4.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_4"))
        self._4.addWidget(self.TextLabel2_2_2_2_2_4)
        self.selectionForegroundButton = QtGui.QPushButton(self.groupBox_3)
        self.selectionForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.selectionForegroundButton.setText(_fromUtf8(""))
        self.selectionForegroundButton.setObjectName(_fromUtf8("selectionForegroundButton"))
        self._4.addWidget(self.selectionForegroundButton)
        self.TextLabel2_2_2_2_2_5 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel2_2_2_2_2_5.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_5"))
        self._4.addWidget(self.TextLabel2_2_2_2_2_5)
        self.selectionBackgroundButton = QtGui.QPushButton(self.groupBox_3)
        self.selectionBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.selectionBackgroundButton.setText(_fromUtf8(""))
        self.selectionBackgroundButton.setObjectName(_fromUtf8("selectionBackgroundButton"))
        self._4.addWidget(self.selectionBackgroundButton)
        self._2.addLayout(self._4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self._5 = QtGui.QVBoxLayout(self.groupBox_4)
        self._5.setObjectName(_fromUtf8("_5"))
        self.caretlineVisibleCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.caretlineVisibleCheckBox.setObjectName(_fromUtf8("caretlineVisibleCheckBox"))
        self._5.addWidget(self.caretlineVisibleCheckBox)
        self._6 = QtGui.QHBoxLayout()
        self._6.setObjectName(_fromUtf8("_6"))
        self.textLabel1_7 = QtGui.QLabel(self.groupBox_4)
        self.textLabel1_7.setObjectName(_fromUtf8("textLabel1_7"))
        self._6.addWidget(self.textLabel1_7)
        self.caretWidthSpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.caretWidthSpinBox.setMinimum(1)
        self.caretWidthSpinBox.setMaximum(3)
        self.caretWidthSpinBox.setObjectName(_fromUtf8("caretWidthSpinBox"))
        self._6.addWidget(self.caretWidthSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._6.addItem(spacerItem1)
        self._5.addLayout(self._6)
        self._7 = QtGui.QHBoxLayout()
        self._7.setObjectName(_fromUtf8("_7"))
        self.TextLabel2_2_2_2_2_2 = QtGui.QLabel(self.groupBox_4)
        self.TextLabel2_2_2_2_2_2.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_2"))
        self._7.addWidget(self.TextLabel2_2_2_2_2_2)
        self.caretForegroundButton = QtGui.QPushButton(self.groupBox_4)
        self.caretForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.caretForegroundButton.setText(_fromUtf8(""))
        self.caretForegroundButton.setObjectName(_fromUtf8("caretForegroundButton"))
        self._7.addWidget(self.caretForegroundButton)
        self.TextLabel2_2_2_2_2_3 = QtGui.QLabel(self.groupBox_4)
        self.TextLabel2_2_2_2_2_3.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_3"))
        self._7.addWidget(self.TextLabel2_2_2_2_2_3)
        self.caretlineBackgroundButton = QtGui.QPushButton(self.groupBox_4)
        self.caretlineBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.caretlineBackgroundButton.setText(_fromUtf8(""))
        self.caretlineBackgroundButton.setObjectName(_fromUtf8("caretlineBackgroundButton"))
        self._7.addWidget(self.caretlineBackgroundButton)
        self._5.addLayout(self._7)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self._8 = QtGui.QHBoxLayout(self.groupBox_2)
        self._8.setObjectName(_fromUtf8("_8"))
        self.TextLabel3_2_2 = QtGui.QLabel(self.groupBox_2)
        self.TextLabel3_2_2.setObjectName(_fromUtf8("TextLabel3_2_2"))
        self._8.addWidget(self.TextLabel3_2_2)
        self.currentLineMarkerButton = QtGui.QPushButton(self.groupBox_2)
        self.currentLineMarkerButton.setMinimumSize(QtCore.QSize(100, 0))
        self.currentLineMarkerButton.setText(_fromUtf8(""))
        self.currentLineMarkerButton.setObjectName(_fromUtf8("currentLineMarkerButton"))
        self._8.addWidget(self.currentLineMarkerButton)
        self.TextLabel4_2_2 = QtGui.QLabel(self.groupBox_2)
        self.TextLabel4_2_2.setObjectName(_fromUtf8("TextLabel4_2_2"))
        self._8.addWidget(self.TextLabel4_2_2)
        self.errorMarkerButton = QtGui.QPushButton(self.groupBox_2)
        self.errorMarkerButton.setMinimumSize(QtCore.QSize(100, 0))
        self.errorMarkerButton.setText(_fromUtf8(""))
        self.errorMarkerButton.setObjectName(_fromUtf8("errorMarkerButton"))
        self._8.addWidget(self.errorMarkerButton)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_6 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self._9 = QtGui.QGridLayout(self.groupBox_6)
        self._9.setObjectName(_fromUtf8("_9"))
        self.bracehighlightingCheckBox = QtGui.QCheckBox(self.groupBox_6)
        self.bracehighlightingCheckBox.setObjectName(_fromUtf8("bracehighlightingCheckBox"))
        self._9.addWidget(self.bracehighlightingCheckBox, 0, 0, 1, 2)
        self.TextLabel1_3_2 = QtGui.QLabel(self.groupBox_6)
        self.TextLabel1_3_2.setObjectName(_fromUtf8("TextLabel1_3_2"))
        self._9.addWidget(self.TextLabel1_3_2, 1, 0, 1, 1)
        self.matchingBracesButton = QtGui.QPushButton(self.groupBox_6)
        self.matchingBracesButton.setMinimumSize(QtCore.QSize(100, 0))
        self.matchingBracesButton.setText(_fromUtf8(""))
        self.matchingBracesButton.setObjectName(_fromUtf8("matchingBracesButton"))
        self._9.addWidget(self.matchingBracesButton, 1, 1, 1, 1)
        self.TextLabel1_3_2_2 = QtGui.QLabel(self.groupBox_6)
        self.TextLabel1_3_2_2.setObjectName(_fromUtf8("TextLabel1_3_2_2"))
        self._9.addWidget(self.TextLabel1_3_2_2, 1, 2, 1, 1)
        self.matchingBracesBackButton = QtGui.QPushButton(self.groupBox_6)
        self.matchingBracesBackButton.setMinimumSize(QtCore.QSize(100, 0))
        self.matchingBracesBackButton.setText(_fromUtf8(""))
        self.matchingBracesBackButton.setObjectName(_fromUtf8("matchingBracesBackButton"))
        self._9.addWidget(self.matchingBracesBackButton, 1, 3, 1, 1)
        self.TextLabel2_2_2 = QtGui.QLabel(self.groupBox_6)
        self.TextLabel2_2_2.setMinimumSize(QtCore.QSize(100, 0))
        self.TextLabel2_2_2.setObjectName(_fromUtf8("TextLabel2_2_2"))
        self._9.addWidget(self.TextLabel2_2_2, 2, 0, 1, 1)
        self.nonmatchingBracesButton = QtGui.QPushButton(self.groupBox_6)
        self.nonmatchingBracesButton.setText(_fromUtf8(""))
        self.nonmatchingBracesButton.setObjectName(_fromUtf8("nonmatchingBracesButton"))
        self._9.addWidget(self.nonmatchingBracesButton, 2, 1, 1, 1)
        self.TextLabel2_2_2_3 = QtGui.QLabel(self.groupBox_6)
        self.TextLabel2_2_2_3.setMinimumSize(QtCore.QSize(100, 0))
        self.TextLabel2_2_2_3.setObjectName(_fromUtf8("TextLabel2_2_2_3"))
        self._9.addWidget(self.TextLabel2_2_2_3, 2, 2, 1, 1)
        self.nonmatchingBracesBackButton = QtGui.QPushButton(self.groupBox_6)
        self.nonmatchingBracesBackButton.setText(_fromUtf8(""))
        self.nonmatchingBracesBackButton.setObjectName(_fromUtf8("nonmatchingBracesBackButton"))
        self._9.addWidget(self.nonmatchingBracesBackButton, 2, 3, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self._10 = QtGui.QVBoxLayout(self.groupBox_7)
        self._10.setObjectName(_fromUtf8("_10"))
        self._11 = QtGui.QGridLayout()
        self._11.setObjectName(_fromUtf8("_11"))
        self.eolCheckBox = QtGui.QCheckBox(self.groupBox_7)
        self.eolCheckBox.setObjectName(_fromUtf8("eolCheckBox"))
        self._11.addWidget(self.eolCheckBox, 0, 0, 1, 1)
        self.wrapLongLinesCheckBox = QtGui.QCheckBox(self.groupBox_7)
        self.wrapLongLinesCheckBox.setObjectName(_fromUtf8("wrapLongLinesCheckBox"))
        self._11.addWidget(self.wrapLongLinesCheckBox, 0, 1, 1, 1)
        self._10.addLayout(self._11)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self._13 = QtGui.QGridLayout(self.groupBox_9)
        self._13.setObjectName(_fromUtf8("_13"))
        spacerItem2 = QtGui.QSpacerItem(211, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._13.addItem(spacerItem2, 0, 2, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(201, 31, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._13.addItem(spacerItem3, 2, 2, 1, 2)
        self.edgeBackgroundColorButton = QtGui.QPushButton(self.groupBox_9)
        self.edgeBackgroundColorButton.setMinimumSize(QtCore.QSize(100, 0))
        self.edgeBackgroundColorButton.setText(_fromUtf8(""))
        self.edgeBackgroundColorButton.setObjectName(_fromUtf8("edgeBackgroundColorButton"))
        self._13.addWidget(self.edgeBackgroundColorButton, 2, 1, 1, 1)
        self.TextLabel13_3_2_2 = QtGui.QLabel(self.groupBox_9)
        self.TextLabel13_3_2_2.setObjectName(_fromUtf8("TextLabel13_3_2_2"))
        self._13.addWidget(self.TextLabel13_3_2_2, 2, 0, 1, 1)
        self.edgeLineColumnSlider = QtGui.QSlider(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeLineColumnSlider.sizePolicy().hasHeightForWidth())
        self.edgeLineColumnSlider.setSizePolicy(sizePolicy)
        self.edgeLineColumnSlider.setMinimum(0)
        self.edgeLineColumnSlider.setMaximum(160)
        self.edgeLineColumnSlider.setProperty("value", 80)
        self.edgeLineColumnSlider.setOrientation(QtCore.Qt.Horizontal)
        self.edgeLineColumnSlider.setTickInterval(10)
        self.edgeLineColumnSlider.setObjectName(_fromUtf8("edgeLineColumnSlider"))
        self._13.addWidget(self.edgeLineColumnSlider, 1, 1, 1, 2)
        self.edgeLineColumnLCD = QtGui.QLCDNumber(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeLineColumnLCD.sizePolicy().hasHeightForWidth())
        self.edgeLineColumnLCD.setSizePolicy(sizePolicy)
        self.edgeLineColumnLCD.setDigitCount(3)
        self.edgeLineColumnLCD.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.edgeLineColumnLCD.setProperty("value", 80.0)
        self.edgeLineColumnLCD.setObjectName(_fromUtf8("edgeLineColumnLCD"))
        self._13.addWidget(self.edgeLineColumnLCD, 1, 3, 1, 1)
        self.TextLabel13_3_2 = QtGui.QLabel(self.groupBox_9)
        self.TextLabel13_3_2.setObjectName(_fromUtf8("TextLabel13_3_2"))
        self._13.addWidget(self.TextLabel13_3_2, 1, 0, 1, 1)
        self.textLabel1_14 = QtGui.QLabel(self.groupBox_9)
        self.textLabel1_14.setObjectName(_fromUtf8("textLabel1_14"))
        self._13.addWidget(self.textLabel1_14, 0, 0, 1, 1)
        self.edgeModeCombo = QtGui.QComboBox(self.groupBox_9)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edgeModeCombo.sizePolicy().hasHeightForWidth())
        self.edgeModeCombo.setSizePolicy(sizePolicy)
        self.edgeModeCombo.setObjectName(_fromUtf8("edgeModeCombo"))
        self.edgeModeCombo.addItem(_fromUtf8(""))
        self.edgeModeCombo.addItem(_fromUtf8(""))
        self.edgeModeCombo.addItem(_fromUtf8(""))
        self._13.addWidget(self.edgeModeCombo, 0, 1, 1, 1)
        self._10.addWidget(self.groupBox_9)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_11 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.whitespaceCheckBox = QtGui.QCheckBox(self.groupBox_11)
        self.whitespaceCheckBox.setObjectName(_fromUtf8("whitespaceCheckBox"))
        self.verticalLayout_2.addWidget(self.whitespaceCheckBox)
        self._12 = QtGui.QHBoxLayout()
        self._12.setObjectName(_fromUtf8("_12"))
        self.textLabel1_8 = QtGui.QLabel(self.groupBox_11)
        self.textLabel1_8.setObjectName(_fromUtf8("textLabel1_8"))
        self._12.addWidget(self.textLabel1_8)
        self.whitespaceSizeSpinBox = QtGui.QSpinBox(self.groupBox_11)
        self.whitespaceSizeSpinBox.setMinimum(1)
        self.whitespaceSizeSpinBox.setMaximum(10)
        self.whitespaceSizeSpinBox.setObjectName(_fromUtf8("whitespaceSizeSpinBox"))
        self._12.addWidget(self.whitespaceSizeSpinBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._12.addItem(spacerItem4)
        self.verticalLayout_2.addLayout(self._12)
        self._15 = QtGui.QHBoxLayout()
        self._15.setObjectName(_fromUtf8("_15"))
        self.TextLabel2_2_2_2_2_9 = QtGui.QLabel(self.groupBox_11)
        self.TextLabel2_2_2_2_2_9.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_9"))
        self._15.addWidget(self.TextLabel2_2_2_2_2_9)
        self.whitespaceForegroundButton = QtGui.QPushButton(self.groupBox_11)
        self.whitespaceForegroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.whitespaceForegroundButton.setText(_fromUtf8(""))
        self.whitespaceForegroundButton.setObjectName(_fromUtf8("whitespaceForegroundButton"))
        self._15.addWidget(self.whitespaceForegroundButton)
        self.TextLabel2_2_2_2_2_10 = QtGui.QLabel(self.groupBox_11)
        self.TextLabel2_2_2_2_2_10.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_10"))
        self._15.addWidget(self.TextLabel2_2_2_2_2_10)
        self.whitespaceBackgroundButton = QtGui.QPushButton(self.groupBox_11)
        self.whitespaceBackgroundButton.setMinimumSize(QtCore.QSize(100, 0))
        self.whitespaceBackgroundButton.setText(_fromUtf8(""))
        self.whitespaceBackgroundButton.setObjectName(_fromUtf8("whitespaceBackgroundButton"))
        self._15.addWidget(self.whitespaceBackgroundButton)
        self.verticalLayout_2.addLayout(self._15)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.groupBox_10 = QtGui.QGroupBox(EditorStylesPage)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self._14 = QtGui.QGridLayout(self.groupBox_10)
        self._14.setObjectName(_fromUtf8("_14"))
        self.miniMenuCheckBox = QtGui.QCheckBox(self.groupBox_10)
        self.miniMenuCheckBox.setObjectName(_fromUtf8("miniMenuCheckBox"))
        self._14.addWidget(self.miniMenuCheckBox, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_10)
        spacerItem5 = QtGui.QSpacerItem(558, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)

        self.retranslateUi(EditorStylesPage)
        QtCore.QObject.connect(self.edgeLineColumnSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.edgeLineColumnLCD.display)
        QtCore.QObject.connect(self.editAreaOverrideCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editAreaForegroundButton.setEnabled)
        QtCore.QObject.connect(self.editAreaOverrideCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.editAreaBackgroundButton.setEnabled)
        QtCore.QObject.connect(self.editAreaOverrideCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.TextLabel2_2_2_2_2_12.setEnabled)
        QtCore.QObject.connect(self.editAreaOverrideCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.TextLabel2_2_2_2_2_11.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(EditorStylesPage)
        EditorStylesPage.setTabOrder(self.editAreaOverrideCheckBox, self.editAreaForegroundButton)
        EditorStylesPage.setTabOrder(self.editAreaForegroundButton, self.editAreaBackgroundButton)
        EditorStylesPage.setTabOrder(self.editAreaBackgroundButton, self.defaultFontButton)
        EditorStylesPage.setTabOrder(self.defaultFontButton, self.monospacedFontButton)
        EditorStylesPage.setTabOrder(self.monospacedFontButton, self.monospacedCheckBox)
        EditorStylesPage.setTabOrder(self.monospacedCheckBox, self.linenoCheckBox)
        EditorStylesPage.setTabOrder(self.linenoCheckBox, self.foldingCheckBox)
        EditorStylesPage.setTabOrder(self.foldingCheckBox, self.unifiedMarginsCheckBox)
        EditorStylesPage.setTabOrder(self.unifiedMarginsCheckBox, self.foldingStyleComboBox)
        EditorStylesPage.setTabOrder(self.foldingStyleComboBox, self.marginsForegroundButton)
        EditorStylesPage.setTabOrder(self.marginsForegroundButton, self.marginsBackgroundButton)
        EditorStylesPage.setTabOrder(self.marginsBackgroundButton, self.foldmarginBackgroundButton)
        EditorStylesPage.setTabOrder(self.foldmarginBackgroundButton, self.linenumbersFontButton)
        EditorStylesPage.setTabOrder(self.linenumbersFontButton, self.customSelColourCheckBox)
        EditorStylesPage.setTabOrder(self.customSelColourCheckBox, self.colourizeSelTextCheckBox)
        EditorStylesPage.setTabOrder(self.colourizeSelTextCheckBox, self.extentSelEolCheckBox)
        EditorStylesPage.setTabOrder(self.extentSelEolCheckBox, self.selectionForegroundButton)
        EditorStylesPage.setTabOrder(self.selectionForegroundButton, self.selectionBackgroundButton)
        EditorStylesPage.setTabOrder(self.selectionBackgroundButton, self.caretlineVisibleCheckBox)
        EditorStylesPage.setTabOrder(self.caretlineVisibleCheckBox, self.caretWidthSpinBox)
        EditorStylesPage.setTabOrder(self.caretWidthSpinBox, self.caretForegroundButton)
        EditorStylesPage.setTabOrder(self.caretForegroundButton, self.caretlineBackgroundButton)
        EditorStylesPage.setTabOrder(self.caretlineBackgroundButton, self.currentLineMarkerButton)
        EditorStylesPage.setTabOrder(self.currentLineMarkerButton, self.errorMarkerButton)
        EditorStylesPage.setTabOrder(self.errorMarkerButton, self.bracehighlightingCheckBox)
        EditorStylesPage.setTabOrder(self.bracehighlightingCheckBox, self.matchingBracesButton)
        EditorStylesPage.setTabOrder(self.matchingBracesButton, self.matchingBracesBackButton)
        EditorStylesPage.setTabOrder(self.matchingBracesBackButton, self.nonmatchingBracesButton)
        EditorStylesPage.setTabOrder(self.nonmatchingBracesButton, self.nonmatchingBracesBackButton)
        EditorStylesPage.setTabOrder(self.nonmatchingBracesBackButton, self.eolCheckBox)
        EditorStylesPage.setTabOrder(self.eolCheckBox, self.wrapLongLinesCheckBox)
        EditorStylesPage.setTabOrder(self.wrapLongLinesCheckBox, self.edgeModeCombo)
        EditorStylesPage.setTabOrder(self.edgeModeCombo, self.edgeLineColumnSlider)
        EditorStylesPage.setTabOrder(self.edgeLineColumnSlider, self.edgeBackgroundColorButton)
        EditorStylesPage.setTabOrder(self.edgeBackgroundColorButton, self.whitespaceCheckBox)
        EditorStylesPage.setTabOrder(self.whitespaceCheckBox, self.whitespaceSizeSpinBox)
        EditorStylesPage.setTabOrder(self.whitespaceSizeSpinBox, self.whitespaceForegroundButton)
        EditorStylesPage.setTabOrder(self.whitespaceForegroundButton, self.whitespaceBackgroundButton)
        EditorStylesPage.setTabOrder(self.whitespaceBackgroundButton, self.miniMenuCheckBox)

    def retranslateUi(self, EditorStylesPage):
        self.headerLabel.setText(_translate("EditorStylesPage", "<b>Configure editor styles</b>", None))
        self.label_3.setText(_translate("EditorStylesPage", "<b>Note:</b> Fonts and colors of the syntax highlighters have to be configured on the syntax highlighter styles page.", None))
        self.groupBox_12.setTitle(_translate("EditorStylesPage", "Colours", None))
        self.editAreaOverrideCheckBox.setToolTip(_translate("EditorStylesPage", "Select to set the colour of the edit area different to the default style", None))
        self.editAreaOverrideCheckBox.setText(_translate("EditorStylesPage", "Override edit area colours", None))
        self.TextLabel2_2_2_2_2_12.setText(_translate("EditorStylesPage", "Edit area foreground:", None))
        self.editAreaForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the edit area.", None))
        self.TextLabel2_2_2_2_2_11.setText(_translate("EditorStylesPage", "Edit area background:", None))
        self.editAreaBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the edit area.", None))
        self.groupBox_5.setTitle(_translate("EditorStylesPage", "Fonts", None))
        self.monospacedCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether the monospaced font should be used as default", None))
        self.monospacedCheckBox.setText(_translate("EditorStylesPage", "Use monospaced as default", None))
        self.defaultFontSample.setText(_translate("EditorStylesPage", "Default Text", None))
        self.defaultFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the default font for the editor\'s text", None))
        self.defaultFontButton.setText(_translate("EditorStylesPage", "Default Text Font", None))
        self.monospacedFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the font to be used as the monospaced font", None))
        self.monospacedFontButton.setText(_translate("EditorStylesPage", "Monospaced Font", None))
        self.monospacedFontSample.setText(_translate("EditorStylesPage", "Monospaced Text", None))
        self.groupBox.setTitle(_translate("EditorStylesPage", "Margins", None))
        self.linenoCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether line numbers margin should be shown.", None))
        self.linenoCheckBox.setText(_translate("EditorStylesPage", "Show Line Numbers Margin", None))
        self.foldingCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether the fold margin should be shown.", None))
        self.foldingCheckBox.setText(_translate("EditorStylesPage", "Show Fold Margin", None))
        self.unifiedMarginsCheckBox.setToolTip(_translate("EditorStylesPage", "Select to show unified margins (like eric4 < 4.3.0)", None))
        self.unifiedMarginsCheckBox.setText(_translate("EditorStylesPage", "Show unified margins", None))
        self.TextLabel1_4_2_2.setText(_translate("EditorStylesPage", "Folding style:", None))
        self.foldingStyleComboBox.setToolTip(_translate("EditorStylesPage", "Select the folding style to be used in the folding margin", None))
        self.foldingStyleComboBox.setWhatsThis(_translate("EditorStylesPage", "<b>Folding style</b>\n"
"<p>Select the desired folding style to be used in the folding margin.</p>\n"
"<p>The available styles are:\n"
"<ul>\n"
"<li>Plain - simple plus and minus symbols</li>\n"
"<li>Circled - circled plus and minus symbols</li>\n"
"<li>Boxed - boxed plus and minus symbols</li>\n"
"<li>Circled Tree - circled plus and minus symbols and flattened tree with rounded corners</li>\n"
"<li>Boxed Tree - boxed plus and minus symbols and flattened tree with rectangled corners</li>\n"
"</ul>\n"
"</p>", None))
        self.foldingStyleComboBox.setItemText(0, _translate("EditorStylesPage", "Plain", None))
        self.foldingStyleComboBox.setItemText(1, _translate("EditorStylesPage", "Circled", None))
        self.foldingStyleComboBox.setItemText(2, _translate("EditorStylesPage", "Boxed", None))
        self.foldingStyleComboBox.setItemText(3, _translate("EditorStylesPage", "Circled Tree", None))
        self.foldingStyleComboBox.setItemText(4, _translate("EditorStylesPage", "Boxed Tree", None))
        self.TextLabel2_2_2_2_2_6.setText(_translate("EditorStylesPage", "Margins foreground:", None))
        self.marginsForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the margins", None))
        self.TextLabel2_2_2_2_2_7.setText(_translate("EditorStylesPage", "Margins background:", None))
        self.marginsBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the margins", None))
        self.TextLabel2_2_2_2_2_8.setText(_translate("EditorStylesPage", "Foldmargin background:", None))
        self.foldmarginBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the foldmargin", None))
        self.linenumbersFontButton.setToolTip(_translate("EditorStylesPage", "Press to select the font for the editor line numbers", None))
        self.linenumbersFontButton.setText(_translate("EditorStylesPage", "Line Numbers Font", None))
        self.marginsFontSample.setText(_translate("EditorStylesPage", "2345", None))
        self.groupBox_3.setTitle(_translate("EditorStylesPage", "Selection", None))
        self.customSelColourCheckBox.setToolTip(_translate("EditorStylesPage", "Select to use custom selection colours", None))
        self.customSelColourCheckBox.setWhatsThis(_translate("EditorStylesPage", "<b>Use custom selection colours</b><p>Select this entry in order to use custom selection colours in the editor and shell windows. The colours for the selection foreground and background are defined on the colours page.</p>", None))
        self.customSelColourCheckBox.setText(_translate("EditorStylesPage", "Use custom selection colours", None))
        self.colourizeSelTextCheckBox.setToolTip(_translate("EditorStylesPage", "Select, if selected text should be colourized by the lexer.", None))
        self.colourizeSelTextCheckBox.setText(_translate("EditorStylesPage", "Colourize selected text", None))
        self.extentSelEolCheckBox.setToolTip(_translate("EditorStylesPage", "Select to extend selection to end of line", None))
        self.extentSelEolCheckBox.setText(_translate("EditorStylesPage", "Extend selection to end of line", None))
        self.TextLabel2_2_2_2_2_4.setText(_translate("EditorStylesPage", "Selection foreground:", None))
        self.selectionForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for the selection.", None))
        self.TextLabel2_2_2_2_2_5.setText(_translate("EditorStylesPage", "Selection background:", None))
        self.selectionBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the selection.", None))
        self.groupBox_4.setTitle(_translate("EditorStylesPage", "Caret", None))
        self.caretlineVisibleCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether the caretline should be highlighted", None))
        self.caretlineVisibleCheckBox.setText(_translate("EditorStylesPage", "Caretline visible", None))
        self.textLabel1_7.setText(_translate("EditorStylesPage", "Caret width:", None))
        self.caretWidthSpinBox.setToolTip(_translate("EditorStylesPage", "Select caret width (1, 2 or 3 pixels)", None))
        self.TextLabel2_2_2_2_2_2.setText(_translate("EditorStylesPage", "Caret foreground:", None))
        self.caretForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the caret.", None))
        self.TextLabel2_2_2_2_2_3.setText(_translate("EditorStylesPage", "Caretline background:", None))
        self.caretlineBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for the line containing the caret.", None))
        self.groupBox_2.setTitle(_translate("EditorStylesPage", "Debugging Line Markers", None))
        self.TextLabel3_2_2.setText(_translate("EditorStylesPage", "Current line marker:", None))
        self.currentLineMarkerButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the current line marker.", None))
        self.TextLabel4_2_2.setText(_translate("EditorStylesPage", "Error line marker:", None))
        self.errorMarkerButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the error line marker.", None))
        self.groupBox_6.setTitle(_translate("EditorStylesPage", "Braces", None))
        self.bracehighlightingCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether matching and bad braces shall be highlighted.", None))
        self.bracehighlightingCheckBox.setText(_translate("EditorStylesPage", "Highlight braces", None))
        self.TextLabel1_3_2.setText(_translate("EditorStylesPage", "Matched braces:", None))
        self.matchingBracesButton.setToolTip(_translate("EditorStylesPage", "Select the colour for highlighting matching braces.", None))
        self.TextLabel1_3_2_2.setText(_translate("EditorStylesPage", "Matched braces background:", None))
        self.matchingBracesBackButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for highlighting matching braces.", None))
        self.TextLabel2_2_2.setText(_translate("EditorStylesPage", "Unmatched brace:", None))
        self.nonmatchingBracesButton.setToolTip(_translate("EditorStylesPage", "Select the colour for  highlighting nonmatching braces.", None))
        self.TextLabel2_2_2_3.setText(_translate("EditorStylesPage", "Unmatched brace background:", None))
        self.nonmatchingBracesBackButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for  highlighting nonmatching braces.", None))
        self.groupBox_7.setTitle(_translate("EditorStylesPage", "End of Line", None))
        self.eolCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether end of line shall be shown", None))
        self.eolCheckBox.setText(_translate("EditorStylesPage", "Show End of Line", None))
        self.wrapLongLinesCheckBox.setToolTip(_translate("EditorStylesPage", "Select, whether long lines should be wrapped", None))
        self.wrapLongLinesCheckBox.setText(_translate("EditorStylesPage", "Wrap long lines", None))
        self.groupBox_9.setTitle(_translate("EditorStylesPage", "Edge Mode", None))
        self.edgeBackgroundColorButton.setToolTip(_translate("EditorStylesPage", "Select the colour for the edge marker.", None))
        self.TextLabel13_3_2_2.setText(_translate("EditorStylesPage", "Background colour:", None))
        self.edgeLineColumnSlider.setToolTip(_translate("EditorStylesPage", "Move to set the edge column.", None))
        self.edgeLineColumnLCD.setToolTip(_translate("EditorStylesPage", "Displays the selected tab width.", None))
        self.TextLabel13_3_2.setText(_translate("EditorStylesPage", "Column number:", None))
        self.textLabel1_14.setText(_translate("EditorStylesPage", "Mode:", None))
        self.edgeModeCombo.setItemText(0, _translate("EditorStylesPage", "Disabled", None))
        self.edgeModeCombo.setItemText(1, _translate("EditorStylesPage", "Draw Line", None))
        self.edgeModeCombo.setItemText(2, _translate("EditorStylesPage", "Change Background Colour", None))
        self.groupBox_11.setTitle(_translate("EditorStylesPage", "Whitespace", None))
        self.whitespaceCheckBox.setToolTip(_translate("EditorStylesPage", "Select whether whitspace characters shall be shown", None))
        self.whitespaceCheckBox.setText(_translate("EditorStylesPage", "Show Whitespace", None))
        self.textLabel1_8.setText(_translate("EditorStylesPage", "Whitespace size:", None))
        self.whitespaceSizeSpinBox.setToolTip(_translate("EditorStylesPage", "Select the size of the dots used to represent visible whitespace", None))
        self.TextLabel2_2_2_2_2_9.setText(_translate("EditorStylesPage", "Whitespace foreground:", None))
        self.whitespaceForegroundButton.setToolTip(_translate("EditorStylesPage", "Select the foreground colour for visible whitespace", None))
        self.TextLabel2_2_2_2_2_10.setText(_translate("EditorStylesPage", "Whitespace background:", None))
        self.whitespaceBackgroundButton.setToolTip(_translate("EditorStylesPage", "Select the background colour for visible whitespace", None))
        self.groupBox_10.setTitle(_translate("EditorStylesPage", "Various", None))
        self.miniMenuCheckBox.setToolTip(_translate("EditorStylesPage", "Select to show a minimalistic context menu", None))
        self.miniMenuCheckBox.setText(_translate("EditorStylesPage", "Show minimal context menu", None))

