# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\EditorSpellCheckingPage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EditorSpellCheckingPage(object):
    def setupUi(self, EditorSpellCheckingPage):
        EditorSpellCheckingPage.setObjectName(_fromUtf8("EditorSpellCheckingPage"))
        EditorSpellCheckingPage.resize(576, 666)
        self.verticalLayout_4 = QtGui.QVBoxLayout(EditorSpellCheckingPage)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.headerLabel = QtGui.QLabel(EditorSpellCheckingPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_4.addWidget(self.headerLabel)
        self.line3 = QtGui.QFrame(EditorSpellCheckingPage)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setFrameShape(QtGui.QFrame.HLine)
        self.line3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line3.setObjectName(_fromUtf8("line3"))
        self.verticalLayout_4.addWidget(self.line3)
        self.errorLabel = QtGui.QLabel(EditorSpellCheckingPage)
        self.errorLabel.setObjectName(_fromUtf8("errorLabel"))
        self.verticalLayout_4.addWidget(self.errorLabel)
        self.spellingFrame = QtGui.QFrame(EditorSpellCheckingPage)
        self.spellingFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.spellingFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.spellingFrame.setObjectName(_fromUtf8("spellingFrame"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.spellingFrame)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.checkingEnabledCheckBox = QtGui.QCheckBox(self.spellingFrame)
        self.checkingEnabledCheckBox.setObjectName(_fromUtf8("checkingEnabledCheckBox"))
        self.verticalLayout_3.addWidget(self.checkingEnabledCheckBox)
        self.groupBox_3 = QtGui.QGroupBox(self.spellingFrame)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.defaultLanguageCombo = QtGui.QComboBox(self.groupBox_3)
        self.defaultLanguageCombo.setObjectName(_fromUtf8("defaultLanguageCombo"))
        self.gridLayout_3.addWidget(self.defaultLanguageCombo, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(353, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.spellingFrame)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stringsOnlyCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.stringsOnlyCheckBox.setObjectName(_fromUtf8("stringsOnlyCheckBox"))
        self.verticalLayout.addWidget(self.stringsOnlyCheckBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.minimumWordSizeSlider = QtGui.QSlider(self.groupBox_4)
        self.minimumWordSizeSlider.setMinimum(1)
        self.minimumWordSizeSlider.setMaximum(10)
        self.minimumWordSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.minimumWordSizeSlider.setTickPosition(QtGui.QSlider.NoTicks)
        self.minimumWordSizeSlider.setTickInterval(1)
        self.minimumWordSizeSlider.setObjectName(_fromUtf8("minimumWordSizeSlider"))
        self.horizontalLayout.addWidget(self.minimumWordSizeSlider)
        self.lCDNumber = QtGui.QLCDNumber(self.groupBox_4)
        self.lCDNumber.setDigitCount(2)
        self.lCDNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lCDNumber.setProperty("intValue", 1)
        self.lCDNumber.setObjectName(_fromUtf8("lCDNumber"))
        self.horizontalLayout.addWidget(self.lCDNumber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_2 = QtGui.QGroupBox(self.spellingFrame)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.TextLabel2_2_2_2_2_2 = QtGui.QLabel(self.groupBox_2)
        self.TextLabel2_2_2_2_2_2.setObjectName(_fromUtf8("TextLabel2_2_2_2_2_2"))
        self.gridLayout_2.addWidget(self.TextLabel2_2_2_2_2_2, 0, 0, 1, 1)
        self.spellingMarkerButton = QtGui.QPushButton(self.groupBox_2)
        self.spellingMarkerButton.setMinimumSize(QtCore.QSize(100, 0))
        self.spellingMarkerButton.setText(_fromUtf8(""))
        self.spellingMarkerButton.setObjectName(_fromUtf8("spellingMarkerButton"))
        self.gridLayout_2.addWidget(self.spellingMarkerButton, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(348, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.spellingFrame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.pwlEdit = QtGui.QLineEdit(self.groupBox)
        self.pwlEdit.setObjectName(_fromUtf8("pwlEdit"))
        self.gridLayout.addWidget(self.pwlEdit, 0, 1, 1, 1)
        self.pwlButton = QtGui.QPushButton(self.groupBox)
        self.pwlButton.setObjectName(_fromUtf8("pwlButton"))
        self.gridLayout.addWidget(self.pwlButton, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.pelEdit = QtGui.QLineEdit(self.groupBox)
        self.pelEdit.setObjectName(_fromUtf8("pelEdit"))
        self.gridLayout.addWidget(self.pelEdit, 1, 1, 1, 1)
        self.pelButton = QtGui.QPushButton(self.groupBox)
        self.pelButton.setObjectName(_fromUtf8("pelButton"))
        self.gridLayout.addWidget(self.pelButton, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 3)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_5 = QtGui.QGroupBox(self.spellingFrame)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.enabledCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.enabledCheckBox.setObjectName(_fromUtf8("enabledCheckBox"))
        self.verticalLayout_2.addWidget(self.enabledCheckBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.chunkSizeSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.chunkSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.chunkSizeSpinBox.setMinimum(10)
        self.chunkSizeSpinBox.setMaximum(999)
        self.chunkSizeSpinBox.setObjectName(_fromUtf8("chunkSizeSpinBox"))
        self.horizontalLayout_3.addWidget(self.chunkSizeSpinBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_4.addWidget(self.spellingFrame)
        spacerItem3 = QtGui.QSpacerItem(558, 231, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)

        self.retranslateUi(EditorSpellCheckingPage)
        QtCore.QObject.connect(self.minimumWordSizeSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.lCDNumber.display)
        QtCore.QMetaObject.connectSlotsByName(EditorSpellCheckingPage)
        EditorSpellCheckingPage.setTabOrder(self.checkingEnabledCheckBox, self.defaultLanguageCombo)
        EditorSpellCheckingPage.setTabOrder(self.defaultLanguageCombo, self.stringsOnlyCheckBox)
        EditorSpellCheckingPage.setTabOrder(self.stringsOnlyCheckBox, self.minimumWordSizeSlider)
        EditorSpellCheckingPage.setTabOrder(self.minimumWordSizeSlider, self.spellingMarkerButton)
        EditorSpellCheckingPage.setTabOrder(self.spellingMarkerButton, self.pwlEdit)
        EditorSpellCheckingPage.setTabOrder(self.pwlEdit, self.pwlButton)
        EditorSpellCheckingPage.setTabOrder(self.pwlButton, self.pelEdit)
        EditorSpellCheckingPage.setTabOrder(self.pelEdit, self.pelButton)
        EditorSpellCheckingPage.setTabOrder(self.pelButton, self.enabledCheckBox)
        EditorSpellCheckingPage.setTabOrder(self.enabledCheckBox, self.chunkSizeSpinBox)

    def retranslateUi(self, EditorSpellCheckingPage):
        self.headerLabel.setText(_translate("EditorSpellCheckingPage", "<b>Configure editor spell checking options</b>", None))
        self.errorLabel.setText(_translate("EditorSpellCheckingPage", "<font color=\"#FF0000\">Spell checking with PyEnchant is not available.</font>", None))
        self.checkingEnabledCheckBox.setToolTip(_translate("EditorSpellCheckingPage", "Select to enable spell checking", None))
        self.checkingEnabledCheckBox.setText(_translate("EditorSpellCheckingPage", "Spell checking enabled", None))
        self.groupBox_3.setTitle(_translate("EditorSpellCheckingPage", "Defaults", None))
        self.label_2.setText(_translate("EditorSpellCheckingPage", "Default language:", None))
        self.defaultLanguageCombo.setToolTip(_translate("EditorSpellCheckingPage", "Select the default language", None))
        self.groupBox_4.setTitle(_translate("EditorSpellCheckingPage", "Spell checking options", None))
        self.stringsOnlyCheckBox.setToolTip(_translate("EditorSpellCheckingPage", "Select to check strings only", None))
        self.stringsOnlyCheckBox.setText(_translate("EditorSpellCheckingPage", "Spell check strings only", None))
        self.label.setText(_translate("EditorSpellCheckingPage", "Minimum word size:", None))
        self.minimumWordSizeSlider.setToolTip(_translate("EditorSpellCheckingPage", "Move to set the minimum size of words to be checked", None))
        self.lCDNumber.setToolTip(_translate("EditorSpellCheckingPage", "Displays the minimum size of words to be checked", None))
        self.groupBox_2.setTitle(_translate("EditorSpellCheckingPage", "Colours", None))
        self.TextLabel2_2_2_2_2_2.setText(_translate("EditorSpellCheckingPage", "Marker Colour:", None))
        self.spellingMarkerButton.setToolTip(_translate("EditorSpellCheckingPage", "Select the colour for the spelling markers.", None))
        self.groupBox.setTitle(_translate("EditorSpellCheckingPage", "Personal lists", None))
        self.label_4.setText(_translate("EditorSpellCheckingPage", "Personal word list file:", None))
        self.pwlEdit.setToolTip(_translate("EditorSpellCheckingPage", "Enter the filename of the personal word list", None))
        self.pwlButton.setToolTip(_translate("EditorSpellCheckingPage", "Select the personal word list file via a file selection dialog", None))
        self.pwlButton.setText(_translate("EditorSpellCheckingPage", "...", None))
        self.label_5.setText(_translate("EditorSpellCheckingPage", "Personal exclude list file:", None))
        self.pelEdit.setToolTip(_translate("EditorSpellCheckingPage", "Enter the filename of the personal exclude list", None))
        self.pelButton.setToolTip(_translate("EditorSpellCheckingPage", "Select the personal exclude list file via a file selection dialog", None))
        self.pelButton.setText(_translate("EditorSpellCheckingPage", "...", None))
        self.label_6.setText(_translate("EditorSpellCheckingPage", "<b>Note:</b> leave these entries empty to use the default", None))
        self.label_7.setText(_translate("EditorSpellCheckingPage", "<b>Note:</b> valid for all newly opened editors", None))
        self.groupBox_5.setTitle(_translate("EditorSpellCheckingPage", "Automatic spell checking", None))
        self.enabledCheckBox.setToolTip(_translate("EditorSpellCheckingPage", "Select to enable spellchecking", None))
        self.enabledCheckBox.setText(_translate("EditorSpellCheckingPage", "Automatic spell checking enabled", None))
        self.label_3.setText(_translate("EditorSpellCheckingPage", "Amount of lines to autocheck at once:", None))
        self.chunkSizeSpinBox.setToolTip(_translate("EditorSpellCheckingPage", "Enter the number of lines to check per go. Higher values increase checking speed but decrease GUI responsivenes", None))

