# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\HelpAppearancePage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HelpAppearancePage(object):
    def setupUi(self, HelpAppearancePage):
        HelpAppearancePage.setObjectName(_fromUtf8("HelpAppearancePage"))
        HelpAppearancePage.resize(497, 440)
        self.verticalLayout_3 = QtGui.QVBoxLayout(HelpAppearancePage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.headerLabel = QtGui.QLabel(HelpAppearancePage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line17 = QtGui.QFrame(HelpAppearancePage)
        self.line17.setFrameShape(QtGui.QFrame.HLine)
        self.line17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line17.setFrameShape(QtGui.QFrame.HLine)
        self.line17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line17.setObjectName(_fromUtf8("line17"))
        self.verticalLayout_3.addWidget(self.line17)
        self.groupBox_5 = QtGui.QGroupBox(HelpAppearancePage)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.standardFontButton = QtGui.QPushButton(self.groupBox_5)
        self.standardFontButton.setObjectName(_fromUtf8("standardFontButton"))
        self.gridLayout.addWidget(self.standardFontButton, 0, 0, 1, 1)
        self.standardFontSample = QtGui.QLineEdit(self.groupBox_5)
        self.standardFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.standardFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.standardFontSample.setReadOnly(True)
        self.standardFontSample.setObjectName(_fromUtf8("standardFontSample"))
        self.gridLayout.addWidget(self.standardFontSample, 0, 1, 1, 1)
        self.fixedFontButton = QtGui.QPushButton(self.groupBox_5)
        self.fixedFontButton.setObjectName(_fromUtf8("fixedFontButton"))
        self.gridLayout.addWidget(self.fixedFontButton, 1, 0, 1, 1)
        self.fixedFontSample = QtGui.QLineEdit(self.groupBox_5)
        self.fixedFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fixedFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.fixedFontSample.setReadOnly(True)
        self.fixedFontSample.setObjectName(_fromUtf8("fixedFontSample"))
        self.gridLayout.addWidget(self.fixedFontSample, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_3 = QtGui.QGroupBox(HelpAppearancePage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.textLabel1_3 = QtGui.QLabel(self.groupBox_3)
        self.textLabel1_3.setObjectName(_fromUtf8("textLabel1_3"))
        self.gridLayout_2.addWidget(self.textLabel1_3, 0, 0, 1, 1)
        self.secureURLsColourButton = QtGui.QPushButton(self.groupBox_3)
        self.secureURLsColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.secureURLsColourButton.setText(_fromUtf8(""))
        self.secureURLsColourButton.setObjectName(_fromUtf8("secureURLsColourButton"))
        self.gridLayout_2.addWidget(self.secureURLsColourButton, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(141, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(HelpAppearancePage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.autoLoadImagesCheckBox = QtGui.QCheckBox(self.groupBox)
        self.autoLoadImagesCheckBox.setObjectName(_fromUtf8("autoLoadImagesCheckBox"))
        self.verticalLayout.addWidget(self.autoLoadImagesCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(HelpAppearancePage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.styleSheetEdit = QtGui.QLineEdit(self.groupBox_2)
        self.styleSheetEdit.setObjectName(_fromUtf8("styleSheetEdit"))
        self.horizontalLayout.addWidget(self.styleSheetEdit)
        self.styleSheetButton = QtGui.QPushButton(self.groupBox_2)
        self.styleSheetButton.setObjectName(_fromUtf8("styleSheetButton"))
        self.horizontalLayout.addWidget(self.styleSheetButton)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.separatorLine = QtGui.QFrame(HelpAppearancePage)
        self.separatorLine.setFrameShape(QtGui.QFrame.HLine)
        self.separatorLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.separatorLine.setFrameShape(QtGui.QFrame.HLine)
        self.separatorLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.separatorLine.setObjectName(_fromUtf8("separatorLine"))
        self.verticalLayout_3.addWidget(self.separatorLine)
        self.nextStartupNoteLabel = QtGui.QLabel(HelpAppearancePage)
        self.nextStartupNoteLabel.setObjectName(_fromUtf8("nextStartupNoteLabel"))
        self.verticalLayout_3.addWidget(self.nextStartupNoteLabel)
        self.tabsGroupBox = QtGui.QGroupBox(HelpAppearancePage)
        self.tabsGroupBox.setObjectName(_fromUtf8("tabsGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabsGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabsCloseButtonCheckBox = QtGui.QCheckBox(self.tabsGroupBox)
        self.tabsCloseButtonCheckBox.setObjectName(_fromUtf8("tabsCloseButtonCheckBox"))
        self.verticalLayout_2.addWidget(self.tabsCloseButtonCheckBox)
        self.verticalLayout_3.addWidget(self.tabsGroupBox)
        spacerItem1 = QtGui.QSpacerItem(479, 121, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)

        self.retranslateUi(HelpAppearancePage)
        QtCore.QMetaObject.connectSlotsByName(HelpAppearancePage)
        HelpAppearancePage.setTabOrder(self.standardFontButton, self.fixedFontButton)
        HelpAppearancePage.setTabOrder(self.fixedFontButton, self.secureURLsColourButton)
        HelpAppearancePage.setTabOrder(self.secureURLsColourButton, self.autoLoadImagesCheckBox)
        HelpAppearancePage.setTabOrder(self.autoLoadImagesCheckBox, self.styleSheetEdit)
        HelpAppearancePage.setTabOrder(self.styleSheetEdit, self.styleSheetButton)

    def retranslateUi(self, HelpAppearancePage):
        self.headerLabel.setText(_translate("HelpAppearancePage", "<b>Configure help viewer appearance</b>", None))
        self.groupBox_5.setTitle(_translate("HelpAppearancePage", "Fonts", None))
        self.standardFontButton.setToolTip(_translate("HelpAppearancePage", "Press to select the standard font", None))
        self.standardFontButton.setText(_translate("HelpAppearancePage", "Standard Font", None))
        self.standardFontSample.setText(_translate("HelpAppearancePage", "Times 16", None))
        self.fixedFontButton.setToolTip(_translate("HelpAppearancePage", "Press to select the fixed-width font", None))
        self.fixedFontButton.setText(_translate("HelpAppearancePage", "Fixed-Width Font", None))
        self.fixedFontSample.setText(_translate("HelpAppearancePage", "Courier 13", None))
        self.groupBox_3.setTitle(_translate("HelpAppearancePage", "Colours", None))
        self.textLabel1_3.setText(_translate("HelpAppearancePage", "Background colour of secure URLs:", None))
        self.secureURLsColourButton.setToolTip(_translate("HelpAppearancePage", "Select the background colour for secure URLs.", None))
        self.groupBox.setTitle(_translate("HelpAppearancePage", "Images", None))
        self.autoLoadImagesCheckBox.setToolTip(_translate("HelpAppearancePage", "Select to load images", None))
        self.autoLoadImagesCheckBox.setText(_translate("HelpAppearancePage", "Load images", None))
        self.groupBox_2.setTitle(_translate("HelpAppearancePage", "Style Sheet", None))
        self.label.setText(_translate("HelpAppearancePage", "User Style Sheet:", None))
        self.styleSheetEdit.setToolTip(_translate("HelpAppearancePage", "Enter the file name of a user style sheet", None))
        self.styleSheetButton.setToolTip(_translate("HelpAppearancePage", "Select the user style sheet via a file selection dialog", None))
        self.styleSheetButton.setText(_translate("HelpAppearancePage", "...", None))
        self.nextStartupNoteLabel.setText(_translate("HelpAppearancePage", "<font color=\"#FF0000\"><b>Note:</b> All settings below are activated at the next startup of the application.</font>", None))
        self.tabsGroupBox.setTitle(_translate("HelpAppearancePage", "Tabs", None))
        self.tabsCloseButtonCheckBox.setText(_translate("HelpAppearancePage", "Show only one close button instead of one for each tab", None))

