# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\HelpWebBrowserPage.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HelpWebBrowserPage(object):
    def setupUi(self, HelpWebBrowserPage):
        HelpWebBrowserPage.setObjectName(_fromUtf8("HelpWebBrowserPage"))
        HelpWebBrowserPage.resize(613, 818)
        self.verticalLayout_2 = QtGui.QVBoxLayout(HelpWebBrowserPage)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.headerLabel = QtGui.QLabel(HelpWebBrowserPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_2.addWidget(self.headerLabel)
        self.line17 = QtGui.QFrame(HelpWebBrowserPage)
        self.line17.setFrameShape(QtGui.QFrame.HLine)
        self.line17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line17.setFrameShape(QtGui.QFrame.HLine)
        self.line17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line17.setObjectName(_fromUtf8("line17"))
        self.verticalLayout_2.addWidget(self.line17)
        self.singleHelpWindowCheckBox = QtGui.QCheckBox(HelpWebBrowserPage)
        self.singleHelpWindowCheckBox.setObjectName(_fromUtf8("singleHelpWindowCheckBox"))
        self.verticalLayout_2.addWidget(self.singleHelpWindowCheckBox)
        self.saveGeometryCheckBox = QtGui.QCheckBox(HelpWebBrowserPage)
        self.saveGeometryCheckBox.setObjectName(_fromUtf8("saveGeometryCheckBox"))
        self.verticalLayout_2.addWidget(self.saveGeometryCheckBox)
        self.webSuggestionsCheckBox = QtGui.QCheckBox(HelpWebBrowserPage)
        self.webSuggestionsCheckBox.setObjectName(_fromUtf8("webSuggestionsCheckBox"))
        self.verticalLayout_2.addWidget(self.webSuggestionsCheckBox)
        self.startupGroupBox = QtGui.QGroupBox(HelpWebBrowserPage)
        self.startupGroupBox.setObjectName(_fromUtf8("startupGroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.startupGroupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.startupGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.startupCombo = QtGui.QComboBox(self.startupGroupBox)
        self.startupCombo.setObjectName(_fromUtf8("startupCombo"))
        self.startupCombo.addItem(_fromUtf8(""))
        self.startupCombo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.startupCombo, 0, 1, 1, 3)
        self.label_2 = QtGui.QLabel(self.startupGroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.homePageEdit = QtGui.QLineEdit(self.startupGroupBox)
        self.homePageEdit.setObjectName(_fromUtf8("homePageEdit"))
        self.gridLayout_3.addWidget(self.homePageEdit, 1, 1, 1, 3)
        self.setCurrentPageButton = QtGui.QPushButton(self.startupGroupBox)
        self.setCurrentPageButton.setObjectName(_fromUtf8("setCurrentPageButton"))
        self.gridLayout_3.addWidget(self.setCurrentPageButton, 2, 1, 1, 1)
        self.defaultHomeButton = QtGui.QPushButton(self.startupGroupBox)
        self.defaultHomeButton.setObjectName(_fromUtf8("defaultHomeButton"))
        self.gridLayout_3.addWidget(self.defaultHomeButton, 2, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(160, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.startupGroupBox)
        self.groupBox_2 = QtGui.QGroupBox(HelpWebBrowserPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.defaultSchemeCombo = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultSchemeCombo.sizePolicy().hasHeightForWidth())
        self.defaultSchemeCombo.setSizePolicy(sizePolicy)
        self.defaultSchemeCombo.setEditable(False)
        self.defaultSchemeCombo.setObjectName(_fromUtf8("defaultSchemeCombo"))
        self.gridLayout_4.addWidget(self.defaultSchemeCombo, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.privacyGroup = QtGui.QGroupBox(HelpWebBrowserPage)
        self.privacyGroup.setObjectName(_fromUtf8("privacyGroup"))
        self.gridLayout = QtGui.QGridLayout(self.privacyGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.javaCheckBox = QtGui.QCheckBox(self.privacyGroup)
        self.javaCheckBox.setObjectName(_fromUtf8("javaCheckBox"))
        self.gridLayout.addWidget(self.javaCheckBox, 0, 0, 1, 1)
        self.javaScriptCheckBox = QtGui.QCheckBox(self.privacyGroup)
        self.javaScriptCheckBox.setObjectName(_fromUtf8("javaScriptCheckBox"))
        self.gridLayout.addWidget(self.javaScriptCheckBox, 1, 0, 1, 1)
        self.jsOpenWindowsCheckBox = QtGui.QCheckBox(self.privacyGroup)
        self.jsOpenWindowsCheckBox.setObjectName(_fromUtf8("jsOpenWindowsCheckBox"))
        self.gridLayout.addWidget(self.jsOpenWindowsCheckBox, 2, 0, 1, 1)
        self.jsClipboardCheckBox = QtGui.QCheckBox(self.privacyGroup)
        self.jsClipboardCheckBox.setObjectName(_fromUtf8("jsClipboardCheckBox"))
        self.gridLayout.addWidget(self.jsClipboardCheckBox, 2, 1, 1, 1)
        self.pluginsCheckBox = QtGui.QCheckBox(self.privacyGroup)
        self.pluginsCheckBox.setObjectName(_fromUtf8("pluginsCheckBox"))
        self.gridLayout.addWidget(self.pluginsCheckBox, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.privacyGroup)
        self.groupBox_3 = QtGui.QGroupBox(HelpWebBrowserPage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.savePasswordsCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.savePasswordsCheckBox.setObjectName(_fromUtf8("savePasswordsCheckBox"))
        self.gridLayout_5.addWidget(self.savePasswordsCheckBox, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(HelpWebBrowserPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.expireHistory = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expireHistory.sizePolicy().hasHeightForWidth())
        self.expireHistory.setSizePolicy(sizePolicy)
        self.expireHistory.setObjectName(_fromUtf8("expireHistory"))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.expireHistory.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.expireHistory)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.cacheGroup = QtGui.QGroupBox(HelpWebBrowserPage)
        self.cacheGroup.setObjectName(_fromUtf8("cacheGroup"))
        self.gridLayout_2 = QtGui.QGridLayout(self.cacheGroup)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.diskCacheCheckBox = QtGui.QCheckBox(self.cacheGroup)
        self.diskCacheCheckBox.setObjectName(_fromUtf8("diskCacheCheckBox"))
        self.gridLayout_2.addWidget(self.diskCacheCheckBox, 0, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.cacheGroup)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.cacheSizeSpinBox = QtGui.QSpinBox(self.cacheGroup)
        self.cacheSizeSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cacheSizeSpinBox.setMinimum(1)
        self.cacheSizeSpinBox.setMaximum(999)
        self.cacheSizeSpinBox.setObjectName(_fromUtf8("cacheSizeSpinBox"))
        self.gridLayout_2.addWidget(self.cacheSizeSpinBox, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(410, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.cacheGroup)
        self.groupBox_5 = QtGui.QGroupBox(HelpWebBrowserPage)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.languageCombo = QtGui.QComboBox(self.groupBox_5)
        self.languageCombo.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.languageCombo.setObjectName(_fromUtf8("languageCombo"))
        self.horizontalLayout_2.addWidget(self.languageCombo)
        spacerItem2 = QtGui.QSpacerItem(450, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.printGroup = QtGui.QGroupBox(HelpWebBrowserPage)
        self.printGroup.setObjectName(_fromUtf8("printGroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.printGroup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.printBackgroundsCheckBox = QtGui.QCheckBox(self.printGroup)
        self.printBackgroundsCheckBox.setObjectName(_fromUtf8("printBackgroundsCheckBox"))
        self.verticalLayout.addWidget(self.printBackgroundsCheckBox)
        self.verticalLayout_2.addWidget(self.printGroup)
        spacerItem3 = QtGui.QSpacerItem(479, 121, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)

        self.retranslateUi(HelpWebBrowserPage)
        QtCore.QMetaObject.connectSlotsByName(HelpWebBrowserPage)
        HelpWebBrowserPage.setTabOrder(self.singleHelpWindowCheckBox, self.saveGeometryCheckBox)
        HelpWebBrowserPage.setTabOrder(self.saveGeometryCheckBox, self.webSuggestionsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.webSuggestionsCheckBox, self.startupCombo)
        HelpWebBrowserPage.setTabOrder(self.startupCombo, self.homePageEdit)
        HelpWebBrowserPage.setTabOrder(self.homePageEdit, self.setCurrentPageButton)
        HelpWebBrowserPage.setTabOrder(self.setCurrentPageButton, self.defaultHomeButton)
        HelpWebBrowserPage.setTabOrder(self.defaultHomeButton, self.defaultSchemeCombo)
        HelpWebBrowserPage.setTabOrder(self.defaultSchemeCombo, self.javaCheckBox)
        HelpWebBrowserPage.setTabOrder(self.javaCheckBox, self.javaScriptCheckBox)
        HelpWebBrowserPage.setTabOrder(self.javaScriptCheckBox, self.jsOpenWindowsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.jsOpenWindowsCheckBox, self.jsClipboardCheckBox)
        HelpWebBrowserPage.setTabOrder(self.jsClipboardCheckBox, self.pluginsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.pluginsCheckBox, self.savePasswordsCheckBox)
        HelpWebBrowserPage.setTabOrder(self.savePasswordsCheckBox, self.expireHistory)
        HelpWebBrowserPage.setTabOrder(self.expireHistory, self.diskCacheCheckBox)
        HelpWebBrowserPage.setTabOrder(self.diskCacheCheckBox, self.cacheSizeSpinBox)
        HelpWebBrowserPage.setTabOrder(self.cacheSizeSpinBox, self.languageCombo)
        HelpWebBrowserPage.setTabOrder(self.languageCombo, self.printBackgroundsCheckBox)

    def retranslateUi(self, HelpWebBrowserPage):
        self.headerLabel.setText(_translate("HelpWebBrowserPage", "<b>Configure web browser</b>", None))
        self.singleHelpWindowCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to use a single help browser window only", None))
        self.singleHelpWindowCheckBox.setText(_translate("HelpWebBrowserPage", "Use single web browser window", None))
        self.saveGeometryCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to save the window size and position", None))
        self.saveGeometryCheckBox.setText(_translate("HelpWebBrowserPage", "Save size and position upon exit", None))
        self.webSuggestionsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable suggestions for web searches", None))
        self.webSuggestionsCheckBox.setText(_translate("HelpWebBrowserPage", "Show suggestions for web searches", None))
        self.startupGroupBox.setTitle(_translate("HelpWebBrowserPage", "Startup", None))
        self.label.setText(_translate("HelpWebBrowserPage", "On startup:", None))
        self.startupCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the startup behavior", None))
        self.startupCombo.setItemText(0, _translate("HelpWebBrowserPage", "Show home page", None))
        self.startupCombo.setItemText(1, _translate("HelpWebBrowserPage", "Show empty page", None))
        self.label_2.setText(_translate("HelpWebBrowserPage", "Home Page:", None))
        self.homePageEdit.setToolTip(_translate("HelpWebBrowserPage", "Enter the desired home page", None))
        self.setCurrentPageButton.setToolTip(_translate("HelpWebBrowserPage", "Press to set the current page as the home page", None))
        self.setCurrentPageButton.setText(_translate("HelpWebBrowserPage", "Set to current page", None))
        self.defaultHomeButton.setToolTip(_translate("HelpWebBrowserPage", "Press to set the default home page", None))
        self.defaultHomeButton.setText(_translate("HelpWebBrowserPage", "Set to default home page", None))
        self.groupBox_2.setTitle(_translate("HelpWebBrowserPage", "Scheme", None))
        self.label_3.setText(_translate("HelpWebBrowserPage", "Default Scheme:", None))
        self.defaultSchemeCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the default scheme", None))
        self.defaultSchemeCombo.setWhatsThis(_translate("HelpWebBrowserPage", "<b>Default Scheme</b><p>Select the default scheme. This scheme is prepended to URLs, that don\'t contain one.</p>", None))
        self.privacyGroup.setTitle(_translate("HelpWebBrowserPage", "Privacy", None))
        self.javaCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable Java", None))
        self.javaCheckBox.setText(_translate("HelpWebBrowserPage", "Enable Java", None))
        self.javaScriptCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable JavaScript", None))
        self.javaScriptCheckBox.setText(_translate("HelpWebBrowserPage", "Enable JavaScript", None))
        self.jsOpenWindowsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to allow JavaScript to open windows", None))
        self.jsOpenWindowsCheckBox.setText(_translate("HelpWebBrowserPage", "JavaScript can open windows", None))
        self.jsClipboardCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to allow JavaScript to access the clipboard", None))
        self.jsClipboardCheckBox.setText(_translate("HelpWebBrowserPage", "JavaScript can access clipboard", None))
        self.pluginsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to enable plugins in web pages", None))
        self.pluginsCheckBox.setText(_translate("HelpWebBrowserPage", "Enable Plugins", None))
        self.groupBox_3.setTitle(_translate("HelpWebBrowserPage", "Security", None))
        self.savePasswordsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to save passwords", None))
        self.savePasswordsCheckBox.setText(_translate("HelpWebBrowserPage", "Save passwords", None))
        self.groupBox.setTitle(_translate("HelpWebBrowserPage", "History", None))
        self.label_4.setText(_translate("HelpWebBrowserPage", "Remove history items:", None))
        self.expireHistory.setToolTip(_translate("HelpWebBrowserPage", "Select the period for expiration of history entries", None))
        self.expireHistory.setItemText(0, _translate("HelpWebBrowserPage", "After one day", None))
        self.expireHistory.setItemText(1, _translate("HelpWebBrowserPage", "After one week", None))
        self.expireHistory.setItemText(2, _translate("HelpWebBrowserPage", "After two weeks", None))
        self.expireHistory.setItemText(3, _translate("HelpWebBrowserPage", "After one month", None))
        self.expireHistory.setItemText(4, _translate("HelpWebBrowserPage", "After one year", None))
        self.expireHistory.setItemText(5, _translate("HelpWebBrowserPage", "Manually", None))
        self.expireHistory.setItemText(6, _translate("HelpWebBrowserPage", "On application exit", None))
        self.cacheGroup.setTitle(_translate("HelpWebBrowserPage", "Browser Cache", None))
        self.diskCacheCheckBox.setText(_translate("HelpWebBrowserPage", "Enable disk cache", None))
        self.label_7.setText(_translate("HelpWebBrowserPage", "Cache size:", None))
        self.cacheSizeSpinBox.setToolTip(_translate("HelpWebBrowserPage", "Enter the maximum size of the disk cache", None))
        self.cacheSizeSpinBox.setSuffix(_translate("HelpWebBrowserPage", " MB", None))
        self.groupBox_5.setTitle(_translate("HelpWebBrowserPage", "Web Search", None))
        self.label_5.setText(_translate("HelpWebBrowserPage", "Language:", None))
        self.languageCombo.setToolTip(_translate("HelpWebBrowserPage", "Select the language to be used for web searches", None))
        self.printGroup.setTitle(_translate("HelpWebBrowserPage", "Printing", None))
        self.printBackgroundsCheckBox.setToolTip(_translate("HelpWebBrowserPage", "Select to print background colours and images", None))
        self.printBackgroundsCheckBox.setText(_translate("HelpWebBrowserPage", "Print background colours and images", None))

