# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\InterfacePage.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InterfacePage(object):
    def setupUi(self, InterfacePage):
        InterfacePage.setObjectName(_fromUtf8("InterfacePage"))
        InterfacePage.resize(555, 1169)
        self.verticalLayout_3 = QtGui.QVBoxLayout(InterfacePage)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.headerLabel = QtGui.QLabel(InterfacePage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout_3.addWidget(self.headerLabel)
        self.line9 = QtGui.QFrame(InterfacePage)
        self.line9.setFrameShape(QtGui.QFrame.HLine)
        self.line9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9.setFrameShape(QtGui.QFrame.HLine)
        self.line9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9.setObjectName(_fromUtf8("line9"))
        self.verticalLayout_3.addWidget(self.line9)
        self.groupBox_4 = QtGui.QGroupBox(InterfacePage)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.uiBrowsersListFoldersFirstCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.uiBrowsersListFoldersFirstCheckBox.setObjectName(_fromUtf8("uiBrowsersListFoldersFirstCheckBox"))
        self.gridLayout_2.addWidget(self.uiBrowsersListFoldersFirstCheckBox, 0, 0, 1, 1)
        self.uiBrowsersHideNonPublicCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.uiBrowsersHideNonPublicCheckBox.setObjectName(_fromUtf8("uiBrowsersHideNonPublicCheckBox"))
        self.gridLayout_2.addWidget(self.uiBrowsersHideNonPublicCheckBox, 0, 1, 1, 1)
        self.uiBrowsersSortByOccurrenceCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.uiBrowsersSortByOccurrenceCheckBox.setObjectName(_fromUtf8("uiBrowsersSortByOccurrenceCheckBox"))
        self.gridLayout_2.addWidget(self.uiBrowsersSortByOccurrenceCheckBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.fileFiltersEdit = QtGui.QLineEdit(self.groupBox_4)
        self.fileFiltersEdit.setObjectName(_fromUtf8("fileFiltersEdit"))
        self.horizontalLayout_2.addWidget(self.fileFiltersEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(InterfacePage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lvAutoRaiseCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.lvAutoRaiseCheckBox.setObjectName(_fromUtf8("lvAutoRaiseCheckBox"))
        self.gridLayout_3.addWidget(self.lvAutoRaiseCheckBox, 0, 0, 1, 3)
        self.TextLabel3_2_2 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel3_2_2.setObjectName(_fromUtf8("TextLabel3_2_2"))
        self.gridLayout_3.addWidget(self.TextLabel3_2_2, 1, 0, 1, 1)
        self.stderrTextColourButton = QtGui.QPushButton(self.groupBox_3)
        self.stderrTextColourButton.setMinimumSize(QtCore.QSize(100, 0))
        self.stderrTextColourButton.setText(_fromUtf8(""))
        self.stderrTextColourButton.setObjectName(_fromUtf8("stderrTextColourButton"))
        self.gridLayout_3.addWidget(self.stderrTextColourButton, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(319, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.uiCaptionShowsFilenameGroupBox = QtGui.QGroupBox(InterfacePage)
        self.uiCaptionShowsFilenameGroupBox.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.uiCaptionShowsFilenameGroupBox.setCheckable(True)
        self.uiCaptionShowsFilenameGroupBox.setObjectName(_fromUtf8("uiCaptionShowsFilenameGroupBox"))
        self.hboxlayout = QtGui.QHBoxLayout(self.uiCaptionShowsFilenameGroupBox)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.label = QtGui.QLabel(self.uiCaptionShowsFilenameGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.hboxlayout.addWidget(self.label)
        self.filenameLengthSpinBox = QtGui.QSpinBox(self.uiCaptionShowsFilenameGroupBox)
        self.filenameLengthSpinBox.setMinimum(10)
        self.filenameLengthSpinBox.setMaximum(999)
        self.filenameLengthSpinBox.setSingleStep(10)
        self.filenameLengthSpinBox.setProperty("value", 100)
        self.filenameLengthSpinBox.setObjectName(_fromUtf8("filenameLengthSpinBox"))
        self.hboxlayout.addWidget(self.filenameLengthSpinBox)
        spacerItem1 = QtGui.QSpacerItem(31, 23, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.uiCaptionShowsFilenameGroupBox)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.label_2 = QtGui.QLabel(InterfacePage)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.styleComboBox = QtGui.QComboBox(InterfacePage)
        self.styleComboBox.setObjectName(_fromUtf8("styleComboBox"))
        self.gridlayout.addWidget(self.styleComboBox, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(InterfacePage)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridlayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.styleSheetEdit = QtGui.QLineEdit(InterfacePage)
        self.styleSheetEdit.setObjectName(_fromUtf8("styleSheetEdit"))
        self.gridlayout.addWidget(self.styleSheetEdit, 1, 1, 1, 1)
        self.styleSheetButton = QtGui.QPushButton(InterfacePage)
        self.styleSheetButton.setObjectName(_fromUtf8("styleSheetButton"))
        self.gridlayout.addWidget(self.styleSheetButton, 1, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridlayout)
        self.groupBox = QtGui.QGroupBox(InterfacePage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.tlTopButton = QtGui.QRadioButton(self.groupBox_2)
        self.tlTopButton.setObjectName(_fromUtf8("tlTopButton"))
        self.vboxlayout.addWidget(self.tlTopButton)
        self.tlLeftButton = QtGui.QRadioButton(self.groupBox_2)
        self.tlLeftButton.setObjectName(_fromUtf8("tlLeftButton"))
        self.vboxlayout.addWidget(self.tlLeftButton)
        self.gridlayout1.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_5)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.trTopButton = QtGui.QRadioButton(self.groupBox_5)
        self.trTopButton.setObjectName(_fromUtf8("trTopButton"))
        self.vboxlayout1.addWidget(self.trTopButton)
        self.trRightButton = QtGui.QRadioButton(self.groupBox_5)
        self.trRightButton.setObjectName(_fromUtf8("trRightButton"))
        self.vboxlayout1.addWidget(self.trRightButton)
        self.gridlayout1.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.blBottomButton = QtGui.QRadioButton(self.groupBox_6)
        self.blBottomButton.setObjectName(_fromUtf8("blBottomButton"))
        self.vboxlayout2.addWidget(self.blBottomButton)
        self.blLeftButton = QtGui.QRadioButton(self.groupBox_6)
        self.blLeftButton.setObjectName(_fromUtf8("blLeftButton"))
        self.vboxlayout2.addWidget(self.blLeftButton)
        self.gridlayout1.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.vboxlayout3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.vboxlayout3.setObjectName(_fromUtf8("vboxlayout3"))
        self.brTopButton = QtGui.QRadioButton(self.groupBox_7)
        self.brTopButton.setObjectName(_fromUtf8("brTopButton"))
        self.vboxlayout3.addWidget(self.brTopButton)
        self.brRightButton = QtGui.QRadioButton(self.groupBox_7)
        self.brRightButton.setObjectName(_fromUtf8("brRightButton"))
        self.vboxlayout3.addWidget(self.brRightButton)
        self.gridlayout1.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_8 = QtGui.QGroupBox(InterfacePage)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.delaySpinBox = QtGui.QSpinBox(self.groupBox_8)
        self.delaySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.delaySpinBox.setMaximum(2000)
        self.delaySpinBox.setSingleStep(100)
        self.delaySpinBox.setProperty("value", 200)
        self.delaySpinBox.setObjectName(_fromUtf8("delaySpinBox"))
        self.horizontalLayout_3.addWidget(self.delaySpinBox)
        spacerItem2 = QtGui.QSpacerItem(396, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.line9_2 = QtGui.QFrame(InterfacePage)
        self.line9_2.setFrameShape(QtGui.QFrame.HLine)
        self.line9_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_2.setFrameShape(QtGui.QFrame.HLine)
        self.line9_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_2.setObjectName(_fromUtf8("line9_2"))
        self.verticalLayout_3.addWidget(self.line9_2)
        self.TextLabel1_2_2_2 = QtGui.QLabel(InterfacePage)
        self.TextLabel1_2_2_2.setObjectName(_fromUtf8("TextLabel1_2_2_2"))
        self.verticalLayout_3.addWidget(self.TextLabel1_2_2_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.languageLabel = QtGui.QLabel(InterfacePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageLabel.sizePolicy().hasHeightForWidth())
        self.languageLabel.setSizePolicy(sizePolicy)
        self.languageLabel.setObjectName(_fromUtf8("languageLabel"))
        self.gridLayout.addWidget(self.languageLabel, 0, 0, 1, 1)
        self.languageComboBox = QtGui.QComboBox(InterfacePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.languageComboBox.sizePolicy().hasHeightForWidth())
        self.languageComboBox.setSizePolicy(sizePolicy)
        self.languageComboBox.setObjectName(_fromUtf8("languageComboBox"))
        self.gridLayout.addWidget(self.languageComboBox, 0, 1, 1, 1)
        self.layoutLabel = QtGui.QLabel(InterfacePage)
        self.layoutLabel.setObjectName(_fromUtf8("layoutLabel"))
        self.gridLayout.addWidget(self.layoutLabel, 1, 0, 1, 1)
        self.layoutComboBox = QtGui.QComboBox(InterfacePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutComboBox.sizePolicy().hasHeightForWidth())
        self.layoutComboBox.setSizePolicy(sizePolicy)
        self.layoutComboBox.setObjectName(_fromUtf8("layoutComboBox"))
        self.layoutComboBox.addItem(_fromUtf8(""))
        self.layoutComboBox.addItem(_fromUtf8(""))
        self.layoutComboBox.addItem(_fromUtf8(""))
        self.layoutComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.layoutComboBox, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_9 = QtGui.QGroupBox(InterfacePage)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self._8 = QtGui.QVBoxLayout(self.groupBox_9)
        self._8.setObjectName(_fromUtf8("_8"))
        self.separateShellButton = QtGui.QRadioButton(self.groupBox_9)
        self.separateShellButton.setObjectName(_fromUtf8("separateShellButton"))
        self._8.addWidget(self.separateShellButton)
        self.debugEmbeddedShellButton = QtGui.QRadioButton(self.groupBox_9)
        self.debugEmbeddedShellButton.setObjectName(_fromUtf8("debugEmbeddedShellButton"))
        self._8.addWidget(self.debugEmbeddedShellButton)
        self.horizontalLayout.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(InterfacePage)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self._9 = QtGui.QVBoxLayout(self.groupBox_10)
        self._9.setObjectName(_fromUtf8("_9"))
        self.separateFileBrowserButton = QtGui.QRadioButton(self.groupBox_10)
        self.separateFileBrowserButton.setObjectName(_fromUtf8("separateFileBrowserButton"))
        self._9.addWidget(self.separateFileBrowserButton)
        self.debugEmbeddedFileBrowserButton = QtGui.QRadioButton(self.groupBox_10)
        self.debugEmbeddedFileBrowserButton.setObjectName(_fromUtf8("debugEmbeddedFileBrowserButton"))
        self._9.addWidget(self.debugEmbeddedFileBrowserButton)
        self.projectEmbeddedFileBrowserButton = QtGui.QRadioButton(self.groupBox_10)
        self.projectEmbeddedFileBrowserButton.setObjectName(_fromUtf8("projectEmbeddedFileBrowserButton"))
        self._9.addWidget(self.projectEmbeddedFileBrowserButton)
        self.horizontalLayout.addWidget(self.groupBox_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabsGroupBox = QtGui.QGroupBox(InterfacePage)
        self.tabsGroupBox.setObjectName(_fromUtf8("tabsGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabsGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabsCloseButtonCheckBox = QtGui.QCheckBox(self.tabsGroupBox)
        self.tabsCloseButtonCheckBox.setObjectName(_fromUtf8("tabsCloseButtonCheckBox"))
        self.verticalLayout_2.addWidget(self.tabsCloseButtonCheckBox)
        self.verticalLayout_3.addWidget(self.tabsGroupBox)
        self.dialogsGroupBox = QtGui.QGroupBox(InterfacePage)
        self.dialogsGroupBox.setObjectName(_fromUtf8("dialogsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.dialogsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uiKdeDialogsCheckBox = QtGui.QCheckBox(self.dialogsGroupBox)
        self.uiKdeDialogsCheckBox.setObjectName(_fromUtf8("uiKdeDialogsCheckBox"))
        self.verticalLayout.addWidget(self.uiKdeDialogsCheckBox)
        self.verticalLayout_3.addWidget(self.dialogsGroupBox)
        spacerItem3 = QtGui.QSpacerItem(537, 41, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.resetLayoutButton = QtGui.QPushButton(InterfacePage)
        self.resetLayoutButton.setObjectName(_fromUtf8("resetLayoutButton"))
        self.verticalLayout_3.addWidget(self.resetLayoutButton)
        self.languageLabel.setBuddy(self.languageComboBox)

        self.retranslateUi(InterfacePage)
        QtCore.QMetaObject.connectSlotsByName(InterfacePage)
        InterfacePage.setTabOrder(self.uiBrowsersListFoldersFirstCheckBox, self.uiBrowsersHideNonPublicCheckBox)
        InterfacePage.setTabOrder(self.uiBrowsersHideNonPublicCheckBox, self.uiBrowsersSortByOccurrenceCheckBox)
        InterfacePage.setTabOrder(self.uiBrowsersSortByOccurrenceCheckBox, self.fileFiltersEdit)
        InterfacePage.setTabOrder(self.fileFiltersEdit, self.lvAutoRaiseCheckBox)
        InterfacePage.setTabOrder(self.lvAutoRaiseCheckBox, self.stderrTextColourButton)
        InterfacePage.setTabOrder(self.stderrTextColourButton, self.uiCaptionShowsFilenameGroupBox)
        InterfacePage.setTabOrder(self.uiCaptionShowsFilenameGroupBox, self.filenameLengthSpinBox)
        InterfacePage.setTabOrder(self.filenameLengthSpinBox, self.styleComboBox)
        InterfacePage.setTabOrder(self.styleComboBox, self.styleSheetEdit)
        InterfacePage.setTabOrder(self.styleSheetEdit, self.styleSheetButton)
        InterfacePage.setTabOrder(self.styleSheetButton, self.tlTopButton)
        InterfacePage.setTabOrder(self.tlTopButton, self.tlLeftButton)
        InterfacePage.setTabOrder(self.tlLeftButton, self.trTopButton)
        InterfacePage.setTabOrder(self.trTopButton, self.trRightButton)
        InterfacePage.setTabOrder(self.trRightButton, self.blBottomButton)
        InterfacePage.setTabOrder(self.blBottomButton, self.blLeftButton)
        InterfacePage.setTabOrder(self.blLeftButton, self.brTopButton)
        InterfacePage.setTabOrder(self.brTopButton, self.brRightButton)
        InterfacePage.setTabOrder(self.brRightButton, self.delaySpinBox)
        InterfacePage.setTabOrder(self.delaySpinBox, self.languageComboBox)
        InterfacePage.setTabOrder(self.languageComboBox, self.layoutComboBox)
        InterfacePage.setTabOrder(self.layoutComboBox, self.separateShellButton)
        InterfacePage.setTabOrder(self.separateShellButton, self.debugEmbeddedShellButton)
        InterfacePage.setTabOrder(self.debugEmbeddedShellButton, self.separateFileBrowserButton)
        InterfacePage.setTabOrder(self.separateFileBrowserButton, self.debugEmbeddedFileBrowserButton)
        InterfacePage.setTabOrder(self.debugEmbeddedFileBrowserButton, self.projectEmbeddedFileBrowserButton)
        InterfacePage.setTabOrder(self.projectEmbeddedFileBrowserButton, self.tabsCloseButtonCheckBox)
        InterfacePage.setTabOrder(self.tabsCloseButtonCheckBox, self.uiKdeDialogsCheckBox)
        InterfacePage.setTabOrder(self.uiKdeDialogsCheckBox, self.resetLayoutButton)

    def retranslateUi(self, InterfacePage):
        self.headerLabel.setText(_translate("InterfacePage", "<b>Configure User Interface</b>", None))
        self.groupBox_4.setTitle(_translate("InterfacePage", "Browsers", None))
        self.uiBrowsersListFoldersFirstCheckBox.setToolTip(_translate("InterfacePage", "Select, if folders should be listed first in the various browsers", None))
        self.uiBrowsersListFoldersFirstCheckBox.setText(_translate("InterfacePage", "List folders first in Browsers", None))
        self.uiBrowsersHideNonPublicCheckBox.setToolTip(_translate("InterfacePage", "Select to hide non public classes, methods and attributes in the browsers.", None))
        self.uiBrowsersHideNonPublicCheckBox.setText(_translate("InterfacePage", "Hide non public members in Browsers", None))
        self.uiBrowsersSortByOccurrenceCheckBox.setToolTip(_translate("InterfacePage", "Select to sort file contents by occurrence", None))
        self.uiBrowsersSortByOccurrenceCheckBox.setText(_translate("InterfacePage", "Sort contents by occurrence", None))
        self.label_4.setText(_translate("InterfacePage", "Filter out files:", None))
        self.fileFiltersEdit.setToolTip(_translate("InterfacePage", "Enter wildcard file patterns separated by semicolon. Files matching these patterns will not be shown by the file browsers.", None))
        self.groupBox_3.setTitle(_translate("InterfacePage", "Log-Viewer", None))
        self.lvAutoRaiseCheckBox.setToolTip(_translate("InterfacePage", "Select to show the log-viewer upon new output", None))
        self.lvAutoRaiseCheckBox.setText(_translate("InterfacePage", "Show upon new output", None))
        self.TextLabel3_2_2.setText(_translate("InterfacePage", "Stderr Colour:", None))
        self.stderrTextColourButton.setToolTip(_translate("InterfacePage", "Select the colour for text sent to stderr", None))
        self.uiCaptionShowsFilenameGroupBox.setToolTip(_translate("InterfacePage", "Select, if the caption of the main window should show the filename of the current editor", None))
        self.uiCaptionShowsFilenameGroupBox.setTitle(_translate("InterfacePage", "Caption shows filename", None))
        self.label.setText(_translate("InterfacePage", "Filename Length", None))
        self.filenameLengthSpinBox.setToolTip(_translate("InterfacePage", "Enter the number of characters to be shown in the main window title.", None))
        self.label_2.setText(_translate("InterfacePage", "Style:", None))
        self.styleComboBox.setToolTip(_translate("InterfacePage", "Select the interface style", None))
        self.label_3.setText(_translate("InterfacePage", "Style Sheet:", None))
        self.styleSheetEdit.setToolTip(_translate("InterfacePage", "Enter the name of the style sheet file", None))
        self.styleSheetButton.setToolTip(_translate("InterfacePage", "Select the style sheet file via a file selection dialog", None))
        self.styleSheetButton.setText(_translate("InterfacePage", "...", None))
        self.groupBox.setTitle(_translate("InterfacePage", "Dockarea Corner Usage", None))
        self.groupBox_2.setTitle(_translate("InterfacePage", "Top Left Corner", None))
        self.tlTopButton.setToolTip(_translate("InterfacePage", "Select to assign the top left corner to the top dockarea", None))
        self.tlTopButton.setText(_translate("InterfacePage", "Top dockarea", None))
        self.tlLeftButton.setToolTip(_translate("InterfacePage", "Select to assign the top left corner to the left dockarea", None))
        self.tlLeftButton.setText(_translate("InterfacePage", "Left dockarea", None))
        self.groupBox_5.setTitle(_translate("InterfacePage", "Top Right Corner", None))
        self.trTopButton.setToolTip(_translate("InterfacePage", "Select to assign the top right corner to the top dockarea", None))
        self.trTopButton.setText(_translate("InterfacePage", "Top dockarea", None))
        self.trRightButton.setToolTip(_translate("InterfacePage", "Select to assign the top right corner to the right dockarea", None))
        self.trRightButton.setText(_translate("InterfacePage", "Right dockarea", None))
        self.groupBox_6.setTitle(_translate("InterfacePage", "Bottom Left Corner", None))
        self.blBottomButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom left corner to the bottom dockarea", None))
        self.blBottomButton.setText(_translate("InterfacePage", "Bottom dockarea", None))
        self.blLeftButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom left corner to the left dockarea", None))
        self.blLeftButton.setText(_translate("InterfacePage", "Left dockarea", None))
        self.groupBox_7.setTitle(_translate("InterfacePage", "Bottom Right Corner", None))
        self.brTopButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom right corner to the bottom dockarea", None))
        self.brTopButton.setText(_translate("InterfacePage", "Bottom dockarea", None))
        self.brRightButton.setToolTip(_translate("InterfacePage", "Select to assign the bottom right corner to the right dockarea", None))
        self.brRightButton.setText(_translate("InterfacePage", "Right dockarea", None))
        self.groupBox_8.setTitle(_translate("InterfacePage", "Sidebars", None))
        self.label_5.setText(_translate("InterfacePage", "Delay:", None))
        self.delaySpinBox.setSuffix(_translate("InterfacePage", " ms", None))
        self.TextLabel1_2_2_2.setText(_translate("InterfacePage", "<font color=\"#FF0000\"><b>Note:</b> All settings below are activated at the next startup of the application.</font>", None))
        self.languageLabel.setText(_translate("InterfacePage", "Language:", None))
        self.languageComboBox.setToolTip(_translate("InterfacePage", "Select the interface language.", None))
        self.languageComboBox.setWhatsThis(_translate("InterfacePage", "The interface language can be selected from this list. If \"system\" is selected, the interface language is determined by the system. The selection of \"none\" means, that the default language will be used.", None))
        self.layoutLabel.setText(_translate("InterfacePage", "Layout:", None))
        self.layoutComboBox.setToolTip(_translate("InterfacePage", "Select the layout type.", None))
        self.layoutComboBox.setItemText(0, _translate("InterfacePage", "Dock Windows", None))
        self.layoutComboBox.setItemText(1, _translate("InterfacePage", "Floating Windows ", None))
        self.layoutComboBox.setItemText(2, _translate("InterfacePage", "Toolboxes", None))
        self.layoutComboBox.setItemText(3, _translate("InterfacePage", "Sidebars", None))
        self.groupBox_9.setTitle(_translate("InterfacePage", "Shell", None))
        self.separateShellButton.setToolTip(_translate("InterfacePage", "Select to get a separate shell window", None))
        self.separateShellButton.setText(_translate("InterfacePage", "separate window", None))
        self.debugEmbeddedShellButton.setToolTip(_translate("InterfacePage", "Select to embed the shell in the Debug-Viewer", None))
        self.debugEmbeddedShellButton.setText(_translate("InterfacePage", "embed in Debug-Viewer", None))
        self.groupBox_10.setTitle(_translate("InterfacePage", "File-Browser", None))
        self.separateFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to get a separate file browser window", None))
        self.separateFileBrowserButton.setText(_translate("InterfacePage", "separate window", None))
        self.debugEmbeddedFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to embed the file browser in the Debug-Viewer", None))
        self.debugEmbeddedFileBrowserButton.setText(_translate("InterfacePage", "embed in Debug-Viewer", None))
        self.projectEmbeddedFileBrowserButton.setToolTip(_translate("InterfacePage", "Select to embed the file browser in the Project-Viewer", None))
        self.projectEmbeddedFileBrowserButton.setText(_translate("InterfacePage", "embed in Project-Viewer", None))
        self.tabsGroupBox.setTitle(_translate("InterfacePage", "Tabs", None))
        self.tabsCloseButtonCheckBox.setText(_translate("InterfacePage", "Show only one close button instead of one for each tab", None))
        self.dialogsGroupBox.setTitle(_translate("InterfacePage", "Dialogs", None))
        self.uiKdeDialogsCheckBox.setToolTip(_translate("InterfacePage", "Select, if KDE 4 dialogs should be used", None))
        self.uiKdeDialogsCheckBox.setText(_translate("InterfacePage", "Use KDE 4 dialogs", None))
        self.resetLayoutButton.setText(_translate("InterfacePage", "Reset layout to factory defaults", None))

