# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\PrinterPage.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrinterPage(object):
    def setupUi(self, PrinterPage):
        PrinterPage.setObjectName(_fromUtf8("PrinterPage"))
        PrinterPage.resize(446, 568)
        self.vboxlayout = QtGui.QVBoxLayout(PrinterPage)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.headerLabel = QtGui.QLabel(PrinterPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.vboxlayout.addWidget(self.headerLabel)
        self.line7 = QtGui.QFrame(PrinterPage)
        self.line7.setFrameShape(QtGui.QFrame.HLine)
        self.line7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line7.setFrameShape(QtGui.QFrame.HLine)
        self.line7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line7.setObjectName(_fromUtf8("line7"))
        self.vboxlayout.addWidget(self.line7)
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.frame_2 = QtGui.QFrame(PrinterPage)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.frame_2)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.printerColorButton = QtGui.QRadioButton(self.frame_2)
        self.printerColorButton.setObjectName(_fromUtf8("printerColorButton"))
        self.vboxlayout1.addWidget(self.printerColorButton)
        self.printerGrayscaleButton = QtGui.QRadioButton(self.frame_2)
        self.printerGrayscaleButton.setObjectName(_fromUtf8("printerGrayscaleButton"))
        self.vboxlayout1.addWidget(self.printerGrayscaleButton)
        self.gridlayout.addWidget(self.frame_2, 1, 1, 1, 2)
        self.frame = QtGui.QFrame(PrinterPage)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.frame)
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.printFirstPageFirstButton = QtGui.QRadioButton(self.frame)
        self.printFirstPageFirstButton.setObjectName(_fromUtf8("printFirstPageFirstButton"))
        self.vboxlayout2.addWidget(self.printFirstPageFirstButton)
        self.printFirstPageLastButton = QtGui.QRadioButton(self.frame)
        self.printFirstPageLastButton.setObjectName(_fromUtf8("printFirstPageLastButton"))
        self.vboxlayout2.addWidget(self.printFirstPageLastButton)
        self.gridlayout.addWidget(self.frame, 2, 1, 1, 2)
        self.printerNameEdit = QtGui.QLineEdit(PrinterPage)
        self.printerNameEdit.setObjectName(_fromUtf8("printerNameEdit"))
        self.gridlayout.addWidget(self.printerNameEdit, 0, 1, 1, 2)
        self.TextLabel1 = QtGui.QLabel(PrinterPage)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.gridlayout.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.TextLabel3 = QtGui.QLabel(PrinterPage)
        self.TextLabel3.setObjectName(_fromUtf8("TextLabel3"))
        self.gridlayout.addWidget(self.TextLabel3, 3, 0, 1, 1)
        self.printheaderFontSample = QtGui.QLineEdit(PrinterPage)
        self.printheaderFontSample.setFocusPolicy(QtCore.Qt.NoFocus)
        self.printheaderFontSample.setAlignment(QtCore.Qt.AlignHCenter)
        self.printheaderFontSample.setReadOnly(True)
        self.printheaderFontSample.setObjectName(_fromUtf8("printheaderFontSample"))
        self.gridlayout.addWidget(self.printheaderFontSample, 4, 1, 1, 2)
        self.printheaderFontButton = QtGui.QPushButton(PrinterPage)
        self.printheaderFontButton.setObjectName(_fromUtf8("printheaderFontButton"))
        self.gridlayout.addWidget(self.printheaderFontButton, 4, 0, 1, 1)
        self.printMagnificationSpinBox = QtGui.QSpinBox(PrinterPage)
        self.printMagnificationSpinBox.setMinimum(-10)
        self.printMagnificationSpinBox.setMaximum(10)
        self.printMagnificationSpinBox.setProperty("value", -3)
        self.printMagnificationSpinBox.setObjectName(_fromUtf8("printMagnificationSpinBox"))
        self.gridlayout.addWidget(self.printMagnificationSpinBox, 3, 1, 1, 1)
        self.TextLabel2 = QtGui.QLabel(PrinterPage)
        self.TextLabel2.setAlignment(QtCore.Qt.AlignTop)
        self.TextLabel2.setObjectName(_fromUtf8("TextLabel2"))
        self.gridlayout.addWidget(self.TextLabel2, 1, 0, 1, 1)
        self.TextLabel4 = QtGui.QLabel(PrinterPage)
        self.TextLabel4.setAlignment(QtCore.Qt.AlignTop)
        self.TextLabel4.setObjectName(_fromUtf8("TextLabel4"))
        self.gridlayout.addWidget(self.TextLabel4, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(251, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem, 3, 2, 1, 1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.groupBox = QtGui.QGroupBox(PrinterPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.topMarginSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.topMarginSpinBox.setDecimals(1)
        self.topMarginSpinBox.setMaximum(9.9)
        self.topMarginSpinBox.setSingleStep(0.5)
        self.topMarginSpinBox.setObjectName(_fromUtf8("topMarginSpinBox"))
        self.gridlayout1.addWidget(self.topMarginSpinBox, 0, 1, 1, 1)
        self.leftMarginSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.leftMarginSpinBox.setDecimals(1)
        self.leftMarginSpinBox.setMaximum(9.9)
        self.leftMarginSpinBox.setSingleStep(0.5)
        self.leftMarginSpinBox.setObjectName(_fromUtf8("leftMarginSpinBox"))
        self.gridlayout1.addWidget(self.leftMarginSpinBox, 1, 0, 1, 1)
        self.rightMarginSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.rightMarginSpinBox.setDecimals(1)
        self.rightMarginSpinBox.setMaximum(9.9)
        self.rightMarginSpinBox.setSingleStep(0.5)
        self.rightMarginSpinBox.setObjectName(_fromUtf8("rightMarginSpinBox"))
        self.gridlayout1.addWidget(self.rightMarginSpinBox, 1, 2, 1, 1)
        self.bottomMarginSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.bottomMarginSpinBox.setDecimals(1)
        self.bottomMarginSpinBox.setMaximum(9.9)
        self.bottomMarginSpinBox.setSingleStep(0.5)
        self.bottomMarginSpinBox.setObjectName(_fromUtf8("bottomMarginSpinBox"))
        self.gridlayout1.addWidget(self.bottomMarginSpinBox, 2, 1, 1, 1)
        self.hboxlayout.addWidget(self.groupBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.hboxlayout)
        spacerItem2 = QtGui.QSpacerItem(428, 61, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem2)

        self.retranslateUi(PrinterPage)
        QtCore.QMetaObject.connectSlotsByName(PrinterPage)
        PrinterPage.setTabOrder(self.printerNameEdit, self.printerColorButton)
        PrinterPage.setTabOrder(self.printerColorButton, self.printerGrayscaleButton)
        PrinterPage.setTabOrder(self.printerGrayscaleButton, self.printFirstPageFirstButton)
        PrinterPage.setTabOrder(self.printFirstPageFirstButton, self.printFirstPageLastButton)
        PrinterPage.setTabOrder(self.printFirstPageLastButton, self.printMagnificationSpinBox)
        PrinterPage.setTabOrder(self.printMagnificationSpinBox, self.printheaderFontButton)
        PrinterPage.setTabOrder(self.printheaderFontButton, self.topMarginSpinBox)
        PrinterPage.setTabOrder(self.topMarginSpinBox, self.leftMarginSpinBox)
        PrinterPage.setTabOrder(self.leftMarginSpinBox, self.rightMarginSpinBox)
        PrinterPage.setTabOrder(self.rightMarginSpinBox, self.bottomMarginSpinBox)

    def retranslateUi(self, PrinterPage):
        self.headerLabel.setText(_translate("PrinterPage", "<b>Configure printer settings</b>", None))
        self.printerColorButton.setText(_translate("PrinterPage", "Colour", None))
        self.printerGrayscaleButton.setText(_translate("PrinterPage", "Gray Scale", None))
        self.printFirstPageFirstButton.setText(_translate("PrinterPage", "First Page First", None))
        self.printFirstPageLastButton.setText(_translate("PrinterPage", "Last Page First", None))
        self.TextLabel1.setText(_translate("PrinterPage", "Printername:", None))
        self.TextLabel3.setText(_translate("PrinterPage", "Magnification:", None))
        self.printheaderFontSample.setText(_translate("PrinterPage", "Header Font", None))
        self.printheaderFontButton.setToolTip(_translate("PrinterPage", "Press to select the font for the page headers", None))
        self.printheaderFontButton.setText(_translate("PrinterPage", "Header Font", None))
        self.TextLabel2.setText(_translate("PrinterPage", "Colour Mode:", None))
        self.TextLabel4.setText(_translate("PrinterPage", "Page Order:", None))
        self.groupBox.setTitle(_translate("PrinterPage", "Margins", None))
        self.topMarginSpinBox.setToolTip(_translate("PrinterPage", "Enter the top margin in cm.", None))
        self.topMarginSpinBox.setSuffix(_translate("PrinterPage", " cm", None))
        self.leftMarginSpinBox.setToolTip(_translate("PrinterPage", "Enter the left margin in cm.", None))
        self.leftMarginSpinBox.setSuffix(_translate("PrinterPage", " cm", None))
        self.rightMarginSpinBox.setToolTip(_translate("PrinterPage", "Enter the right margin in cm.", None))
        self.rightMarginSpinBox.setSuffix(_translate("PrinterPage", " cm", None))
        self.bottomMarginSpinBox.setToolTip(_translate("PrinterPage", "Enter the bottom margin in cm.", None))
        self.bottomMarginSpinBox.setSuffix(_translate("PrinterPage", " cm", None))

