# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\ProjectPage.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProjectPage(object):
    def setupUi(self, ProjectPage):
        ProjectPage.setObjectName(_fromUtf8("ProjectPage"))
        ProjectPage.resize(602, 624)
        self.verticalLayout = QtGui.QVBoxLayout(ProjectPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.headerLabel = QtGui.QLabel(ProjectPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout.addWidget(self.headerLabel)
        self.line8 = QtGui.QFrame(ProjectPage)
        self.line8.setFrameShape(QtGui.QFrame.HLine)
        self.line8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line8.setFrameShape(QtGui.QFrame.HLine)
        self.line8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line8.setObjectName(_fromUtf8("line8"))
        self.verticalLayout.addWidget(self.line8)
        self.groupBox = QtGui.QGroupBox(ProjectPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.projectCompressedProjectFilesCheckBox = QtGui.QCheckBox(self.groupBox)
        self.projectCompressedProjectFilesCheckBox.setObjectName(_fromUtf8("projectCompressedProjectFilesCheckBox"))
        self.vboxlayout.addWidget(self.projectCompressedProjectFilesCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_6 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_6)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.projectTimestampCheckBox = QtGui.QCheckBox(self.groupBox_6)
        self.projectTimestampCheckBox.setObjectName(_fromUtf8("projectTimestampCheckBox"))
        self.vboxlayout1.addWidget(self.projectTimestampCheckBox)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.groupBox_2 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.projectSearchNewFilesRecursiveCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.projectSearchNewFilesRecursiveCheckBox.setObjectName(_fromUtf8("projectSearchNewFilesRecursiveCheckBox"))
        self.gridlayout.addWidget(self.projectSearchNewFilesRecursiveCheckBox, 0, 0, 1, 1)
        self.projectSearchNewFilesCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.projectSearchNewFilesCheckBox.setObjectName(_fromUtf8("projectSearchNewFilesCheckBox"))
        self.gridlayout.addWidget(self.projectSearchNewFilesCheckBox, 0, 1, 1, 1)
        self.projectAutoIncludeNewFilesCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.projectAutoIncludeNewFilesCheckBox.setEnabled(False)
        self.projectAutoIncludeNewFilesCheckBox.setObjectName(_fromUtf8("projectAutoIncludeNewFilesCheckBox"))
        self.gridlayout.addWidget(self.projectAutoIncludeNewFilesCheckBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox_4)
        self.gridlayout1.setObjectName(_fromUtf8("gridlayout1"))
        self.projectLoadDebugPropertiesCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.projectLoadDebugPropertiesCheckBox.setObjectName(_fromUtf8("projectLoadDebugPropertiesCheckBox"))
        self.gridlayout1.addWidget(self.projectLoadDebugPropertiesCheckBox, 0, 0, 1, 1)
        self.projectSaveDebugPropertiesCheckBox = QtGui.QCheckBox(self.groupBox_4)
        self.projectSaveDebugPropertiesCheckBox.setObjectName(_fromUtf8("projectSaveDebugPropertiesCheckBox"))
        self.gridlayout1.addWidget(self.projectSaveDebugPropertiesCheckBox, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout2.setObjectName(_fromUtf8("gridlayout2"))
        self.projectLoadSessionCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.projectLoadSessionCheckBox.setObjectName(_fromUtf8("projectLoadSessionCheckBox"))
        self.gridlayout2.addWidget(self.projectLoadSessionCheckBox, 0, 0, 1, 1)
        self.projectSaveSessionCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.projectSaveSessionCheckBox.setObjectName(_fromUtf8("projectSaveSessionCheckBox"))
        self.gridlayout2.addWidget(self.projectSaveSessionCheckBox, 0, 1, 1, 1)
        self.projectSessionAllBpCheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.projectSessionAllBpCheckBox.setObjectName(_fromUtf8("projectSessionAllBpCheckBox"))
        self.gridlayout2.addWidget(self.projectSessionAllBpCheckBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridlayout3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridlayout3.setObjectName(_fromUtf8("gridlayout3"))
        self.projectAutoCompileFormsCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.projectAutoCompileFormsCheckBox.setObjectName(_fromUtf8("projectAutoCompileFormsCheckBox"))
        self.gridlayout3.addWidget(self.projectAutoCompileFormsCheckBox, 0, 0, 1, 1)
        self.projectAutoCompileResourcesCheckBox = QtGui.QCheckBox(self.groupBox_5)
        self.projectAutoCompileResourcesCheckBox.setObjectName(_fromUtf8("projectAutoCompileResourcesCheckBox"))
        self.gridlayout3.addWidget(self.projectAutoCompileResourcesCheckBox, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.groupBox_7 = QtGui.QGroupBox(ProjectPage)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox_7)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.projectRecentSpinBox = QtGui.QSpinBox(self.groupBox_7)
        self.projectRecentSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.projectRecentSpinBox.setMinimum(5)
        self.projectRecentSpinBox.setMaximum(50)
        self.projectRecentSpinBox.setObjectName(_fromUtf8("projectRecentSpinBox"))
        self.horizontalLayout.addWidget(self.projectRecentSpinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox_7)
        spacerItem1 = QtGui.QSpacerItem(584, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(ProjectPage)
        QtCore.QObject.connect(self.projectSearchNewFilesCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.projectAutoIncludeNewFilesCheckBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(ProjectPage)
        ProjectPage.setTabOrder(self.projectCompressedProjectFilesCheckBox, self.projectTimestampCheckBox)
        ProjectPage.setTabOrder(self.projectTimestampCheckBox, self.projectSearchNewFilesRecursiveCheckBox)
        ProjectPage.setTabOrder(self.projectSearchNewFilesRecursiveCheckBox, self.projectSearchNewFilesCheckBox)
        ProjectPage.setTabOrder(self.projectSearchNewFilesCheckBox, self.projectAutoIncludeNewFilesCheckBox)
        ProjectPage.setTabOrder(self.projectAutoIncludeNewFilesCheckBox, self.projectLoadSessionCheckBox)
        ProjectPage.setTabOrder(self.projectLoadSessionCheckBox, self.projectSaveSessionCheckBox)
        ProjectPage.setTabOrder(self.projectSaveSessionCheckBox, self.projectSessionAllBpCheckBox)
        ProjectPage.setTabOrder(self.projectSessionAllBpCheckBox, self.projectLoadDebugPropertiesCheckBox)
        ProjectPage.setTabOrder(self.projectLoadDebugPropertiesCheckBox, self.projectSaveDebugPropertiesCheckBox)
        ProjectPage.setTabOrder(self.projectSaveDebugPropertiesCheckBox, self.projectAutoCompileFormsCheckBox)
        ProjectPage.setTabOrder(self.projectAutoCompileFormsCheckBox, self.projectAutoCompileResourcesCheckBox)
        ProjectPage.setTabOrder(self.projectAutoCompileResourcesCheckBox, self.projectRecentSpinBox)

    def retranslateUi(self, ProjectPage):
        self.headerLabel.setText(_translate("ProjectPage", "<b>Configure project settings</b>", None))
        self.groupBox.setTitle(_translate("ProjectPage", "Compression", None))
        self.projectCompressedProjectFilesCheckBox.setToolTip(_translate("ProjectPage", "Select, if the project file of a new project should be compressed", None))
        self.projectCompressedProjectFilesCheckBox.setText(_translate("ProjectPage", "Compress project file upon creation", None))
        self.groupBox_6.setTitle(_translate("ProjectPage", "XML", None))
        self.projectTimestampCheckBox.setToolTip(_translate("ProjectPage", "Select, if a timestamp should be written to all project related XML files", None))
        self.projectTimestampCheckBox.setText(_translate("ProjectPage", "Include timestamp in project related XML files", None))
        self.groupBox_2.setTitle(_translate("ProjectPage", "Search new files", None))
        self.projectSearchNewFilesRecursiveCheckBox.setText(_translate("ProjectPage", "Search for new files recursively", None))
        self.projectSearchNewFilesCheckBox.setToolTip(_translate("ProjectPage", "Select whether a search for new files on a project open should be performed.", None))
        self.projectSearchNewFilesCheckBox.setText(_translate("ProjectPage", "Search for new files on open", None))
        self.projectAutoIncludeNewFilesCheckBox.setToolTip(_translate("ProjectPage", "Select whether the found files should be included automatically.", None))
        self.projectAutoIncludeNewFilesCheckBox.setText(_translate("ProjectPage", "Automatically include found files", None))
        self.groupBox_4.setTitle(_translate("ProjectPage", "Debugger Properties", None))
        self.projectLoadDebugPropertiesCheckBox.setToolTip(_translate("ProjectPage", "Select, whether a project debugger properties file shall be read on opening the project", None))
        self.projectLoadDebugPropertiesCheckBox.setText(_translate("ProjectPage", "Load debugger properties upon opening", None))
        self.projectSaveDebugPropertiesCheckBox.setToolTip(_translate("ProjectPage", "Select, whether a project debugger properties file shall be written on closing the project", None))
        self.projectSaveDebugPropertiesCheckBox.setText(_translate("ProjectPage", "Save debugger properties upon closing", None))
        self.groupBox_3.setTitle(_translate("ProjectPage", "Sessions", None))
        self.projectLoadSessionCheckBox.setToolTip(_translate("ProjectPage", "Select, whether a project session file shall be read on opening the project", None))
        self.projectLoadSessionCheckBox.setText(_translate("ProjectPage", "Load session upon opening", None))
        self.projectSaveSessionCheckBox.setToolTip(_translate("ProjectPage", "Select, whether a project session file shall be written on closing the project", None))
        self.projectSaveSessionCheckBox.setText(_translate("ProjectPage", "Save session upon closing", None))
        self.projectSessionAllBpCheckBox.setToolTip(_translate("ProjectPage", "Select whether all breakpoints should be saved to the session file.", None))
        self.projectSessionAllBpCheckBox.setText(_translate("ProjectPage", "Save all breakpoints", None))
        self.groupBox_5.setTitle(_translate("ProjectPage", "Automatically compile", None))
        self.projectAutoCompileFormsCheckBox.setToolTip(_translate("ProjectPage", "Select, if changed forms should be compiled automatically upon a run action", None))
        self.projectAutoCompileFormsCheckBox.setText(_translate("ProjectPage", "changed forms", None))
        self.projectAutoCompileResourcesCheckBox.setToolTip(_translate("ProjectPage", "Select, if changed resources should be compiled automatically upon a run action", None))
        self.projectAutoCompileResourcesCheckBox.setText(_translate("ProjectPage", "changed resources", None))
        self.groupBox_7.setTitle(_translate("ProjectPage", "Recent Projects", None))
        self.label.setText(_translate("ProjectPage", "Number of recent projects:", None))
        self.projectRecentSpinBox.setToolTip(_translate("ProjectPage", "Enter the number of recent projects to remember", None))

