# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Preferences\ConfigurationPages\VcsPage.ui'
#
# Created: Fri Apr 18 09:56:43 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VcsPage(object):
    def setupUi(self, VcsPage):
        VcsPage.setObjectName(_fromUtf8("VcsPage"))
        VcsPage.resize(619, 572)
        self.verticalLayout = QtGui.QVBoxLayout(VcsPage)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.headerLabel = QtGui.QLabel(VcsPage)
        self.headerLabel.setObjectName(_fromUtf8("headerLabel"))
        self.verticalLayout.addWidget(self.headerLabel)
        self.line9_3_2_2 = QtGui.QFrame(VcsPage)
        self.line9_3_2_2.setFrameShape(QtGui.QFrame.HLine)
        self.line9_3_2_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_3_2_2.setFrameShape(QtGui.QFrame.HLine)
        self.line9_3_2_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line9_3_2_2.setObjectName(_fromUtf8("line9_3_2_2"))
        self.verticalLayout.addWidget(self.line9_3_2_2)
        self.vcsAutoCloseCheckBox = QtGui.QCheckBox(VcsPage)
        self.vcsAutoCloseCheckBox.setObjectName(_fromUtf8("vcsAutoCloseCheckBox"))
        self.verticalLayout.addWidget(self.vcsAutoCloseCheckBox)
        self.groupBox = QtGui.QGroupBox(VcsPage)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.vcsAutoSaveCheckBox = QtGui.QCheckBox(self.groupBox)
        self.vcsAutoSaveCheckBox.setObjectName(_fromUtf8("vcsAutoSaveCheckBox"))
        self.vboxlayout.addWidget(self.vcsAutoSaveCheckBox)
        self.vcsAutoSaveProjectCheckBox = QtGui.QCheckBox(self.groupBox)
        self.vcsAutoSaveProjectCheckBox.setObjectName(_fromUtf8("vcsAutoSaveProjectCheckBox"))
        self.vboxlayout.addWidget(self.vcsAutoSaveProjectCheckBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(VcsPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.vcsStatusMonitorIntervalSpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.vcsStatusMonitorIntervalSpinBox.setMaximum(3600)
        self.vcsStatusMonitorIntervalSpinBox.setObjectName(_fromUtf8("vcsStatusMonitorIntervalSpinBox"))
        self.gridLayout_2.addWidget(self.vcsStatusMonitorIntervalSpinBox, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.vcsMonitorLocalStatusCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.vcsMonitorLocalStatusCheckBox.setObjectName(_fromUtf8("vcsMonitorLocalStatusCheckBox"))
        self.gridLayout_2.addWidget(self.vcsMonitorLocalStatusCheckBox, 1, 0, 1, 2)
        self.autoUpdateCheckBox = QtGui.QCheckBox(self.groupBox_2)
        self.autoUpdateCheckBox.setObjectName(_fromUtf8("autoUpdateCheckBox"))
        self.gridLayout_2.addWidget(self.autoUpdateCheckBox, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(VcsPage)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.pbVcsAddedButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsAddedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsAddedButton.setText(_fromUtf8(""))
        self.pbVcsAddedButton.setObjectName(_fromUtf8("pbVcsAddedButton"))
        self.gridLayout.addWidget(self.pbVcsAddedButton, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.pbVcsConflictButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsConflictButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsConflictButton.setText(_fromUtf8(""))
        self.pbVcsConflictButton.setObjectName(_fromUtf8("pbVcsConflictButton"))
        self.gridLayout.addWidget(self.pbVcsConflictButton, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pbVcsModifiedButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsModifiedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsModifiedButton.setText(_fromUtf8(""))
        self.pbVcsModifiedButton.setObjectName(_fromUtf8("pbVcsModifiedButton"))
        self.gridLayout.addWidget(self.pbVcsModifiedButton, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.pbVcsReplacedButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsReplacedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsReplacedButton.setText(_fromUtf8(""))
        self.pbVcsReplacedButton.setObjectName(_fromUtf8("pbVcsReplacedButton"))
        self.gridLayout.addWidget(self.pbVcsReplacedButton, 1, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pbVcsUpdateButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsUpdateButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsUpdateButton.setText(_fromUtf8(""))
        self.pbVcsUpdateButton.setObjectName(_fromUtf8("pbVcsUpdateButton"))
        self.gridLayout.addWidget(self.pbVcsUpdateButton, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.pbVcsRemovedButton = QtGui.QPushButton(self.groupBox_3)
        self.pbVcsRemovedButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pbVcsRemovedButton.setText(_fromUtf8(""))
        self.pbVcsRemovedButton.setObjectName(_fromUtf8("pbVcsRemovedButton"))
        self.gridLayout.addWidget(self.pbVcsRemovedButton, 2, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        spacerItem2 = QtGui.QSpacerItem(512, 81, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(VcsPage)
        QtCore.QMetaObject.connectSlotsByName(VcsPage)
        VcsPage.setTabOrder(self.vcsAutoCloseCheckBox, self.vcsAutoSaveCheckBox)
        VcsPage.setTabOrder(self.vcsAutoSaveCheckBox, self.vcsAutoSaveProjectCheckBox)
        VcsPage.setTabOrder(self.vcsAutoSaveProjectCheckBox, self.vcsStatusMonitorIntervalSpinBox)
        VcsPage.setTabOrder(self.vcsStatusMonitorIntervalSpinBox, self.vcsMonitorLocalStatusCheckBox)
        VcsPage.setTabOrder(self.vcsMonitorLocalStatusCheckBox, self.autoUpdateCheckBox)
        VcsPage.setTabOrder(self.autoUpdateCheckBox, self.pbVcsAddedButton)
        VcsPage.setTabOrder(self.pbVcsAddedButton, self.pbVcsModifiedButton)
        VcsPage.setTabOrder(self.pbVcsModifiedButton, self.pbVcsUpdateButton)
        VcsPage.setTabOrder(self.pbVcsUpdateButton, self.pbVcsConflictButton)
        VcsPage.setTabOrder(self.pbVcsConflictButton, self.pbVcsReplacedButton)

    def retranslateUi(self, VcsPage):
        self.headerLabel.setText(_translate("VcsPage", "<b>Configure Version Control Systems</b>", None))
        self.vcsAutoCloseCheckBox.setText(_translate("VcsPage", "Close VCS dialog automatically, if no error occured", None))
        self.groupBox.setTitle(_translate("VcsPage", "Commit", None))
        self.vcsAutoSaveCheckBox.setToolTip(_translate("VcsPage", "Select, if files should be saved before a commit", None))
        self.vcsAutoSaveCheckBox.setText(_translate("VcsPage", "Save files upon commit", None))
        self.vcsAutoSaveProjectCheckBox.setToolTip(_translate("VcsPage", "Select, if project should be saved before a commit", None))
        self.vcsAutoSaveProjectCheckBox.setText(_translate("VcsPage", "Save project upon commit", None))
        self.groupBox_2.setTitle(_translate("VcsPage", "Status Monitor", None))
        self.vcsStatusMonitorIntervalSpinBox.setToolTip(_translate("VcsPage", "Select the interval in seconds for VCS status updates (0 to disable)", None))
        self.vcsStatusMonitorIntervalSpinBox.setSuffix(_translate("VcsPage", " sec", None))
        self.vcsMonitorLocalStatusCheckBox.setToolTip(_translate("VcsPage", "Select to monitor local status only (if supported by VCS)", None))
        self.vcsMonitorLocalStatusCheckBox.setText(_translate("VcsPage", "Monitor local status only", None))
        self.autoUpdateCheckBox.setToolTip(_translate("VcsPage", "Select to enable automatic updates", None))
        self.autoUpdateCheckBox.setText(_translate("VcsPage", "Automatic updates enabled", None))
        self.groupBox_3.setTitle(_translate("VcsPage", "Colours", None))
        self.label_4.setText(_translate("VcsPage", "VCS status \"added\":", None))
        self.pbVcsAddedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"added\".", None))
        self.label_5.setText(_translate("VcsPage", "VCS status \"conflict\":", None))
        self.pbVcsConflictButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"conflict\".", None))
        self.label_2.setText(_translate("VcsPage", "VCS status \"modified\":", None))
        self.pbVcsModifiedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"modified\".", None))
        self.label_6.setText(_translate("VcsPage", "VCS status \"replaced\":", None))
        self.pbVcsReplacedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"replaced\".", None))
        self.label_3.setText(_translate("VcsPage", "VCS status \"needs update\":", None))
        self.pbVcsUpdateButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"needs update\".", None))
        self.label_7.setText(_translate("VcsPage", "VCS status \"removed\":", None))
        self.pbVcsRemovedButton.setToolTip(_translate("VcsPage", "Select the background colour for entries with VCS status \"removed\".", None))

