# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eric\Plugins\WizardPlugins\ColorDialogWizard\ColorDialogWizardDialog.ui'
#
# Created: Fri Apr 18 09:56:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ColorDialogWizardDialog(object):
    def setupUi(self, ColorDialogWizardDialog):
        ColorDialogWizardDialog.setObjectName(_fromUtf8("ColorDialogWizardDialog"))
        ColorDialogWizardDialog.resize(367, 469)
        ColorDialogWizardDialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtGui.QVBoxLayout(ColorDialogWizardDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.qtGroup = QtGui.QGroupBox(ColorDialogWizardDialog)
        self.qtGroup.setObjectName(_fromUtf8("qtGroup"))
        self._2 = QtGui.QHBoxLayout(self.qtGroup)
        self._2.setObjectName(_fromUtf8("_2"))
        self.rQt40 = QtGui.QRadioButton(self.qtGroup)
        self.rQt40.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQt40.setObjectName(_fromUtf8("rQt40"))
        self._2.addWidget(self.rQt40)
        self.rQt45 = QtGui.QRadioButton(self.qtGroup)
        self.rQt45.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rQt45.setChecked(True)
        self.rQt45.setObjectName(_fromUtf8("rQt45"))
        self._2.addWidget(self.rQt45)
        spacerItem = QtGui.QSpacerItem(161, 21, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self._2.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.qtGroup)
        self.groupBox = QtGui.QGroupBox(ColorDialogWizardDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.hboxlayout = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.rColor = QtGui.QRadioButton(self.groupBox)
        self.rColor.setChecked(True)
        self.rColor.setObjectName(_fromUtf8("rColor"))
        self.hboxlayout.addWidget(self.rColor)
        self.rRGBA = QtGui.QRadioButton(self.groupBox)
        self.rRGBA.setObjectName(_fromUtf8("rRGBA"))
        self.hboxlayout.addWidget(self.rRGBA)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.titleGroup = QtGui.QGroupBox(ColorDialogWizardDialog)
        self.titleGroup.setObjectName(_fromUtf8("titleGroup"))
        self.verticalLayout = QtGui.QVBoxLayout(self.titleGroup)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.eTitle = QtGui.QLineEdit(self.titleGroup)
        self.eTitle.setObjectName(_fromUtf8("eTitle"))
        self.verticalLayout.addWidget(self.eTitle)
        self.verticalLayout_2.addWidget(self.titleGroup)
        self.groupBox_2 = QtGui.QGroupBox(ColorDialogWizardDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.vboxlayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.eColor = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eColor.sizePolicy().hasHeightForWidth())
        self.eColor.setSizePolicy(sizePolicy)
        self.eColor.setEditable(True)
        self.eColor.setObjectName(_fromUtf8("eColor"))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.setItemText(0, _fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.eColor.addItem(_fromUtf8(""))
        self.vboxlayout.addWidget(self.eColor)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(ColorDialogWizardDialog)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridlayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridlayout.setVerticalSpacing(6)
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.eRGB = QtGui.QLineEdit(self.groupBox_3)
        self.eRGB.setObjectName(_fromUtf8("eRGB"))
        self.gridlayout.addWidget(self.eRGB, 3, 0, 1, 4)
        self.TextLabel2 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel2.setObjectName(_fromUtf8("TextLabel2"))
        self.gridlayout.addWidget(self.TextLabel2, 2, 0, 1, 4)
        self.sAlpha = QtGui.QSpinBox(self.groupBox_3)
        self.sAlpha.setMaximum(255)
        self.sAlpha.setObjectName(_fromUtf8("sAlpha"))
        self.gridlayout.addWidget(self.sAlpha, 1, 3, 1, 1)
        self.sBlue = QtGui.QSpinBox(self.groupBox_3)
        self.sBlue.setMaximum(255)
        self.sBlue.setProperty("value", 128)
        self.sBlue.setObjectName(_fromUtf8("sBlue"))
        self.gridlayout.addWidget(self.sBlue, 1, 2, 1, 1)
        self.sGreen = QtGui.QSpinBox(self.groupBox_3)
        self.sGreen.setMaximum(255)
        self.sGreen.setProperty("value", 128)
        self.sGreen.setObjectName(_fromUtf8("sGreen"))
        self.gridlayout.addWidget(self.sGreen, 1, 1, 1, 1)
        self.sRed = QtGui.QSpinBox(self.groupBox_3)
        self.sRed.setMaximum(255)
        self.sRed.setProperty("value", 128)
        self.sRed.setObjectName(_fromUtf8("sRed"))
        self.gridlayout.addWidget(self.sRed, 1, 0, 1, 1)
        self.TextLabel1_4 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel1_4.setObjectName(_fromUtf8("TextLabel1_4"))
        self.gridlayout.addWidget(self.TextLabel1_4, 0, 3, 1, 1)
        self.TextLabel1_3 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel1_3.setObjectName(_fromUtf8("TextLabel1_3"))
        self.gridlayout.addWidget(self.TextLabel1_3, 0, 2, 1, 1)
        self.TextLabel1 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel1.setObjectName(_fromUtf8("TextLabel1"))
        self.gridlayout.addWidget(self.TextLabel1, 0, 0, 1, 1)
        self.TextLabel1_2 = QtGui.QLabel(self.groupBox_3)
        self.TextLabel1_2.setObjectName(_fromUtf8("TextLabel1_2"))
        self.gridlayout.addWidget(self.TextLabel1_2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.buttonBox = QtGui.QDialogButtonBox(ColorDialogWizardDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ColorDialogWizardDialog)
        QtCore.QObject.connect(self.rColor, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_2.setEnabled)
        QtCore.QObject.connect(self.rRGBA, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.groupBox_3.setEnabled)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ColorDialogWizardDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ColorDialogWizardDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ColorDialogWizardDialog)
        ColorDialogWizardDialog.setTabOrder(self.rQt40, self.rQt45)
        ColorDialogWizardDialog.setTabOrder(self.rQt45, self.rColor)
        ColorDialogWizardDialog.setTabOrder(self.rColor, self.rRGBA)
        ColorDialogWizardDialog.setTabOrder(self.rRGBA, self.eTitle)
        ColorDialogWizardDialog.setTabOrder(self.eTitle, self.eColor)
        ColorDialogWizardDialog.setTabOrder(self.eColor, self.sRed)
        ColorDialogWizardDialog.setTabOrder(self.sRed, self.sGreen)
        ColorDialogWizardDialog.setTabOrder(self.sGreen, self.sBlue)
        ColorDialogWizardDialog.setTabOrder(self.sBlue, self.sAlpha)
        ColorDialogWizardDialog.setTabOrder(self.sAlpha, self.eRGB)
        ColorDialogWizardDialog.setTabOrder(self.eRGB, self.buttonBox)

    def retranslateUi(self, ColorDialogWizardDialog):
        ColorDialogWizardDialog.setWindowTitle(_translate("ColorDialogWizardDialog", "QColorDialog Wizard", None))
        self.qtGroup.setTitle(_translate("ColorDialogWizardDialog", "Qt Version", None))
        self.rQt40.setToolTip(_translate("ColorDialogWizardDialog", "Select to generate code for Qt 4.0.0 but less than Qt 4.5.0", None))
        self.rQt40.setText(_translate("ColorDialogWizardDialog", "Qt 4.0", None))
        self.rQt45.setToolTip(_translate("ColorDialogWizardDialog", "Select to generate code for Qt 4.5.0 or newer", None))
        self.rQt45.setText(_translate("ColorDialogWizardDialog", "Qt 4.5", None))
        self.groupBox.setTitle(_translate("ColorDialogWizardDialog", "Type", None))
        self.rColor.setToolTip(_translate("ColorDialogWizardDialog", "Select to generate a QColorDialog.getColor dialog", None))
        self.rColor.setText(_translate("ColorDialogWizardDialog", "Colour", None))
        self.rRGBA.setToolTip(_translate("ColorDialogWizardDialog", "Select to generate a QColorDialog.getRgba dialog", None))
        self.rRGBA.setText(_translate("ColorDialogWizardDialog", "RGBA", None))
        self.titleGroup.setTitle(_translate("ColorDialogWizardDialog", "Title", None))
        self.eTitle.setToolTip(_translate("ColorDialogWizardDialog", "Enter the dialog title", None))
        self.groupBox_2.setTitle(_translate("ColorDialogWizardDialog", "Colour", None))
        self.eColor.setToolTip(_translate("ColorDialogWizardDialog", "Enter a variable name or a colour", None))
        self.eColor.setItemText(1, _translate("ColorDialogWizardDialog", "Qt.red", None))
        self.eColor.setItemText(2, _translate("ColorDialogWizardDialog", "Qt.darkRed", None))
        self.eColor.setItemText(3, _translate("ColorDialogWizardDialog", "Qt.green", None))
        self.eColor.setItemText(4, _translate("ColorDialogWizardDialog", "Qt.darkGreen", None))
        self.eColor.setItemText(5, _translate("ColorDialogWizardDialog", "Qt.blue", None))
        self.eColor.setItemText(6, _translate("ColorDialogWizardDialog", "Qt.darkBlue", None))
        self.eColor.setItemText(7, _translate("ColorDialogWizardDialog", "Qt.cyan", None))
        self.eColor.setItemText(8, _translate("ColorDialogWizardDialog", "Qt.darkCyan", None))
        self.eColor.setItemText(9, _translate("ColorDialogWizardDialog", "Qt.magenta", None))
        self.eColor.setItemText(10, _translate("ColorDialogWizardDialog", "Qt.darkMagenta", None))
        self.eColor.setItemText(11, _translate("ColorDialogWizardDialog", "Qt.yellow", None))
        self.eColor.setItemText(12, _translate("ColorDialogWizardDialog", "Qt.darkYellow", None))
        self.eColor.setItemText(13, _translate("ColorDialogWizardDialog", "Qt.white", None))
        self.eColor.setItemText(14, _translate("ColorDialogWizardDialog", "Qt.lightGray", None))
        self.eColor.setItemText(15, _translate("ColorDialogWizardDialog", "Qt.gray", None))
        self.eColor.setItemText(16, _translate("ColorDialogWizardDialog", "Qt.darkGray", None))
        self.eColor.setItemText(17, _translate("ColorDialogWizardDialog", "Qt.black", None))
        self.eColor.setItemText(18, _translate("ColorDialogWizardDialog", "Qt.transparent", None))
        self.eColor.setItemText(19, _translate("ColorDialogWizardDialog", "Qt.color0", None))
        self.eColor.setItemText(20, _translate("ColorDialogWizardDialog", "Qt.color1", None))
        self.groupBox_3.setTitle(_translate("ColorDialogWizardDialog", "RGBA", None))
        self.eRGB.setToolTip(_translate("ColorDialogWizardDialog", "Enter a variable name", None))
        self.TextLabel2.setText(_translate("ColorDialogWizardDialog", "Variable", None))
        self.sAlpha.setToolTip(_translate("ColorDialogWizardDialog", "Enter the alpha value", None))
        self.sBlue.setToolTip(_translate("ColorDialogWizardDialog", "Enter the blue value", None))
        self.sGreen.setToolTip(_translate("ColorDialogWizardDialog", "Enter the green value", None))
        self.sRed.setToolTip(_translate("ColorDialogWizardDialog", "Enter the red value", None))
        self.TextLabel1_4.setText(_translate("ColorDialogWizardDialog", "Alpha", None))
        self.TextLabel1_3.setText(_translate("ColorDialogWizardDialog", "Blue", None))
        self.TextLabel1.setText(_translate("ColorDialogWizardDialog", "Red", None))
        self.TextLabel1_2.setText(_translate("ColorDialogWizardDialog", "Green", None))

